### ISSUE TITLE
Working on NonbondedForce

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#1]
This is actually pretty complicated, so won't finish tonight.  Will review my progress with you tomorrow.

**Comment by jchodera** [comment]
It looks like we will have a number of special cases for the `NonbondedForce` interactions involving the small molecule being alchemically transformed:

### Sterics
* Pair interactions where `epsilon` and `sigma` do not change from A to B states should not be softened at intermediate `lambda`
* Pair interactions in which one atom is disappearing in one state (A or B) but not the other will have `epsilon = 0` in that state, and should remained alchemically softcore in that state to avoid sampling issues, using a schedule like `(1-lambda)` or `lambda` depending on the state (A or B) in which the atom disappears.
* Pair interactions in which the parameters are just changing from one set to another set should be softened at intermediate `lambda` using a schedule like `lambda*(1-lambda)` so that physical interactions are recovered at `lambda = 0` and `lambda = 1`.

### Electrostatics
* Pair interactions where `chargeProd` does not change should not be softened
* Pair interactions in which `chargeProd = 0` at one state (A or B) but not the other will remain alchemically softcore in that endstate
* Pair interactions in which parameters are changing will be softened at intermediate `lambda` using a schedule like `lambda*(1-lambda)` so that physical interactions are recovered at `lambda = 0` and `lambda = 1`.

If we want the full generality of being able to tweak all of these choices individually, I can separate out some options.  Also, we can separate the `lambda` values into different components if we want to play with different alchemical pathways.

**Comment by pgrinaway** [comment]
Should this discussion be moved to examol?

**Comment by jchodera** [comment]
Whoops, yes!  Will do.
