### ISSUE TITLE
PointMutationEngine should set chemical_state_key in TopologyProposal

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#100]
#97 has `SmallMoleculeProposalEngine` set `chemical_state_key`, but it doesn't look like the `PolymerProposalEngine`s (like `PointMutationEngine`) does this.

@juliebehr @pgrinaway can you fix?

We should make `chemical_state_key` mandatory in `TopologyProposal`, since none of the sampler swill work without it.

**Comment by pgrinaway** [comment]
That's a good point. I have an open PR so I'll fix the issues related to the chemical_state_key in that tomorrow.

**Comment by jchodera** [comment]
For the purposes of initializing the samplers, I also need to figure out how to set the *initial* chemical state key the sampler is started in.  

This means we either need:
* a well-documented description of how the state key is defined for each kind of `ProposalEngine` so that we can make one by hand when initializing a sampler
* a method in `ProposalEngine` that computes the key corresponding to a given `Topology`, like
```
proposal_engine = PointMutationEngine(system_generators[environment], max_point_mutants=1, proposal_metadata=proposal_metadata)
state_key = proposal_engine.computeStateKey(topology)
# now I can initialize my sampler to start in `state_key`...
```

**Comment by pgrinaway** [comment]
>a method in ProposalEngine that computes the key corresponding to a given Topology, like

I like this one. I already have code that computes the current state key (per a discussion earlier), so it would be easy to make it into its own method.

**Comment by juliebehr** [comment]
Resolved https://github.com/choderalab/perses/pull/108
