### ISSUE TITLE
Make `metadata` optional?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#101]
There are lots of places where we have a mandatory `metadata` argument (such as everywhere in the geometry engine) even though it isn't used yet.  Can we make this an optional argument that defaults to `dict()` or `None`?

**Comment by pgrinaway** [comment]
+1. I think defaulting to `None` is a good option here.

**Comment by pgrinaway** [comment]
I've done that for the small molecule engine in #105 , but I think `metadata` is actually used in the polymer proposal engines.

**Comment by jchodera** [comment]
>  I think metadata is actually used in the polymer proposal engines.

@juliebehr can we get that fixed?  In #103 it seems that `chain_id` should really be in the constructor, and not `metadata`.

**Comment by juliebehr** [comment]
I'm storing the information about what mutations have been made in ```metadata```, where should this go instead?  Also, the constructor has its own ```proposal_metadata``` (which has been there the whole time, I was just following the skeleton) which I'm currently only using to pass ```ffxml```s; should I make them their own argument and remove ```proposal_metadata``` too?

**Comment by juliebehr** [comment]
I just saw that the ```ffxml```s are addressed in https://github.com/choderalab/perses/issues/95 and yes I can easily change them to be retrieved from SystemGenerator -- so then the point remains, just to clarify we're eliminating both ```metadata``` and ```proposal_metadata```?

**Comment by jchodera** [comment]
Can we have chain_id in proposal_metadata in the constructor, or as a separate optional argument? This just gets it out of needing to be passed to propose() every time.

Totally OK to keep the current mutation info in the metadata associated with the current state. We also need to provide a way to get the current chemical state key.

**Comment by juliebehr** [comment]
Resolved https://github.com/choderalab/perses/pull/108
