### ISSUE TITLE
Store `chain_id` of chain to mutate in PointMutationEngine object during construction

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#103]
Initialization of `PointMutationEngine` should take the `chain_id` to mutate and store that, and any other information it needs.

`chain_id` currently needs to be passed in via `PointMutationEngine.propose()`, which doesn't seem reasonable since we would need to pass that in every time.  Instead, we should just take that at object construction time and cache it.

**Comment by jchodera** [comment]
Relevant code:
https://github.com/choderalab/perses/blob/master/perses/rjmc/topology_proposal.py#L268-L290

**Comment by pgrinaway** [comment]
Yeah, I think we want to make the `propose` methods as similar as possible--that way the classes can be easily interchanged.

**Comment by juliebehr** [comment]
Resolved https://github.com/choderalab/perses/pull/108
