### ISSUE TITLE
What other test systems should be added to perses.tests.testsystems?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#104]
In #92, I introduced an [alanine dipeptide test system](https://github.com/choderalab/perses/blob/samplers/perses/tests/testsystems.py#L52) that includes a ton of alanine-dipeptide goodness to make testing easier:
* three `environments`: `vacuum`, `implicit`, `explicit`
* `SystemGenerator`s for all environments
* initial `Topology` objects for all environments 
* initial `positions` for all environments
* `PointMutationProposalEngine`s for all environments
* `ThermodynamicState`s for all environments
* `MCMCSampler`s for all environments
* `ExpandedEnsembleSampler`s for all environments
* `SAMSSampler`s for all environments
* a `MultiTargetDesign` test sampler

What other kinds of systems would be useful to prepare this way?  Small, simple test systems we can use for quickly testing components would be useful here.

**Comment by jchodera** [comment]
Any other ideas here? Maybe small alkane hydration free energies?

I can also add your host guest system once we have the ability to write out multimolecule ffxml files. That is currently waiting on an implementation of loadmol2 in parmed, which Rafal is going to take a stab at.

**Comment by pgrinaway** [comment]
Alkane hydration free energies and host-guest would be good as well. Maybe some system with rings (like naphthalene)?

**Comment by jchodera** [comment]
@pgrinaway points out that relative solvation energies of amino acids is probably a good test system.  We can maybe adapt the alanine dipeptide test system for that.

@juliebehr : Maybe you could dig up some literature on amino acid hydration free energies or partition coefficients between different media?

**Comment by jchodera** [comment]
There are some T4 lysozyme L99A mutants that are actually worth @juliebehr  considering as a model system for looking at the impact of mutations on inhibitor binding:
* L99A: 
  * binders: http://www.bkslab.org/l99a-binders.php
  * nonbinders: http://www.bkslab.org/l99a-non-binders.php
* L99A/M102H: http://pubs.acs.org/doi/pdf/10.1021/jm301823g
* L99A/M102Q: 
  * binders: http://www.bkslab.org/l99a-m102q-binders.php
  * nonbinders: http://www.bkslab.org/l99a-m102q-non-binders.php

So we could consider a T4 lysozyme L99A "wild type" which also allows Met102 to sample `[MET, HIS, GLN]`.

**Comment by pgrinaway** [comment]
Tagging myself here to add some host-guest testsystems when we finish the other stuff.

**Comment by juliebehr** [comment]
Did we ever implement a T4 lysozyme test system for mutants (I know there is one for its inhibitors)?  Should I create one?

**Comment by jchodera** [comment]
I didn't implement one. Can you take a stab at this?

**Comment by juliebehr** [comment]
Yep!  Starting now

**Comment by pgrinaway** [comment]
Going to close this since we have a set of test systems.
