### ISSUE TITLE
Rename SystemGenerator.build_system to createSystem to match openmm.app.ForceField and ParmEd?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#107]
Would be nice to use `createSystem()` instead of `build_system` just to stay consistent with OpenMM and ParmEd naming conventions.

**Comment by pgrinaway** [comment]
Hm, I was trying to use Python-style naming conventions instead of C++ (not sure why OpenMM uses C++ naming conventions for a pure Python layer) but if it makes things easier I can change it.

**Comment by jchodera** [comment]
We can punt on this.

**Comment by pgrinaway** [comment]
sounds good.
