### ISSUE TITLE
S3 support 

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#1072]

**Comment by mikemhenry** [comment]
I'm thinking I keep https://github.com/choderalab/perses/pull/1073 around (and can build docker images off that branch) until we refactor, but I think we can punt this issue to `0.11.x` as part of a re-org of setup_relative_calculation.py and friends.

**Comment by ijpulidos** [comment]
Yes, we were thinking the same. I think it is better to handle this correctly after we have dealt with the API refactor first.

**Comment by ijpulidos** [comment]
Ok, on a second thought after our dev sync, we decided to keep this for our next release, since we are already using it for some of our docker containers. I'll take another look to the changes in the PR.
