### ISSUE TITLE
Change aromaticity drawing style

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#1082]
https://github.com/choderalab/perses/blob/87bc1d00c6c087b0dc13b38f83f5e2c4d13e012d/perses/rjmc/atom_mapping.py#L283-L286

https://docs.eyesopen.com/toolkits/python/depicttk/OEDepictClasses/OE2DMolDisplayOptions.html#OEDepict::OE2DMolDisplayOptions::SetAromaticStyle

**Comment by mikemhenry** [comment]
@ijpulidos @jchodera I can't remember the style we wanted, which one do we want to use?
https://docs.eyesopen.com/toolkits/python/depicttk/OEDepictConstants/OEAromaticStyle.html#id1

**Comment by mikemhenry** [comment]
I just went with `OEAromaticStyle_Circle` for the PR but I can change it.
