### ISSUE TITLE
Make sure ionic_strength is available as an option in CLI, and update example to specify this

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#1089]
We want to make sure that users of the new CLI can specify `ionic_strength` and make sure the new CLI example we have uses this explicitly.

**Comment by jchodera** [comment]
It looks like the [`ionic_strength` defaults to 150 mM](https://github.com/choderalab/perses/blob/7148b229805f0185adef65a3987cf3899219ed12/perses/app/relative_point_mutation_setup.py#L126).

**Comment by mikemhenry** [comment]
It is something we can set in the CLI:
https://github.com/choderalab/perses/blob/main/perses/app/setup_relative_calculation.py#L97-L98

But we need to document it as an example
