### ISSUE TITLE
`RelativeFEPSetup` cannot deal with list of ligand input files

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#1093]
In PR #1073 we included a way to deal with files from different cloud providers using `cloudpathlib`. But when doing this we generated a bug where if we pass a list of filenames for the `RelativeFEPSetup` object as the `ligand_input` parameter, we end up with an error like the following:
```python
Traceback (most recent call last):
  File "/home/user/workdir/debugging/perses/perses-new-issue/test_RelativeFEPSetup_API.py", line 19, in <module>
    fe_setup = RelativeFEPSetup(
  File "/home/user/miniconda3/envs/perses-1092-omm-nightly-test/lib/python3.9/site-packages/perses/app/relative_setup.py", line 165, in __init__
    self._ligand_input = AnyPath(ligand_input)
  File "/home/user/miniconda3/envs/perses-1092-omm-nightly-test/lib/python3.9/site-packages/cloudpathlib/anypath.py", line 38, in __new__
    raise AnyPathTypeError(
cloudpathlib.exceptions.AnyPathTypeError: Invalid input for both CloudPath and Path. CloudPath exception: InvalidPrefixError("Path ['./a1.sybyl.mol2', './a2.sybyl.mol2'] does not begin with a known prefix ['az://', 's3://', 'gs://'].") Path exception: TypeError('expected str, bytes or os.PathLike object, not list')
(perses-1092-omm-nightly-test) 
```
This is caused by trying to convert the list to an `cloudpathlib.AnyPath` object [here](https://github.com/choderalab/perses/blob/c96e65572b26cfdbce2d3ecaec7dae708e01568c/perses/app/relative_setup.py#L164-L165).

A quick fix would be to just convert the given `input_ligand` (or even `self._input_ligand`) to an `AnyPath` object after we check it isn't a list in [line 242](https://github.com/choderalab/perses/blob/c96e65572b26cfdbce2d3ecaec7dae708e01568c/perses/app/relative_setup.py#L242). 

A longer term solution would be to refactor how we are dealing with this and have special methods for each case (list or str path) instead of having the huge if-else blocks we currently have.

**Comment by ijpulidos** [comment]
I am attaching here the code to reproduce the issue

[test_RelativeFEPSetup_API.tar.gz](https://github.com/choderalab/perses/files/9419547/test_RelativeFEPSetup_API.tar.gz)

**Comment by mikemhenry** [comment]
We should add a CPU CI test for this as well.

**Comment by mikemhenry** [comment]
something like
```python
   if isinstance(input_ligand, str):
        input_ligand = AnyPath(input_ligand)
   else:
        input_ligand = [AnyPath(_) for _ in input_ligand]
```
