### ISSUE TITLE
Docs build check stopped working in github actions (GHA)

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#1094]
When creating new PRs and checking them we can see the docs build check from readthedocs is always stuck at "Expected -- Waiting for status to be reported" as shown in the following picture. This is affecting merge capabilities for new PRs, we need to figure out what is going on.

![image](https://user-images.githubusercontent.com/2949729/186539464-de9b72a3-bfa3-40c9-8e64-551447e85fb3.png)

**Comment by jchodera** [comment]
Just noticed this in readthedocs settings:
![image](https://user-images.githubusercontent.com/3656088/186541396-c08e271b-090a-4245-88c3-d85008f22e3e.png)

**Comment by jchodera** [comment]
Here are the relevant links to the [config file](https://docs.readthedocs.io/en/stable/config-file/v2.html) and [build.tools.python](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python).

**Comment by mikemhenry** [comment]
That looks like a warning for openff-toolkit, but that screenshot tells the story that  builds stopped working ~5 days ago. There are no errors in the log so I might just have to re-sync the webhook or re-make the integration. 

It looks like re-syncing is all that was needed, it is building docs on pull requests again! :tada: 

![image](https://user-images.githubusercontent.com/11765982/186746189-7da6103f-0710-49e3-beab-535ca39ace40.png)
