### ISSUE TITLE
Bug in test_relative_setup_charge_change()

### ISSUE THREAD

**Issue by zhang-ivy** [choderalab/perses#1096]
[This line ](https://github.com/choderalab/perses/blob/main/perses/tests/test_relative_setup.py#L313) should contain this filepath
`"perses", "data/bace-example/Bace_protein.pdb"`

**Comment by zhang-ivy** [comment]
The test does not fail because only solvent and vacuum phases are run, so the `receptor_pdb` is actually unused.

**Comment by ijpulidos** [comment]
Good catch, thanks! Yeah, and `pkg_resources.resource_filename` doesn't fail as long as the module exist.
