### ISSUE TITLE
Extend TopologyProposal with convenience methods to retrieve atoms being deleted and atoms being created

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#11]
Perhaps we should make `TopologyProposal` a real class, since we could then define convenience methods that use `new_to_old_atom_map` along with `old_topology` and `new_topology` to return the lists of atoms being deleted or created.  This would be helpful for creating alchemically modified systems without having to recompute these lists.

**Comment by pgrinaway** [comment]
I think this is a good idea. It might also make the proposal classes cleaner.

**Comment by jchodera** [comment]
Do you want to take a stab at this?

**Comment by pgrinaway** [comment]
Yep! Sounds good!

**Comment by pgrinaway** [comment]
I'll make this the next PR after fixing the test failures.

**Comment by pgrinaway** [comment]
Based on #22 and the discussion there, I've implemented a full class version of the `TopologyProposal`. I can open a PR now, though it will require a bit of a refactor to make the tests work (since the constructor is now different).

**Comment by jchodera** [comment]
Go for it!

**Comment by pgrinaway** [comment]
Implemented in #27
