### ISSUE TITLE
Add analysis script variant to integrate and weight protonation/tautomer states

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#1107]
We should add a variant of the `perses/examples/new-cli/` analysis script that zips up the appropriate protonation/tautomer microstates that have been expanded with state penalties.

**Comment by ijpulidos** [comment]
We should have the script in `examples`. Check and close.

**Comment by ijpulidos** [comment]
Related to https://github.com/choderalab/perses/issues/1136

**Comment by jchodera** [comment]
We have a an example script [here](https://github.com/choderalab/perses/blob/main/examples/moonshot-mainseries/perses/analyze-benchmark-pKa.py), but #1136 will supercede this with a more integrated analysis tool.
