### ISSUE TITLE
Avoid using `settattr()` in lambda protocols

### ISSUE THREAD

**Issue by zhang-ivy** [choderalab/perses#1109]
We want to replace all `setattr()` calls in `lambda_protocol.py`. Here is one example:

Instead of `setattr()` [here](https://github.com/choderalab/perses/blob/2ff4a7bb631a93716b64f2bd11dc68a2864402cd/perses/annihilation/lambda_protocol.py#L483), we want to call `getattr()` and then `__set__()`. Otherwise, we may be replacing the function with a float instead of setting the value. 

Note that John found this potential problem in my meeting with him today.

**Comment by ijpulidos** [comment]
We want to use the setters and getters in https://github.com/choderalab/openmmtools/blob/2e64980d86cf087f69e282927eebf2b41b73a3ea/openmmtools/states.py#L3435 that are ultimately being used by the `LambdaParameters`

**Comment by ijpulidos** [comment]
I was checking this and realized that it should be okay. 

When you have this composition as we have it in the `RESTCapableRelativeAlchemicalState`, such that all the parameters/attributes are instances of `_LambdaParameter` [here](https://github.com/choderalab/perses/blob/2ff4a7bb631a93716b64f2bd11dc68a2864402cd/perses/annihilation/lambda_protocol.py#L440-L461]), then the underlying `__set__()` should be called from `openmmtools.states.GlobalParameter`.

And example of this is as follows:
```python
In [1]: class GlobalParameter(object):
   ...:     def __set__(self, instance, value):
   ...:         print("set was executed")
   ...: 
   ...: class AlchemicalState(GlobalParameter):
   ...:     some_parameter = GlobalParameter()
   ...: 
   ...:     def set_method_test(self):
   ...:         setattr(self, "some_parameter", "some_value")
   ...: 
   ...: alchemical_state = AlchemicalState()
   ...: alchemical_state.set_method_test()
set was executed
```
I honestly find it a bit confusing but it should be okay. With regards of finding a better way to do this or trying to call the `__set__()` method directly, it may be possible, I just cannot think of a way of doing this programmatically [inside the loop in `set_alchemical_parameters`](https://github.com/choderalab/perses/blob/2ff4a7bb631a93716b64f2bd11dc68a2864402cd/perses/annihilation/lambda_protocol.py#L474-L483).

If you can think of a better way of doing this please let me know.

**Comment by ijpulidos** [comment]
Btw, this is what's called a descriptor. More info in https://docs.python.org/3/howto/descriptor.html and http://martyalchin.com/2007/nov/23/python-descriptors-part-1-of-2/
