### ISSUE TITLE
Remove outdated devtools/conda-recipe/

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#1126]
The [`devtools/conda-recipe/`](https://github.com/choderalab/perses/tree/main/devtools/conda-recipe) directory is highly outdated. We should remove it.

**Comment by ijpulidos** [comment]
Yes, I agree. The recipe for  building the conda-forge packages lives in https://github.com/conda-forge/perses-feedstock now, as far as I know there is no reason to have this here.
