### ISSUE TITLE
Test Newest OpenMM Release Candidate  

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/perses#1147]
- [ ] Add to CI
- [ ] Run all local test w/GPU

**Comment by ijpulidos** [comment]
As far as I remember I think this can be marked as completed/closed. We did not find any new issues with running the tests locally on GPU other than the ones mentioned in #1124 

@mikemhenry maybe just a quick summary of your findings here to be able to close it?

**Comment by ijpulidos** [comment]
@mikemhenry just a reminder to update your findings here, if any.
