### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#115]
This is just a reminder for me to add a docs skeleton.

**Comment by jchodera** [comment]
http://readme.io/ might be an alternative

**Comment by pgrinaway** [comment]
Docs are failing; we should figure out why and remedy this.

**Comment by jchodera** [comment]
Docs aren't actually failing, but the badge seems to be broken:
![image](https://user-images.githubusercontent.com/3656088/29983888-d371edde-8f25-11e7-9bbc-7d181617d18b.png)

**Comment by pgrinaway** [comment]
Oh... ok, I'll fix the badge then

**Comment by pgrinaway** [comment]
This badge was just not synced.
