### ISSUE TITLE
Update docstring example for PointMutationExecutor

### ISSUE THREAD

**Issue by zhang-ivy** [choderalab/perses#1168]
Just noticed that the docstring for the PointMutationExecutor contains `reassign_velocities=True`. It should contain `reassign_velocities=False`.

https://github.com/choderalab/perses/blob/e1db2061eec75cceba9f29fa3e3d0a26a8156ed2/perses/app/relative_point_mutation_setup.py#L89-L97

**Comment by ijpulidos** [comment]
Thanks for reporting.
