### ISSUE TITLE
Make sure logging messages stream to stdout 

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#1175]
By default the `StreamHandler` in `logging` outputs to `sys.stderr`, we should make sure that this gets streamed to `sys.stdout` instead, such that users get access to the logged information more easily.

Related to https://github.com/choderalab/openmmtools/pull/673

**Comment by mikemhenry** [comment]
I don't think we should change where we stream the logging messages, users can tell their submission system to combine the output into a single file if they want, or they can use the standard posix output direction ie `perses-cli --yaml my.yaml 2>&1`

**Comment by ijpulidos** [comment]
@mikemhenry I agree, I think this should be handled by the users at the higher level. Closing. Feel free to reopen if there's something else to be discussed here.
