### ISSUE TITLE
[CLI] no entry point for non-tip3p solvation model

### ISSUE THREAD

**Issue by IAlibay** [choderalab/perses#1192]
As far as I can tell, there's no way to pass an entry that isn't 'tip3p' to `_solvate_system` in `perses.app.relative_setup.py`:

https://github.com/choderalab/perses/blob/8e3e423a388553fadd9d3f9c0342ffe3e3b4e4c0/perses/app/relative_setup.py#L815

This leads to a template matching `ValueError` when trying to use tip4pew (i.e. `amber/tip4pew_standard.xml`).

**Comment by ijpulidos** [comment]
It should be easy to pass this from the YAML file and pass this when we solvate the system. Maybe some `solvate_water_model` option in this file.

**Comment by ijpulidos** [comment]
The way to do this is adding yet another keyword argument to the `RelativeFEPSetup` object. Which we already know it's not an ideal way to do this, but I thin it's easy enough for us to move forward with this and to keep in mind in the future that this is something we want to let users choose once we do the API refactor in the 0.11 release.
