### ISSUE TITLE
Make `offline-freq` be the same as `checkpoint_interval` by default

### ISSUE THREAD

**Issue by jthorton** [choderalab/perses#1220]
If not specified in the template file it might be good to make `offline-freq` default to being the same as the `checkpoint_interval` instead of [10](https://github.com/choderalab/perses/blob/ae5580173e321cc85014a2a780080b9b546f18bf/perses/app/setup_relative_calculation.py#L151-L153) as this will cause an error in openmmtools if `checkpoint_interval`  is larger than 10 which most of the time it is.

**Comment by ijpulidos** [comment]
closing via #1227 (for some reason it wasn't closed automatically when the PR was merged).
