### ISSUE TITLE
PointMutationProposalEngine allows terminal residues to be made into non-terminal residues

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#134]
Just saw this flash by:
```
Proposed transformation: LYS-GLU-LYS-ARG-VAL-LYS-GLU-LEU-GLU-LEU-LEU-LEU-MET-SER-THR-GLU-ASN-GLU-LEU-LYS-GLY-GLN-GLN-ALA-LEU => LYS-GLU-LYS-ARG-VAL-LYS-GLU-LEU-GLU-LEU-LEU-LEU-MET-SER-THR-GLU-ASN-GLU-LEU-LYS-GLY-GLN-GLN-ALA-CLEU
```
Here, it proposes changing `LEU` into `CLEU`.

**Comment by juliebehr** [comment]
What exactly is the issue here? I'm not sure why it would be able to turn ```LEU``` into itself, but isn't it terminal?

**Comment by jchodera** [comment]
I think I see the reason.  I was explicitly constructing a list of `allowed_mutations` that allowed this to happen.  Sorry!
