### ISSUE TITLE
Does SmallMoleculeSetProposalEngine assume molecule to be modified is at end of topology?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#145]
Looking over `SmallMoleculeSetProposalEngine.propose()`, it seems to assume that the small molecule is always at the *end* of the topology.  Is there a way we can avoid this assumption?

**Comment by pgrinaway** [comment]
I don't see that. `SmallMoleculeSetProposalEngine.propose()` always finds the small molecule via its residue name (not index) and converts it to canonical isomeric smiles. In the the atom mapping, it does put the small molecule at the end of the topology immediately before creating the atom map, but I don't see what difference this makes. Nothing should interrupt `propose` and change the indices of the small molecule before `propose` returns.

**Comment by jchodera** [comment]
Ah, OK!  My bad for misreading this.
