### ISSUE TITLE
Add perses-dev builds for multiple platforms

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#149]
Just a reminder for myself.

**Comment by pgrinaway** [comment]
What's the timeframe for this?

**Comment by jchodera** [comment]
Oh, I can do that now.

**Comment by jchodera** [comment]
I'm deprecating the `perses-dev` packages and going for the multiplatform nightlies:
https://github.com/omnia-md/conda-dev-recipes/pull/39

**Comment by jchodera** [comment]
Not sure what's going on here:
https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/161515672#L506

**Comment by jchodera** [comment]
@pgrinaway : Looks like I won't be able to build a `perses` `dev` conda package while you still have `numba` pinned to `0.27.0` because there are no `numba` packages for `numpy` 1.11:
```
...Can't build /io/perses due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - numba ==0.27.0 -> numpy 1.11*
  - numba ==0.27.0 -> python 2.7*|3.4*
  - python 3.5*
```
More info [here](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/162299149).

**Comment by jchodera** [comment]
Done in https://github.com/omnia-md/conda-dev-recipes/pull/39

**Comment by jchodera** [comment]
I've deleted the old `perses-dev` package to avoid confusion.

New `perses` package will appear in the `dev` channel [here](https://anaconda.org/omnia/perses/files), and will be installable via
```bash
conda install -c https://conda.anaconda.org/omnia/label/dev perses
```

**Comment by jchodera** [comment]
Something is wrong with `conda-dev-build` now:
https://github.com/omnia-md/conda-dev-recipes/issues/44

**Comment by jchodera** [comment]
Fixed.

**Comment by jchodera** [comment]
[Hooray!](https://anaconda.org/omnia/perses/files)
