### ISSUE TITLE
Travis tests taking > 18 hours

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#151]
Not sure if this is some weird artifact, but the travis tests seem to be taking [extremely long](https://travis-ci.org/choderalab/perses/builds/111345497)  ( >18 hours).

**Comment by jchodera** [comment]
Whoops.  Will fix after PR is merged.  I accidentally changed the default number of iterations without changing the tests.

**Comment by jchodera** [comment]
I've split up the tests further in #156 and reduced iterations in #153
