### ISSUE TITLE
Geometry engine proposal time

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#161]
Do you have a good feeling for where the majority of time is spent in the geometry proposal?  I wonder if it's something that can be easily sped up with a little optimization.

**Comment by pgrinaway** [comment]
Yeah, it's the coordinate conversion.

**Comment by pgrinaway** [comment]
More specifically, it's the coordinate conversion when it's performing a rotation about a torsion. I've been meaning to replace that step with a quaternion multiplication, but it's been on the back burner. I can tackle this sooner, though. I know it's ridiculously slow.

**Comment by jchodera** [comment]
Would be great to speed this up, since I think this is really rate limiting in testing.

**Comment by pgrinaway** [comment]
Ok, I've thought a bit about the `GeometryEngine` proposal time stuff, and I've come up with a few plans for tackling this:

* Try to do torsion scans in `OpenEye`, or, barring that, perhaps figure something out with OpenMM. If neither of those are straightforward, I can write the coordinate conversion stuff in Cython.

* For the modified `System` that the `GeometryEngine` uses, make sure to avoid creating any force terms between atoms that are not changing. This might make including the `NonbondedForce` as I mentioned in #159 cheap enough that it's worthwhile.

**Comment by jchodera** [comment]
> Try to do torsion scans in OpenEye, or, barring that, perhaps figure something out with OpenMM. If neither of those are straightforward, I can write the coordinate conversion stuff in Cython.

Do you mean compute energies as a function of torsion angle using OpenEye (sybki?), or just use OpenEye tools to convert between Cartesian and internal coordinates?

> For the modified System that the GeometryEngine uses, make sure to avoid creating any force terms between atoms that are not changing. This might make including the NonbondedForce as I mentioned in #159 cheap enough that it's worthwhile.

Do we think the energy computation time is really responsible here?  You might try just integrating N steps of `VerletIntegrator` dynamics and timing this to see if the energy computation is the rate-limiting step here.

**Comment by jchodera** [comment]
If OpenMM energy computations are slow, we should be able to find a way to speed this up on the GPU. Might be worth posting an issue in the OpenMM issue tracker to get ideas from @peastman.

**Comment by pgrinaway** [comment]
>Do you mean compute energies as a function of torsion angle using OpenEye (sybki?), or just use OpenEye tools to convert between Cartesian and internal coordinates?

Sorry, I probably misspoke here! I meant just calculating the coordinates. I'm not sure how good the overlap between MMFF or whatever szybki uses and GAFF/whatever are going to be, so it seems like it could be an extra complication. It's really just the coordinate conversion that is painfully slow.

>Do we think the energy computation time is really responsible here? You might try just integrating N steps of VerletIntegrator dynamics and timing this to see if the energy computation is the rate-limiting step here.

Probably not, I need to re-profile to double check though. If we add in the nonbonded stuff I assume it would get pretty slow.

**Comment by pgrinaway** [comment]
Closing for now to avoid an eternal issue.
