### ISSUE TITLE
Ring closure fix

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#163]
The simplest way to add a fix for increasing the probability of successful ring closures is probably to add a single-periodicity torsion term during the geometry proposal phase.  If only added at this stage, the bias is automatically corrected for by the geometry engine.

To determine which bonds should have torsions added, I think we can take advantage of the OpenEye tools.  We can:
* Build a the appropriate stereochemistry molecule in some geometry using `oeomega`
* Use [`OEIsRotor()`](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemClasses/OEIsRotor.html) to determine which bonds need torsions applied. If `True`, we don't need a torsion; if `False`, we need one.
* Measure the torsion phase from the geometry generated by `oeomega`
* Add a torsion term with some arbitrary barrier height of a few `kT`

**Comment by pgrinaway** [comment]
Resolved in #167
