### ISSUE TITLE
Optimizing MCSS atom mapping

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#172]
Since the MCSS atom mapping is so critical to success of the geometry proposal, we should optimize this at some point.

There are [many different modifiers](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEExprOpts.html#OEChem::OEExprOpts::SymmetryClass) that can be used to fine-tune the atom and bond matching. We could even go further and use set string or integer atom and bond types that are used in the matching, which could allow us to match based on forcefield parameters---as [I did in `mmtools`](https://github.com/choderalab/mmtools/blob/master/relativetools/setup-relative-fep.py#L513-L516), though there are issues with how GAFF treats aromatic atom types---or create our own properties based on, say, the ring size (e.g. assign a `6` to atoms in 6-membered rings, or `5` to atoms in 5-membered rings).

There is [a recipe in the Python OEChem cookbook](https://docs.eyesopen.com/toolkits/cookbook/python/depiction/multi-matches.html) for depicting substructure matches that might help us fine-tune these by looking at all kinase inhibitor matches and amino acid matches.

This isn't critical right now, but something that will ultimately be responsible for the success of this method.

**Comment by jchodera** [comment]
[This visualization recipe](https://docs.eyesopen.com/toolkits/cookbook/python/cheminfo/core.html) is also pretty cool.

**Comment by jchodera** [comment]
We might also consider the [MCSS scheme](https://github.com/nividic/Lomap/blob/master/mcs.py) used in [LOMAP2](https://github.com/nividic/Lomap), though it seems to use RDKit rather than OpenEye tools.

**Comment by hannahbrucemacdonald** [comment]
I think we've sort of come to the conclusion that there is no one single atom scheme that works for all transformations. I think the `AtomMapper` and associated example is a good compromise to allow for easy testing of these things
