### ISSUE TITLE
Fix geometry tests

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#189]
As noted in #188 , there are some additional test failures on Jenkins. One of these is due to a naive `GeometryEngine` test that tries to convert all T4 inhibitors to all others. It shouldn't actually be capable of that, so I'm going to fix that test.

**Comment by jchodera** [comment]
Thanks!

**Comment by pgrinaway** [comment]
Closing because the Jenkins issue (#188 ) was also closed.
