### ISSUE TITLE
Improve readability of protein chemical_state_keys

### ISSUE THREAD

**Issue by juliebehr** [choderalab/perses#190]
This isn't quite as straightforward as we were thinking, because I don't necessarily know what WT is.  It would be trivial, for instance, to make a ```new_chemical_state_key``` reflecting the changes made within that proposal with respect to the old sequence, but more difficult / less obvious to know what modifications have been made for ```old_chemical_state_key```.

**Comment by jchodera** [comment]
You can change the API of `PointMutationEngine` to take whatever you want!  If it would be useful to cache a copy of the wild-type sequence, you can have the user pass in something (maybe a wild-type `Topology` object) in the constructor and extract the sequence and store it!

But `PointMutationEngine` only permits a fixed number of mutations *away* from the wild-type sequence, so I'm a little confused as to how you don't already have to track this information.

**Comment by jchodera** [comment]
Might be useful to also improve the readability of small molecule chemical state keys if the molecules have a common name (e.g. `imatinib`) that can be provided along with the SMILES string.

Maybe this is a use of our `metadata` field?

**Comment by juliebehr** [comment]
Currently planning on making the ```chemical_state_key``` in a point mutation system a list of strings describing the mutant -- implementing now.

**Comment by jchodera** [comment]
+1!

**Comment by pgrinaway** [comment]
Ok, I think this is done
