### ISSUE TITLE
conda installation of perses-dev destroys CUDA support in openmm?

### ISSUE THREAD

**Issue by sstolzenberg** [choderalab/perses#191]
Hi there (I hope this is OK to post user/installation issues here?),

it is not possible to install perses with openmm/cuda support, or is there something I am missing?:

I am using a regular 64Bit Linux platform with miniconda.

If scenario (a), I use
conda create --name simpletest python openmm numpy
...
Then in python, this command works:
import simtk.openmm as openmm
print openmm.Platform.getPlatformByName("CUDA")

However, if scenario (b), instead I use
conda create --name simpletest python openmm numpy perses-dev
...
Then this command does not work anymore:
print openmm.Platform.getPlatformByName("CUDA")

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print openmm.Platform.getPlatformByName("CUDA")
  File "/home/sstolzen/sw/miniconda/envs/simpletest/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 8485, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
Exception: There is no registered Platform called "CUDA"

I am attaching the "conda list" outputs for each scenario:
(a) [without_perses.txt](https://github.com/choderalab/perses/files/200523/without_perses.txt)
(b) [with_perses.txt](https://github.com/choderalab/perses/files/200522/with_perses.txt)

Any help is much appreciated,
Best,
Sebastian

**Comment by jchodera** [comment]
What CUDA version do you have installed? Right now, perses-dev requires openmm-dev, which is build against CUDA 7.5. If you are on CUDA 7.0 (which works for the normal openmm package) you will need to upgrade.

Note that perses-dev is very much a work in progress, both from a code perspective and a science perspective! The tests are still not quite all passing yet, and then we need to make it efficient enough to be useful (the actual science!).

yank is very close to a stable release if you just want to compute some binding free energies.

**Comment by sstolzenberg** [comment]
Hi @jchodera,

thanks a lot, this may be it - will get back to you about this.

Great to hear about the yank release! My current goal is to play around with NCMC (for which I understand I need perses) and then compare the results with the ones obtained with yank.

- Sebastian

**Comment by jchodera** [comment]
Can you give us any further details? Do you need relative or absolute free
energy calculations? For small molecule or peptide binding?

Perses is highly specialized, so may not be what you want here.

**Comment by sstolzenberg** [comment]
Hi @jchodera ,

(i)
Relative free binding energies of ions to a protein within the NCMC framework would be a great start.
Eventually, we are thinking about relative free energies of mutations, also performed within the NCMC framework.
-> done with perses?

(ii)
Of course, whatever free energies we obtain with NCMC will have to be validated against existing (non-NCMC) free energy methods.
-> done with yank?

Thanks again,
Sebastian

**Comment by jchodera** [comment]
#221 switches to using the `openmm` 7.0.1 release, so the oriignal issue should no longer happen.
