### ISSUE TITLE
constructor to allow for easy calculation set up 

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/perses#199]
Just throwing this up here re: a conversation with @pgrinaway 

It would be nice to have some type of flexible constructor that would take user options and allow us to set up the calculations more easily than editing a Class! 

That being said, a template Class in the `examples` folder would certainly be fine for now while we work on getting the whole thing to run!

**Comment by jchodera** [comment]
I thought we had discussed the proposed API for helper classes that do exactly what you suggest, but I can't find the issue or PR. @pgrinaway: Do you remember where this is?

**Comment by pgrinaway** [comment]
Already discussed in #61
