### ISSUE TITLE
Disable OpenEye tests in PRs 

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#21]
Otherwise all PRs will have tests fail.

**Comment by pgrinaway** [comment]
Ok. I'll have to pre-generate some input files then (at the moment, we're generating example molecules from SMILES).

**Comment by jchodera** [comment]
Or we can just skip tests that require OpenEye tools in PRs.

**Comment by pgrinaway** [comment]
Ok.

**Comment by jchodera** [comment]
Doesn't look like there is a better solution at the moment unless we use
branches of the main repo.

I do like your idea of generating files though. We could in principle cache
these to disk as a form of memoization, and just store some files for the
tests that would not need to be regenerated.

**Comment by pgrinaway** [comment]
Yeah, I'm just concerned that we'd be unable to test important parts of, for instance, the `GeometryEngine` without a way to construct small molecules.

**Comment by jchodera** [comment]
Agreed.

What if we worked on branches of the main repo instead?

**Comment by jchodera** [comment]
Working from branches of the main repo seems to work OK for this.
