### ISSUE TITLE
Small Molecule Proposal Engine naming issues

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#215]
In #214 , we've discovered an issue with the molecule naming, where the name of the residue is set independently from the constructor argument, even though the object relies on the name in the constructor argument. I will change [this](https://github.com/choderalab/perses/blob/master/perses/rjmc/topology_proposal.py#L1341) to use the name specified in the constructor and avoid relying on default behavior in `openmoltools`.

**Comment by jchodera** [comment]
I'll incorporate the fix into #214.

**Comment by jchodera** [comment]
This was fixed in #214.
