### ISSUE TITLE
Syntax Error during install for python 3

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/perses#216]
I was just updating my PERSES installation on the cluster for Python 3 and got a syntax error: 

```
Extracting perses-0.1-py3.5.egg to /cbio/jclab/home/albaness/miniconda3/lib/python3.5/site-packages
  File "/cbio/jclab/home/albaness/miniconda3/lib/python3.5/site-packages/perses-0.1-py3.5.egg/perses/data/constant-pH/imidazole/generate-protomers-from-smiles.py", line 145
    print "Generating molecule {}".format(name)
                                 ^
SyntaxError: invalid syntax
```

It looks like it's a problem with changes to `print` in python 3

**Comment by steven-albanese** [comment]
to clarify, this was when I was installing using `python setup.py install`

**Comment by juliebehr** [comment]
Fixing right now!

**Comment by jchodera** [comment]
This probably means some py3x travis tests were disabled too.

**Comment by juliebehr** [comment]
Addressed by https://github.com/choderalab/perses/pull/217
