### ISSUE TITLE
NaNs encountered with GHMC NCMC

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#222]
I'm still seeing `nan`s with the current GHMC NCMC implementation, which should never happen. For a simple `benzene <--> napthalene` transformation, I encountered this:
```
................................................................................
Updating chemical state with ncmc-geometry-ncmc scheme...
Proposing new topology...
Proposed transformation: c1ccc(cc1)N => CC(=O)CSc1cccs1
Generating new system...
Performing NCMC annihilation
Geometry engine proposal...
proposal took 1.393 s
Geometry engine logP_reverse calculation...
calculation took 1.449 s
Performing NCMC insertion
Traceback (most recent call last):
  File "perses/tests/testsystems.py", line 2106, in <module>
    run_fused_rings()
  File "perses/tests/testsystems.py", line 2097, in run_fused_rings
    testsystem.designer.run(niterations=5)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 1181, in run
    self.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 1163, in update
    self.update_samplers()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 1124, in update_samplers
    sampler.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 1032, in update
    self.update_sampler()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 996, in update_sampler
    self.sampler.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 863, in update
    self.update_state()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/samplers/samplers.py", line 789, in update_state
    [ncmc_new_positions, ncmc_introduction_logp, potential_insert] = self.ncmc_engine.integrate(topology_proposal, geometry_new_positions, direction='insert', iteration=self.iteration)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses/annihilation/ncmc_switching.py", line 419, in integrate
    raise NaNException(msg)
perses.annihilation.ncmc_switching.NaNException: Particle coordinate is nan during NCMC integration while using integrator_type 'GHMC'
This should NEVER HAPPEN with GHMC!
```
I'm not quite sure how this can happen unless [something is wrong with this logic](https://github.com/choderalab/perses/blob/master/perses/annihilation/ncmc_switching.py#L578-L582).  There is also a [`select`](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomIntegrator.html#simtk.openmm.openmm.CustomIntegrator) alternative to `beginIfBlock`s, but the issue may lie with whether `nan` energies really result in [this line](https://github.com/choderalab/perses/blob/master/perses/annihilation/ncmc_switching.py#L578) giving `accept = 1`.

**Comment by jchodera** [comment]
As far as I can tell, this code for `NCMCGHMCAlchemicalIntegrator` does *not* give `NaN`s:
```
            # All steps
            self.beginIfBlock('step < nsteps')
            self.addComputeGlobal("Eold", "energy")
            self.addAlchemicalPerturbationStep()
            self.addComputeGlobal("Enew", "energy")
            self.addComputeGlobal("total_work", "total_work + (Enew-Eold)")
            self.addGHMCStep()
            self.addComputeGlobal('step', 'step+1')
            self.endBlock()
```
while this code *does* give `NaN`s:
```python
            # Initial step only
            self.beginIfBlock('step = 0')
            self.addGHMCStep()
            self.endBlock()

            # All steps
            self.beginIfBlock('step < nsteps')
            self.addComputeGlobal("Eold", "energy")
            self.addAlchemicalPerturbationStep()
            self.addComputeGlobal("Enew", "energy")
            self.addComputeGlobal("total_work", "total_work + (Enew-Eold)")
            self.addGHMCStep()
            self.addComputeGlobal('step', 'step+1')
            self.endBlock()
```
Somehow, adding that GHMC on the initial step causes the `NaN`. I'm not sure why.

Options seem to be:
* Debug what is going on with `CustomIntegrator` and submit an OpenMM issue
* Work around this by adding another `CustomIntegrator` that is just responsible for that first step, and switching between them with a `CompoundIntegrator` (which makes things a bit more complicated)
* Use the same approach in the NCMC paper to make the protocol symmetric by randomly choosing the order of perturbation and propagation steps every time an `NCMCGHMCAlchemicalIntegrator` is created, rather than trying to add that initial GHMC step to make the protocol symmetric.
* Make the protocol symmetric by perturbing first instead of propagating first.

Any suggestions @pgrinaway @juliebehr?

**Comment by pgrinaway** [comment]
I am unable to reproduce this error. What platform are you using?

**Comment by jchodera** [comment]
After

pip install --upgrade .

I ran

python perses/tests/testsystems.py

And see the nan appear stochastically sometime in the first 100 perses
iterations for benzene-naphthalene with 10 NCMC switching steps.

This appears to happen on both CPU (on osx) and CUDA (on the cluster).

**Comment by pgrinaway** [comment]
Is this still a problem? I haven't seen it.

**Comment by jchodera** [comment]
That's because I removed the first velocity Verlet step from the GHMCIntegrator. If we added it back (which is necessary for correctness) it still gives NaNs. We still need to get to the bottom of that issue, but I haven't yet been able to produce a minimal example that demonstrates the issue.

**Comment by pgrinaway** [comment]
Ah, ok.

**Comment by jchodera** [comment]
Addressed in https://github.com/choderalab/perses/pull/267
