### ISSUE TITLE
Make sure we are handling NPT correctly with MonteCarloBarostat

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#225]
It appears that we aren't correctly treating solvated systems by adding a `MonteCarloBarostat` to them. While we _don't_ want to include volume change in NCMC (though this might be OK when GHMC is used), we definitely want to add a barostat for solvated systems, since otherwise the default water densities can be awful, making NCMC much more difficult than it should be.

**Comment by jchodera** [comment]
We have to remember to switch off the barostat during NCMC

**Comment by jchodera** [comment]
It looks like we have a few options here:
* Augment `SystemGenerator` to add a `MonteCarloBarostat` to NPT systems. This will require passing a `ThermodynamicState` to the `SystemGenerator`, and would mean that the generated system is specific to a single temperature and pressure. We would need to remember to disable the barostat in other parts of the code (like NCMC).
* Only use a barostat in `MCMCSampler`, where we add a barostat, run some simulation, and then remove the barostat. This keeps us from having to worry about disabling the barostat elsewhere.

Would be useful to discuss best approach.

**Comment by pgrinaway** [comment]
Resolved by previous PR.
