### ISSUE TITLE
Complete sterics implementation

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#229]
Temporarily disabling in #228 but I think this will be important in getting larger molecules to work.

**Comment by jchodera** [comment]
Are you seeing rejections because of geometries that include steric clashes?

**Comment by pgrinaway** [comment]
A couple times I've seen molecules self-intersect, which I assume would be solved by including sterics. On the other hand, I don't have an empirical number as to how often that happens, and maybe we can live with its occasional occurrence. I mostly raised this to not forget about the sterics implementation, but if you don't think it's necessary feel free to remove the tag.

**Comment by jchodera** [comment]
Nope, just wondering if you had any data on this that was relevant!

**Comment by pgrinaway** [comment]
Not yet, but I definitely should do that.

**Comment by jchodera** [comment]
Moving forward, once we are sure we have the acceptance criteria correct
(how do we test that?), we should think about writing harnesses to gather
the acceptance rate statistics we need. The statistics can all be stored in
the NetCDF file, so we really just need the harness that runs multiple
instances with different parameters in parallel.

**Comment by pgrinaway** [comment]
I think this was resolved in #239
