### ISSUE TITLE
Manuscript / notes on theory

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#23]
Perhaps this is a good point to pull the [overleaf document](https://www.overleaf.com/read/tmtbwbksjpwn) with theory notes into this repo?

**Comment by pgrinaway** [comment]
+1, sounds like a good plan

**Comment by pgrinaway** [comment]
How about we put these into a separate (private?) repo?

**Comment by jchodera** [comment]
Private isn't needed. Not sure if a separate repo needed either unless we want to store large datasets/trajectories to go into the manuscript in the github repo for the manuscript.

**Comment by pgrinaway** [comment]
It's in the repo now.
