### ISSUE TITLE
Add intra-ring angle terms to increase ring fusion rate

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#242]
From looking at the creation of rings by the current code using the [atom-by-atom geometry PDB files](https://github.com/choderalab/perses/blob/master/perses/tests/testsystems.py#L152-L154), it's clear that a major source of poor acceptance for ring creation is that the broad angular distributions for placing each atom in the ring result in rings that are somewhat misshapen, with larger bond energies to close the ring when the final atom is placed. Standard forcefields do not have large angle restraints on rings because they don't need them---the balance of bonds, angles, and torsions that close the ring do just fine. But to increase our acceptance rates, we will benefit from adding tighter angular restraints during the proposal phase that are set to reference angles measured from omega geometries or computed from ideal ring angles, much as we do for ring torsions right now.

**Comment by jchodera** [comment]
Here's an example of a resulting misshapen ring:

![misshapen-ring](https://cloud.githubusercontent.com/assets/3656088/18231998/871d2bb4-7294-11e6-82ad-b6fdded4bbb6.png)

The selected atom was the last one placed, and ends up "off" because of the weak angular restraints.

**Comment by jchodera** [comment]
Note that the angle terms may not use the ideal ring geometry reference angles---hence why we might have to measure or calculate them.

**Comment by pgrinaway** [comment]
Taking care of this now in the `geometry-angles` branch.

**Comment by pgrinaway** [comment]
Resolved in #247
