### ISSUE TITLE
PointMutationEngine insists on self-proposals

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#244]
I'm not sure if I'm just misreading the API or there is a bug, but when I do:

```python
        allowed_mutations = [[('2','PHE')]]
        proposal_metadata = {"always_change":True}
        for environment in environments:
            proposal_engines[environment] = PointMutationEngine(topologies[environment],system_generators[environment], chain_id, proposal_metadata=proposal_metadata, allowed_mutations=allowed_mutations)
```

I still get things like this:
```
Updating chemical state with ncmc-geometry-ncmc scheme...
Proposing new topology...
Proposed transformation: ALA2PHE => ALA2PHE
```

**Comment by pgrinaway** [comment]
Update: I think this is a bug where any proposal from a mutation to wildtype automatically becomes a self-proposal. That is, once we leave wildtype, we can never propose to return.

**Comment by juliebehr** [comment]
Addressed in https://github.com/choderalab/perses/pull/247 for cases with `allowed_mutations`.  Not exactly a bug, per se, in cases without, but probably doesn't have the intended behavior (won't go back to WT).  Changing now and will open a new PR.

**Comment by juliebehr** [comment]
Addressed in https://github.com/choderalab/perses/pull/250 for other cases.

**Comment by pgrinaway** [comment]
Ok, Closing.
