### ISSUE TITLE
Storage layer test failures

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#249]
I'm seeing failures like [this](https://travis-ci.org/choderalab/perses/jobs/161324417#L859) relating to the storage layer. @jchodera suggested in #247 that this might be caused by some pickling issues.

**Comment by bas-rustenburg** [comment]
https://github.com/swig/swig/blob/master/CHANGES#L281   This seems like a related fix in swig 3.0.8, openmm currently uses 3.0.7.

**Comment by bas-rustenburg** [comment]
I would suggest to stop using generators here until openmm has a new release that updates the swig function.
