### ISSUE TITLE
Fix test failure due to missing pymol import

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#262]
There's a doctest failure due to one of the movie-making scripts that I need to fix:

```
Doctest: perses.samplers.thermodynamics.volume ... ok ([32m0.1400s[0m)
Failure: ImportError (No module named pymol) ... ERROR
Test analysis tools. ... ok ([31m500.9463s[0m)
```

https://jenkins.choderalab.org/job/test-perses-linux/246/console

**Comment by pgrinaway** [comment]
Thanks for reporting. Do you want to tackle this one?

Also, I thought we had put the movie making scripts in another repo?

**Comment by jchodera** [comment]
I'll tackle this!

I ended up having to put it here to make some critical slides for a talk. I didn't have time to set up a separate repo at the time. Will do so when I tackle this issue.

**Comment by pgrinaway** [comment]
Ok, thanks. Certainly no rush.

**Comment by pgrinaway** [comment]
I don't think this is currently a problem.
