### ISSUE TITLE
Move SystemGenerator to its own file?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#268]
`SystemGenerator` is currently in `perses.rjmc.topology_proposal`. 

Should we move it to its own file in a separate location?

**Comment by pgrinaway** [comment]
I'm not really opposed to it, but what's the motivation? It's really tiny.

**Comment by pgrinaway** [comment]
Sounds like it might not be a bad plan, if only to make sure modules only contain code that has the same functionality.

**Comment by jchodera** [comment]
`SystemGenerator` has been moved to [`openmmforcefields.generators`](https://github.com/openmm/openmmforcefields#using-systemgenerator-to-automate-the-use-of-amber-force-fields-with-gaff-for-small-molecule-parameterization).
