### ISSUE TITLE
When hybrid-tests branch is merged, include new test systems in `test_samplers.py`

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#279]
When the `hybrid-tests` branch is merged, we need to remember to include the new test systems by name in `perses/tests/test_samplers.py`.

**Comment by pgrinaway** [comment]
What are the new test systems? When the hybrid branch is merged, don't we simply want to include the T4 test systems?

**Comment by jchodera** [comment]
https://github.com/choderalab/perses/blob/hybrid-tests/perses/tests/testsystems.py#L2096-L2217

**Comment by jchodera** [comment]
We want to (1) include tests for systems that will appear in the paper in the travis tests, and (2) put any other tests that have been added into the full suite of tests that will run locally so we can eventually debug them.

**Comment by pgrinaway** [comment]
Oh, right, thanks.

**Comment by pgrinaway** [comment]
This branch is defunct.
