### ISSUE TITLE
SAMS sampler does not implement algorithm in paper

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#295]
As I was running the tractable valence tests, I needed to have a look at the `SAMSSampler`, and I noticed a few things. I may have missed some of these, so if they are there, please let me know.

* The code doesn't implement the subtraction step as written in the paper
     * The first element (presumably arbitrary) of the log weight array must be zero, since it's a log ratio of that distribution's normalizing constant to itself.

* If `second_stage_start` isn't set, the code never enters the diminishing gain phase--I think the behavior should be opposite (`second_stage_start` unset should mean immediately entering the optimal phase). Relatedly, #240 tries to address how to set the `second_stage_start`, but first we have to resolve this (apparent) bug.

* Related to #148 which I seem to have neglected: we just add states as they appear in the `SAMSSampler`, since there is currently no standardized way to obtain the size of the space and the specific state keys. I think we should fix this soon, since we are otherwise implementing a subtly different algorithm than what's in the paper (this may ultimately be of little consequence, but to my knowledge we don't have mathematical evidence one way or another).

I'm happy to tackle this.

**Comment by jchodera** [comment]
Please do! 

For future reference: I didn't constrain the lowest free energy to be zero because this would have caused the addition of new molecules to be assigned weights dependent on the order and time of their discovery.

**Comment by pgrinaway** [comment]
Understood.

**Comment by pgrinaway** [comment]
Resolved in #303
