### ISSUE TITLE
Branches are not being Travis tested

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#297]
Unless development is done in a PR, Travis tests are not being run on branches except master, and potentially erroneous conclusions are being drawn during development because of incomplete testing. We need a solution to this to incorporate into the git flow development model if we wish to continue using it.

**Comment by pgrinaway** [comment]
I suggest that we add all branches to the `.travis.yml` like this:

```yaml

# blocklist
branches:
  except:
  - /^(?i:notest)-.*$/

```

This will automatically cause travis to build on all branches, and allow a nice dashboard-like view on travis of what's going on.

**Comment by pgrinaway** [comment]
Going to make sure that these changes make it through / troubleshoot if not. I will close this with a link to the functioning dashboard when it works.

**Comment by pgrinaway** [comment]
Ah, seems the `.travis.yml` needs to percolate into the other branches in order to have effect (the "master only" overrides everything).

**Comment by pgrinaway** [comment]
You can now see both [here](https://github.com/choderalab/perses/branches/active) and [here](https://travis-ci.org/choderalab/perses/branches) that branches with the new `.travis.yml` are being built outside of PRs.

**Comment by jchodera** [comment]
Great! OK, let's give this a try for now.
