### ISSUE TITLE
How will we visualize trajectories hopping over chemical space?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#30]
Any idea how we will be able to view trajectories where the number and identities of atoms are changing?

**Comment by jchodera** [comment]
It looks like PyMOL will happily load multi-`MODEL` PDB files where each model has completely different topologies, so we should be fine just writing these trajectories out to multi-`MODEL` PDB files.

**Comment by pgrinaway** [comment]
I'm since `pymol` seems to be able to do this, I'm going to close this issue for now. If we want another discussion on better ways of visualizing, we can open another one later.
