### ISSUE TITLE
Ensure geometry proposal probabilities correctly account for all random choices

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#305]
After discussing with @pgrinaway last week, we concluded that the acceptance criteria derivation could be extended so that the ratio of reverse and forward geometry probabilities (ratio of `$\phi$` terms in our derivation) includes the probabilities of *all* stochastic choices in the proposal, including:
* The probability of selecting the atom order out of all possible valid atom orders
* The probability of selecting which torsion of all the possible torsions to drive

I don't believe we are currently including all of these contributions.

**Comment by jchodera** [comment]
Just adding this now so we don't forget. No immediate action is required!

**Comment by pgrinaway** [comment]
Resolved in #313
