### ISSUE TITLE
Sampler driver class

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#31]
It would be useful for us to store the components of the RJMC acceptance probability to help us figure out how to optimize these moves later.

If we have the statistics for all moves stored in a log, we can later analyze the data to compute things like the log acceptance probability of every component,
```
log <A> = log <min{1, exp[-w]}>
```
If we also store the identities or indices of the proposed switch (e.g. from species 3 -> 7), we can later use BAR to reconstruct pair free energies, or an [approximate Bayesian pairwise version of BAR](http://dx.doi.org/10.1063%2F1.2937892) to get a better estimate of relative free energies.

**Comment by pgrinaway** [comment]
I agree completely. I was actually planning on implementing a `Sampler` class of some sort that would automate all of these things, including saving to a file (I was thinking NetCDF), and allowing a resume feature.

>If we also store the identities or indices of the proposed switch (e.g. from species 3 -> 7), we can later use BAR to reconstruct pair free energies

Yes, this sounds really useful!

>an approximate Bayesian pairwise version of BAR to get a better estimate of relative free energies.

Sounds really interesting!

**Comment by jchodera** [comment]
I like the idea of a driver `Sampler` class which can automate much of the machinery.

Ideally, we could have a hierarchy, like
```
Sampler (base class)
   + MCMCSampler
      + AdaptiveWeightSampler
      + FixedWeightSampler
   + BayesianBanditsSampler
      + ThompsonSampler
      + (other strategies)
```
We could, of course, simply have a flag that turns weight adaptation on/off in `MCMCSampler` instead of having two derived classes.

**Comment by jchodera** [comment]
I'm also still wondering if there isn't a way to have an `MCMCSampler` that couples together several parallel chains and uses some sort of weight adaptation algorithm that couples the chains together and provably converges to more complex target distributions, like a marginal distribution proportional to the resistance index `Z_{P_k L_ATP} / Z_{P_k L_I}`.

**Comment by jchodera** [comment]
I've also emailed Zhiqiang Tan (CCing you) about my thoughts on extending the recursion scheme for handling the more complex target sampling case where we want `pi_k \propto Z_{P_k L_ATP} / Z_{P_k L_I}`.

**Comment by pgrinaway** [comment]
Samplers are implemented.
