### ISSUE TITLE
Convert print statements to logger

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#315]
I'd like to convert the print statements to logger. The user can more easily control how verbose the output is and where the output goes.

**Comment by jchodera** [comment]
That's a good idea, though it would be nice to figure out a logger solution that is friendlier than the one we currently have for yank.

**Comment by pgrinaway** [comment]
>figure out a logger solution that is friendlier than the one we currently have for yank.

Happy to do this, but what are the pain points for logger right now? I'll try to find a solution that avoids them.

**Comment by Lnaden** [comment]
The logger is extremely verbose and virtually unreadable, there is also not any real distinction between "what goes into the log" and "what comes out on screen in verbose mode". Think if if perses had a `-vvvvvvvvv` option, thats about what you get.

**Comment by pgrinaway** [comment]
Isn't the point of logger that you can use different levels (like 'INFO', 'WARN', 'DEBUG', etc.), and then let the user choose which level to display?

**Comment by Lnaden** [comment]
Right now I don't think YANK is set up to handle that. The logger is just logging everything and spitting out just as much. We have not really had a chance to comb over what is logged and what isn't as its a lower priority than getting the science working.

I think the more general point here is perses should take the time to figure that out before just writing everything to file.

**Comment by pgrinaway** [comment]
>I think the more general point here is perses should take the time to figure that out before just writing everything to file.

Right, of course. But that isn't what we were talking about. I was talking about console output.

**Comment by Lnaden** [comment]
The YANk `logger` is related to that since verbose mode actually spits everything going to the logger to console as well. Just something to be aware of if you choose to run with that package as well

**Comment by jchodera** [comment]
I'm hoping there's some more useful logging scheme than what we ended up implementing for yank, for the reasons @Lnaden noted. There might be something really nice out there that we haven't been using yet!

**Comment by bas-rustenburg** [comment]
The logger format is really easy to customize. +1 on replacing print statements. The different levels also make it really easy to disable logging when verbosity is not desired.

**Comment by bas-rustenburg** [comment]
For reference here is my logging solution for protons:
https://github.com/choderalab/protons/blob/master/protons/logger.py

Any code that logs imports the logger from this file. You can then import it into whatever your script runs, and affect all logging output with a single command for convenience.

**Comment by pgrinaway** [comment]
Yeah, I don't know how Yank is using it currently, but it sounds like you might have missed some features. Again, I'm _not_ talking about writing to a file, just a convenient way to filter print statements. It also has more useful divisions than 'v' 'vv' etc, such as "INFO", "WARN," "DEBUG," etc.

**Comment by jchodera** [comment]
> For reference here is my logging solution for protons:

Logging the file and line looks really useful, @bas-rustenburg!

**Comment by hannahbrucemacdonald** [comment]
I think we've adopted this!
