### ISSUE TITLE
Non-specified kinetic energy variable in addGHMCStep

### ISSUE THREAD

**Issue by sgill2** [choderalab/perses#323]
In https://github.com/choderalab/perses/blob/master/perses/annihilation/ncmc_switching.py#L911-L922 there are two kinetic energy variables, "kinetic" and "ke". However ke is never actually added to the set of global variables so it causes the NCMCGHMCAlchemicalIntegrator to behave improperly.

**Comment by jchodera** [comment]
Whoops! That is indeed a bug!

**Comment by pgrinaway** [comment]
Fixing this now.
