### ISSUE TITLE
Switch to openmmtools NCMC integrator

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#327]
We should switch our [NCMC alchemical integrators](https://github.com/choderalab/perses/blob/master/perses/annihilation/ncmc_switching.py#L737-L1259) with calls to [`NonequilibriumLangevinIntegrator`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L1266-L1369) and use g-BAOAB-based splittings (e.g. `V R O H O R V`).

Note that `V R O H O R V` requires 2 x (1/2) force evaluations and two energy evaluations per timestep, all at different configurations. I'm not sure if `NonequilibriumLangevinIntegrator supports more than one H perturbation per timestep, but if so, `H V R O R V H` may be superior since it moves the energy evaluations to occur at the same positions as the force evaluations and allows them to be reused at the boundaries between timesteps.

**Comment by pgrinaway** [comment]
Complete
