### ISSUE TITLE
Create simple command-line interface

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#328]
The simplest way to get something usable right now is to write an application driver for relative free energy calculations that can be called from the command-line. 

Possible syntax might be something like
```bash
perses relative-binding --method=nonequilibrium --complex complex.pdb --current=current.mol2 --perturbed=perturbed.mol2 [--matchindex=3] --work work.out --currenttraj=current.h5 --perturbedtraj=perturbed.h5
```
where `complex.pdb` has the small molecule `current.mol2` and the perturbed molecule is `perturbed.mol2`, `method` lets us select between `nonequilibrium` and `sams`, the `matchindex` is a way of selecting amongst a deterministic set of prioritized mappings, `work.out` contains the work data to analyze, and the trajectories for the current and perturbed complexes are written in HDF5 format by MDTraj (which also contains the topology).

The [`docopt` dispatch method in yank](https://github.com/choderalab/yank/blob/master/Yank/cli.py) may be useful if you intend to write a few command-line drivers.

Reusable components of the application driver can then be refactored into library functions and tasklets that are called by a distributed application driver.

**Comment by jchodera** [comment]
Woody notes that it would be great to have the option of specifying a YAML file that specifies all of the other run options, such as simulation time, lambda schedule (for SAMS) or switching schedule, etc.

**Comment by jchodera** [comment]
Two more observations:
* SAMS simulations would probably instead have a single output trajectory for ligand-in-complex and a single trajectory for ligand-in-solution
* Nonequilibrium switching would presumably also include another argument to say whether the complex phase or solution phase is being simulated
* Depending on how #344 is implemented, we may need an argument for checkpoint file

**Comment by pgrinaway** [comment]
Opted for API.
