### ISSUE TITLE
Add support for transformations that change net charge

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#332]
Supporting transformations that change net charge will require the ability to eliminate or introduce a counterion as well. We may alternatively be able to transform a counterion into a water, or vice-versa.

I'm not sure if we need to include some sort of chemical potential term or other charge correction.

**Comment by jchodera** [comment]
Currently, this is low priority for SiliconTx.

**Comment by hannahbrucemacdonald** [comment]
Linking to #596 and closing
