### ISSUE TITLE
Eliminate GHMCIntegrator in favor of openmmtools implementation

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#338]
We can eliminate [`perses.samplers.GHMCIntegrator`](https://github.com/choderalab/perses/blob/master/perses/samplers/samplers.py#L402-L526) in favor of [`openmmtools.integrators.LangevinIntegrator`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L810-L858) and switch to using g-BAOAB.

**Comment by pgrinaway** [comment]
We're not using `GHMCIntegrator` anymore.
