### ISSUE TITLE
Support ORNL Titan

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#341]
SiliconTx will apparently have ORNL Titan time available in the ~1 mo timescale, accessible for doing publishable work and validation.

**Comment by jchodera** [comment]
Most of the early validation will happen on Titan, it sounds like.

**Comment by pgrinaway** [comment]
The major thing to investigate here is CUDA/OpenCL support on Titan and compatibility with OpenMM.

**Comment by jchodera** [comment]
I couldn't glean anything from the online docs, so you'll probably need to contact support there.

**Comment by jchodera** [comment]
No longer relevant.
