### ISSUE TITLE
SAMS support

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#343]
Equilibrium (SAMS) support is also important for the short term.

**Comment by pgrinaway** [comment]
Since by this you mean SAMS between different alchemical states, shouldn't this be in another repository? As for the changes in this repository, I'd imagine that would just involve using the SAMS sampler from a standardized stack here.

**Comment by jchodera** [comment]
Yes, but we would have to (1) make sure to implement a standardized SAMS sampler into openmmtools, and (2) add support for using that SAMS sampler to compute relative free energies for individual transformations within Perses. 

I was just capturing the need in this issue, so feel free to break this into separate issues for both repositories, but (1) will obviously need to happen before (2).

**Comment by hannahbrucemacdonald** [comment]
We can do this
