### ISSUE TITLE
Make sure tasks output sufficient data.

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#355]

**Comment by pgrinaway** [comment]
This is partly done, but needs to be fixed because the data is not retrieved from celery properly.

**Comment by jchodera** [comment]
I think we also wanted to add optional arguments to the tasklets to specify the interval at which data is to be saved:
* `run_protocol` should store cumulative work, box vectors, and configurations at this interval
* `run_equilibrium` should store box vectors, configurations, and energies at this interval

By default, only the *last* values would be stored.

**Comment by jchodera** [comment]
Looks like this was addressed in #396. Can this be closed?
