### ISSUE TITLE
Ensure core atoms are correctly identified when there are no unique atoms

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#362]
In transformations such as 1-fluorobenzene to 1-chlorobenzene, we are unclear as to whether the current atom-matching scheme would flag there the ligand residue does not have any atoms that are deleted or added, resulting in no `unique` atoms found. We should refine the logic used to identify `environment` atoms to make sure these corner cases are correctly handled.

**Comment by pgrinaway** [comment]
We should move the determination of whether an atom is in core or environment to the atom mapping facility to avoid this problem. We can also add a second stage to de-map atoms that would change a constraint length.

**Comment by jchodera** [comment]
I'm diving into this now!

**Comment by jchodera** [comment]
Pinging this thread to note the remainder of this solution needs to be implemented now that #420 is in.

**Comment by jchodera** [comment]
Fixed by naming residues `MOL`
