### ISSUE TITLE
Exclude hydrogens from being mapped

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#363]
In order to allow us to run `perses` with bonds to hydrogen constrained, we are forced to exclude hydrogens from mapped atoms so that they are always `unique`. Otherwise, we would not be able to permit constrained `H-X` bonds of different lengths in initial and final states.

**Comment by pgrinaway** [comment]
Currently being addressed in #398

**Comment by pgrinaway** [comment]
This wasn't actually fully addressed.

**Comment by pgrinaway** [comment]
From a slack discussion with @jchodera, he suggested that we could set the atom mapping criteria in a way that doesn't allow ring breakage, and also doesn't map hydrogens.

```
DEFAULT_ATOM_EXPRESSION = oechem.OEExprOpts_Aromaticity | oechem.OEExprOpts_RingMember | oechem.OEExprOpts_Degree | oechem.OEExprOpts_AtomicNumber | oechem.OEExprOpts_EqAromatic | oechem.OEExprOpts_EqHalogen | oechem.OEExprOpts_EqCAliphaticONS
```

@jchodera adds:

>* `oechem.OEExprOpts_AtomicNumber` won't map one element onto another, BUT:
>* `oechem.OEExprOpts_EqAromatic` lets you change atoms within aromatic heterocycles as long as they are still aromatic (so no benzene to cyclohexane)
>* `oechem.OEExprOpts_EqHalogen` treats all halogens as equivalent, and
>* `oechem.OEExprOpts_EqCAliphaticONS` treats aliphatic atoms we care about as equivalent

>Longer term, the correct fix is to annotate the bonds for molecules going into `_get_mol_atom_map` to label them as constrained or unconstrained, then use that information to not map bonds that change constraint.
>But it will take more refactoring to make that longer-term change


>We could use the user-defined `IntType` for labeling constrained bonds as 1 and unconstrained bonds as 0 and the `OEExprOpts_IntType` for checking they are the same:
https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEExprOpts.html#OEChem::OEExprOpts::IntType

**Comment by pgrinaway** [comment]
I believe that #441 fixes this

**Comment by jchodera** [comment]
Let's keep this open so we can implement the second solution later:
> Longer term, the correct fix is to annotate the bonds for molecules going into _get_mol_atom_map to label them as constrained or unconstrained, then use that information to not map bonds that change constraint.
> But it will take more refactoring to make that longer-term change
We could use the user-defined `IntType` for labeling constrained bonds as 1 and unconstrained bonds as 0 and the `OEExprOpts_IntType` for checking they are the same:
https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEExprOpts.html#OEChem::OEExprOpts::IntType

**Comment by hannahbrucemacdonald** [comment]
We are sorted on how we map/don't map hydrogens
