### ISSUE TITLE
Anywhere with setPositions and getPositions, make sure to get/set box vectors

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#367]
Currently, the code only sets/gets positions, but if a barostat is in use, the box volume must also be tracked in order for the code to work in explicit solvent.

We can use the [`openmtools.mcmc` framework](http://openmmtools.readthedocs.io/en/latest/mcmc.html) to simplify this tracking of all the information (positions, velocities, box vectors) associated with a sampler state.

**Comment by pgrinaway** [comment]
Being addressed in #396

**Comment by jchodera** [comment]
Can this be closed since #396 was merged?
