### ISSUE TITLE
Add endpoint perturbations

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#372]
Since `lambda = 0` and `lambda = 1` for the hybrid alchemical system are not identical to the initial and final fully interacting systems, we need to also compute the energy differences between alchemical and real systems. Since it's best to amortize the cost over the entire calculation rather than reprocess the whole trajectory, we want to either add this to the tasklet that computes the nonequilibrium switching trajectory (where we perform `real A -> alchemical lambda=0 ------> alchemical lambda=1 -> real B` and return these energy differences as well) or add a separate tasklet to do just these calculations, since they could in principle be done in parallel with nonequilibrium switching (though might be so quick as to not be necessary to parallelize).

This brings up the point that we could either run our equilibrium simulations with (1) the `real A` and `real B` states *or* (2) the `alchemical lambda=0` and `alchemical lambda=1` states. I'm not actually sure which would be most efficient. (1) benefits from using BAR for the whole free energy calculation, while (2) reduces the thermodynamic length between the states that are sampled from equilibrium and their targets.

**Comment by pgrinaway** [comment]
>This brings up the point that we could either run our equilibrium simulations with (1) the real A and real B states or (2) the alchemical lambda=0 and alchemical lambda=1 states. 

I'm not sure this is so easy. If we do that, we'll need to do a reversible jump step at the beginning of each nonequilibrium protocol. We do have the code for it, but one of the advantages of tackling NE switching first was avoiding the hairy details of ensuring that that was correct.

**Comment by jchodera** [comment]
Good point! That means we're stuck with simulating the dual topology system. That makes it easier!

**Comment by jchodera** [comment]
To avoid a reversible jump step in going  from the dual topology lambda = 0 or 1 states to the A or B real systems, we probably want to keep the valence terms and just compute the nonbonded contributions for the real systems. That mimics being able to actually fix the nonbonded forces correctly, but retaining the valence terms for the hybrid system (which match the A and B states plus the dummy atom valence terms). This has the happy result of eliminating the extra variance contributions from the extra degrees of freedom too. 

We should also use this in our tests: Just compute the overlap for the difference in nonbonded energies, omitting the valence terms.

**Comment by pgrinaway** [comment]
This was completed in #399
