### ISSUE TITLE
GPU out of memory issue

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#373]
There are too many exceptions in the system; OpenMM cannot allocate enough memory for them. The resolution involves moving some interactions to a new force.

**Comment by jchodera** [comment]
Alternatively, the `epsilon` and `charge` parameters for the core atoms can be zeroed out and the few core-core interactions can be encoded as exceptions, vastly reducing the total number of exceptions.

**Comment by pgrinaway** [comment]
Resolved in #380
