### ISSUE TITLE
Handling storage and logging for first-gen application

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#377]
We need to figure out how we want to implement a storage and logging system for the initial command-line relative free energy application.

**Comment by pgrinaway** [comment]
Initially, we want to store:

* Work values
* Trajectories as `mdtraj` file
* Switching trajectories w/ per-step work.

We also want to output some initial simulation setup data:
 * initially we can output the `NonequilibriumFEPSetup` to disk as a pickle


We also need run status:
    * Logging status from each tasklet
        * Celery output
        * Log to redis
    * Logging status from master

**Comment by jchodera** [comment]
@pgrinaway : I've updated the proposal above with a concrete suggestion as to how to store data. Would love your feedback/revisions, especially regarding how to store nonequilibrium data.

If the tasklets return, say, `mdtraj.Trajectory` objects and `numpy` arrays, a chained tasklet responsible for writing the data to disk can later be swapped out to deposit the data in a database or something.

**Comment by pgrinaway** [comment]
Being addressed in #396

**Comment by pgrinaway** [comment]
Addressed in #396
