### ISSUE TITLE
Handle Schrodinger JACS set systems automatically

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#378]
The Schrodinger JACS set contains unmodeled loops where residues have been terminated with hydrogens instead of ACE/NME blocking groups. The AMBER forcefields we use don't have residue templates for these hydrogen-terminated residues.

**Comment by pgrinaway** [comment]
Let's try to work this out Thu/Fri.

**Comment by jchodera** [comment]
@steven-albanese suggests we need to run it through PDBFixer with the option to replace nonnatural amino acids, but only adding atoms for this replaced residue.

**Comment by hannahbrucemacdonald** [comment]
I think that this is addressed in @brycestx 's repo https://github.com/brycestx/perses_jacs_systems
