### ISSUE TITLE
Add support for FEPMapper-specified atom mappings / chemical transformations

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#379]
We may want to allow the user to start with an FEPMapper-specified atom mapping for chemical transformations.

**Comment by brycestx** [comment]
I propose we make this high priority for reproducibility and testing of different atom mappings.

**Comment by pgrinaway** [comment]
Ok. Can anyone point me to the format in which FEPMapper gives you atom mappings?

**Comment by hannahbrucemacdonald** [comment]
We have the option to either - define the atom map _a priori_ or use MCSS keywords to generate a whole bunch of atom maps so I think this is done/
