### ISSUE TITLE
Code quality improvements

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#382]
Check that generators are not unnecessarily expanded and that code is not unnecessarily duplicated.

**Comment by pgrinaway** [comment]
This is rather vague and will hang around forever. We can raise separate issues for specific quality points.

**Comment by jchodera** [comment]
I believe I had pointed out specific places where this was an issue in my code review. We should just restrict this issue to those sections.

**Comment by jchodera** [comment]
In hindsight, we should have captured the details of which sections these were in our original issue.
