### ISSUE TITLE
Explicit hydrogen SMILES is causing failures in SmallMoleculeSetProposalEngine

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#394]
The travis tests [are failing](https://travis-ci.org/choderalab/perses/jobs/270885563#L1944) because the `SmallMoleculeSetProposalEngine` is now using explicit hydrogens in the SMILES string but is being fed SMILES without explicit hydrogens. 

Short term:
 * We could add hydrogens to SMILES without them
 * We could make sure the input is explicit-hydrogen SMILES (I think this is better for now*)

Long term:
 * We can think a bit more about the way the ProposalEngines work and how to internally represent chemical states.

* I imagine that adding hydrogens to the SMILES strings could lead us to a problem where the hydrogens are inappropriately rearranged as before.

**Comment by jchodera** [comment]
We will likely want to generally work with a two-stage procedure:
* Propose a transition to (and keep statistics for) a chemical species that encompasses all protonation/tautomer states, whether this is for small molecules or protein residues
* Propose a specific protonation/tautomer state for this species according to some biasing probability, such as the solution populations of these protonation states

There are cases where we may only want a one-stage procedure---such as using perses to sample over all protonation/tautomer states of a small molecule and some residues---but that could likely be implemented within the two-stage scheme by just ensuring only one chemical species can be proposed, so the second stage would choose the appropriate protonation state.

In light of that, what if we rework the small molecule proposal engine to
* track statistics using a single canonical isomeric SMILES string without hydrogens
* used this to propose a specific explicit-hydrogen species with a specific protonation/tautomer state, and used that for all explicit molecule construction in the geometry engine

**Comment by jchodera** [comment]
Looks like this issue might be why our Travis tests on master are consistently failing:
https://travis-ci.org/choderalab/perses/jobs/279580231

**Comment by pgrinaway** [comment]
What do you mean? The issue was originally about how the explicit hydrogens are making travis tests fail. Did you mean to link to a specific line?

**Comment by jchodera** [comment]
> Did you mean to link to a specific line?

Whoops! I had tried to, though I see that's totally redundant now. I was just surprised tests were still failing, but it's due to this issue.

**Comment by pgrinaway** [comment]
Oh, yeah, that's why I raised the issue. Will fix soon so that the test failure goes away.
