### ISSUE TITLE
Plan going forward

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#4]
Now that we have some base API, my imagination of the priorities are:

1a. Get the meat of instantaneous compound switching put together
1b. Get tests for this part in the repo and running on travis

2. Make conda-installable

3. Add in NCMC switching

Unless there are any objections, I'll start working on them in this order.

**Comment by jchodera** [comment]
We should do a bit of prep work to get this in a shape where multiple people can contribute at once.

Here's what I think we need to do:
* Rename the repo to be a useful Python package name (`perses`?)
* Reorganize repo to create a directory/module structure, like:
```
perses/
   perses/
      annihilation/ - alchemical factories for annihilation
      dualtopology/ - direct dual-topology alchemical transformation
      multitopology/ - core-based multi-topology alchemical transformation
      rjmc/ - reversible-jump based methods
      tests/ - automated tests
   devtools/
   examples/
   setup.py
   travis.yml
   README.md
```
* Add basic documentation in `README.md` just to describe where stuff is
* Add `setup.py` to make this Python installable
* Add `devtools/` and `travis.yml` and enable automated testing [JDC can do this]
* Add `examples/` with most basic working example of each type

After that, I think we're all set to divide up the work and flesh out some details of the `rjmc` approach:
* geometry engine [PBG]
* small molecule topology proposal engine [PBG] based on simplest approach (picking similar compounds from a specified compound library using MCSS?)
* protein topology proposal engine [JMB]
* NCMC switching using alchemical protocols [JDC]

I'll also clean up the `multitopology` and `alchemical` scripts to the point where we can have Julie figure out how to use them for residue mutations.

**Comment by jchodera** [comment]
Does this sound reasonable?

**Comment by pgrinaway** [comment]
That definitely sounds reasonable to me. Do you want me to organize the repo as you described above, or did you want to do it as you indicated in the pull request? Either is fine with me, I just don't want to leave the repo in a weird state.

**Comment by jchodera** [comment]
Can you take a stab at it?  Feel free to do some direct commits if that is easiest, and raise an issue if you want any input/feedback!

**Comment by pgrinaway** [comment]
Sounds good

**Comment by jchodera** [comment]
OK, we've stripped out the alchemical stuff and moved it to [`examol`](http://github.com/choderalab/examol).

We might need to add in some additional tests and automatic running of the examples to make sure they work.

After that, we can get to work on dividing up the actual implementation!

**Comment by pgrinaway** [comment]
I'm going to close this for now to avoid issue clutter.
