### ISSUE TITLE
Add subsampling for free energy estimation

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#401]
We should add subsampling to avoid a vastly underestimated variance of the free energy estimates.

**Comment by brycestx** [comment]
Agreed, we use subsampling in house and it has reduced our error estimates

**Comment by pgrinaway** [comment]
Just a note to @jchodera that we should discuss what the best way to do this is.

**Comment by pgrinaway** [comment]
Resolved in #439.
