### ISSUE TITLE
Store energies and work values to file for analysis

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#410]
NetCDF is a good choice to begin with until we choose a database.

**Comment by andrrizzi** [comment]
One solution to avoid the concurrent writing with NetCDF is to have a separate queue for `write_to_disk` Celery tasks and assign only a single worker to that queue. This way writing tasks could be run asynchronously.

**Comment by pgrinaway** [comment]
Closing in favor of potential discussion on #421
