### ISSUE TITLE
Add a ring opening/closing test case

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#42]
The null transformation of naphthalene to naphthalene (where a ring is destroyed at one end and created at the other end) would be a great test case since we know the free energy difference should be zero.  (Jed Pitera had a paper on this test case with Wilfred van Gunsteren.). We can do this in vacuum, implicit solvent, and explicit solvent.

This would be a very powerful test because of the novelty of our ability to handle ring opening and closing.

**Comment by jchodera** [comment]
Jed's naphthalene paper is here: http://dx.doi.org/10.1080/08927020211973

**Comment by jchodera** [comment]
I've already implemented [this test case](https://github.com/choderalab/perses/blob/master/perses/tests/testsystems.py#L1829-L1835).

**Comment by jchodera** [comment]
Whoops, my mistake: I only implemented `benzene <-> napthalene`, not the naphthalene null transformation (which would require just testing the geometry engine part).

**Comment by pgrinaway** [comment]
Yeah, I almost made the same mistake and closed the issue, but you're right.

**Comment by pgrinaway** [comment]
These are in the repo.
