### ISSUE TITLE
Move all instances of forcefield_generators.generateOEMolFromTopologyResidue(mol_res) to oess

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#422]
The `forcefield_generators` methods like `generateOEMolFromTopologyResidue` have been deprecated and replaced with more methods from https://github.com/oess/oeommtools

This isn't yet available in `omnia` or `conda-forge` yet, but the [LICENSE](https://github.com/oess/oeommtools/blob/master/LICENSE) permits us to use these methods in our own code.

**Comment by pgrinaway** [comment]
Can we easily fall back to antechamber/sqm if OpenEye is not present?

**Comment by jchodera** [comment]
A better way to tackle this might be to use the new openforcefield Topology object that will also encode small molecule information and support both the RDKit and OpenEye toolkits. We will have to create a version of OpenMM Forcefield that supports this Topology object for plugging in antechamber Forcefield generators, but the good news is that this would allow us to use the Smirnoff forcefields as well.

**Comment by jchodera** [comment]
If we can also be sure to add support for things you need to do with the OpenEye toolkits into the openforcefield Topology API, this also provides a route to eliminating OpenEye dependencies if desired.

**Comment by jchodera** [comment]
We will tackle this through #521 instead.
