### ISSUE TITLE
Very high energies in null hybrid system at intermediate lambda values

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#431]
@brycestx , you told me on a call yesterday that you had very high energies in the null (where both endpoints are the same) hybrid system after 1000 steps of Langevin dynamics at the endpoint. Could you clarify/post the code you used to get that here so that I could start working on this?

**Comment by brycestx** [comment]
Sorry for the delay. The code below is taken from [test_elimination](https://github.com/choderalab/perses/blob/master/perses/tests/test_elimination.py). I found that the SmallMoleculeSetProposalEngine._get_mol_atom_map function does not map the bridgehead carbons of napthalene leading to huge errors in the custom and harmonic bond forces:
```
-----------------------
Energy components at lambda=0
CustomBondForce	5562433841603.15 kJ/mol
HarmonicBondForce	1.559132968215998e+16 kJ/mol
CustomAngleForce	1047.314638742342 kJ/mol
HarmonicAngleForce	7102.562500935552 kJ/mol
CustomTorsionForce	9.495888666549268e-07 kJ/mol
PeriodicTorsionForce	2.8461500720252927e-05 kJ/mol
NonbondedForce	5.683903055989541e-05 kJ/mol
CustomNonbondedForce	-0.004548577877067871 kJ/mol
CustomNonbondedForce	-9.847170273164524e-20 kJ/mol
CustomBondForce	0.007901860449835528 kJ/mol
-----------------------
Energy components at lambda=1
CustomBondForce	5562433841603.15 kJ/mol
HarmonicBondForce	1.559132968215998e+16 kJ/mol
CustomAngleForce	1047.314638742342 kJ/mol
HarmonicAngleForce	7102.562500935552 kJ/mol
CustomTorsionForce	9.495888666549268e-07 kJ/mol
PeriodicTorsionForce	2.8461500720252927e-05 kJ/mol
NonbondedForce	5.683903055989541e-05 kJ/mol
CustomNonbondedForce	-0.004547877224575666 kJ/mol
CustomNonbondedForce	-9.847170029376088e-20 kJ/mol
CustomBondForce	0.007901860449835528 kJ/mol
------------------------
```
I believe I have fixed the mcs code in that function to avoid this from happening and will push a pull request with my implementation.

```
from simtk import openmm, unit
from simtk.openmm import app
import os, os.path
import sys, math
from unittest import skipIf
import numpy as np
from functools import partial
from pkg_resources import resource_filename
from openeye import oechem
if sys.version_info >= (3, 0):
    from io import StringIO
    from subprocess import getstatusoutput
else:
    from cStringIO import StringIO
    from commands import getstatusoutput
from openmmtools.constants import kB
from perses.annihilation.new_relative import HybridTopologyFactory

temperature = 300.0 * unit.kelvin
kT = kB * temperature
beta = 1.0/kT

def simulate_hybrid(hybrid_system,functions, lambda_value, positions, nsteps=100, timestep=1.0*unit.femtoseconds, temperature=temperature, collision_rate=5.0/unit.picoseconds):
    platform = openmm.Platform.getPlatformByName("OpenCL")
    integrator = openmm.LangevinIntegrator(temperature, collision_rate, timestep)
    context = openmm.Context(hybrid_system, integrator, platform)
    for parameter in functions.keys():
        context.setParameter(parameter, lambda_value)
    context.setPositions(positions)
    initial_energy = context.getState(getEnergy=True).getPotentialEnergy()
    integrator.step(nsteps)
    positions = context.getState(getPositions=True).getPositions(asNumpy=True)
    final_energy = context.getState(getEnergy=True).getPotentialEnergy()
    return positions, initial_energy, final_energy

def generate_hybrid_test_topology(mol_name="naphthalene", ref_mol_name="benzene"):
    """
    Generate a test topology proposal and positions for the hybrid test.
    """
    from perses.rjmc.topology_proposal import SmallMoleculeSetProposalEngine, TopologyProposal
    from perses.tests.utils import createOEMolFromIUPAC, createSystemFromIUPAC

    mol = createOEMolFromIUPAC(mol_name)
    m, system, positions, topology = createSystemFromIUPAC(mol_name)

    refmol = createOEMolFromIUPAC(ref_mol_name)

    #map one of the rings
    atom_map = SmallMoleculeSetProposalEngine._get_mol_atom_map(mol, refmol)

    #now use the mapped atoms to generate a new and old system with identical atoms mapped. This will result in the
    #same molecule with the same positions for lambda=0 and 1, and ensures a contiguous atom map
    effective_atom_map = {value : value for value in atom_map.values()}

    #make a topology proposal with the appropriate data:
    top_proposal = TopologyProposal(new_topology=topology, new_system=system, old_topology=topology, old_system=system, new_to_old_atom_map=effective_atom_map, new_chemical_state_key="n1", old_chemical_state_key='n2')

    return top_proposal, positions


if __name__ == '__main__':
    #make the hybrid topology factory:
    topology_proposal, positions = generate_hybrid_test_topology()
    factory = HybridTopologyFactory(topology_proposal, positions, positions)

    hybrid_system = factory.hybrid_system
    hybrid_topology = factory.hybrid_topology
    initial_hybrid_positions = factory.hybrid_positions

    functions = {
        'lambda_sterics' : '2*lambda * step(0.5 - lambda) + (1.0 - step(0.5 - lambda))',
        'lambda_electrostatics' : '2*(lambda - 0.5) * step(lambda - 0.5)',
        'lambda_bonds' : 'lambda',
        'lambda_angles' : 'lambda',
        'lambda_torsions' : 'lambda'
    }

    equil_positions, initial_energy, final_energy = simulate_hybrid(hybrid_system,functions, 0.0, initial_hybrid_positions)
    print("Initial energy: ", initial_energy)
    print("Final energy: ", final_energy)
```

**Comment by pgrinaway** [comment]
Thanks, taking a look now.

**Comment by pgrinaway** [comment]
Ah, maybe because the default atom mapping criteria include `OEExprOpts_HvyDegree`, and those atoms have a higher heavy degree? Thanks for finding this, btw.

**Comment by pgrinaway** [comment]
![napthalene_null](https://user-images.githubusercontent.com/4674712/32917718-17fa2210-caee-11e7-8d74-0ba4d73882b8.png)

Ok I'm noticing (see above) that the sterics force is going crazy as we switch lambda from 0 to 1. I also noticed that the regular `NonbondedForce` starts off at `nan` for some reason. I'm digging into this now.

PS: apologies for the crappy legend.

**Comment by brycestx** [comment]
@pgrinaway yes I have noticed this trend across multiple ligands as well. I have not been able to determine the cause yet unfortunately.

**Comment by jchodera** [comment]
Just a few observations to summarize our phone call with @brycestx:
* Ring closures (like benzene -> napthalene) are NOT currently supported by the HybridTopologyAlchemicalFactory. This should raise an exception, though we'd have to figure out how to detect ring opening/closing transformations. We should create a new issue for that.
* The `functions` you use above are meant for an absolute alchemical protocol. We should only be using the linear protocol (everything is set to `lambda`) for now. I think your example is based on [this test](https://github.com/choderalab/perses/blob/master/perses/tests/test_elimination.py#L167-L241) that should be running correctly on travis (but also uses the weird functions above).
* It would be great if you folks could provide a list of druglike transformations that we can add a test for to make sure that the transformation engine works well for these. We can add a travis test to make sure a few steps of dynamics don't explode for lambda = 0 or 1. You can also annotate the transformations with a mapping so we can manually check we're not screwing these up.
* We can prioritize the ability to specify manual maps or manually specify atom mapping rules if you'd like. We already have [this issue](https://github.com/choderalab/perses/issues/379) open but hadn't prioritized it. We can make it high priority if you like!

**Comment by pgrinaway** [comment]
I think we determined that this is not an issue at this point. Reopen if needed.
