### ISSUE TITLE
Atom gets de-mapped by HybridTopologyFactory

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#432]
@brycestx You told me on a call yesterday that when mapping a Fluorine atom to a Hydrogen atom, the Carbon that they are connected to is de-mapped. Can you post the code you used to observe this (or clarify if I'm mistaken about what you said)? Thanks! I can get started trying to fix this as soon as I have the code for it.

**Comment by jchodera** [comment]
Was hydrogen atom mapping (#363) ever fully addressed? I started on that but ended up fixing other issues in #420 and not tackling this myself.

**Comment by pgrinaway** [comment]
That might have been closed in error. I'll reopen, but it's a separate problem.

**Comment by pgrinaway** [comment]
It looks like this might be happening because of a [change](https://github.com/choderalab/perses/pull/420/files#diff-bd95c4342ca1beb79ba546696bfdc262R1300) in the default atom mapping in a past PR. I think this causes a carbon in a ring that is connected to a hydrogen to be unmapped if the other system contains a heavy atom in place of that hydrogen. I think we should remove heavy degree from the mapping criteria.

**Comment by jchodera** [comment]
Good catch!

I had misinterpreted [`OEExprOpts_HvyDegree`](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEExprOpts.html#OEChem::OEExprOpts::HvyDegree) as being "match the degree of just heavy atoms", but it is indeed the number of heavy atoms bound to the atom. We should replace this with [`OEExprOpts_Degree`](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEExprOpts.html#OEChem::OEExprOpts::Degree).

**Comment by jchodera** [comment]
I've fixed this in #441.
