### ISSUE TITLE
Examples of mappings from CDK2 ligands in JACS set

### ISSUE THREAD

**Issue by brycestx** [choderalab/perses#433]
@jchodera mentioned it would be helpful to post examples of transformations that should serve to develop a test set for atom mapping and hybrid topology construction. Attached is a pdf showing a transformation in each row with highlighted atoms being those we are mapping with our internal protocols. These molecules are all located in the CDK2_ligands.mol2 file provided previously and attached here as well. 
[cdk2.pdf](https://github.com/choderalab/perses/files/1480645/cdk2.pdf)
[CDK2_ligands.zip](https://github.com/choderalab/perses/files/1480651/CDK2_ligands.zip)

**Comment by jchodera** [comment]
Thanks! We'll take a look at this.

Right off the bat, I can see that we don't map bond-constrained hydrogens (e.g. `C-H`) that change into unconstrained bonds (e.g. `C-Br`), so our mapping will differ from yours. We should have the [OpenEye Grapheme Toolkit](https://docs.eyesopen.com/toolkits/cookbook/python/depiction/simcalc.html) auto-generate PDFs of our mappings so we can more easily debug what's going on: I created an issue (#419) to remind us to do this.

**Comment by jchodera** [comment]
We've now fixed the hydrogen mapping issue (#363) and are now testing our mappings on the CDK2 JACS benchmark set. If we notice more issues, we can add tests to `perses/test_topology_proposal.py:test_molecular_atom_mapping()` to catch them.
