### ISSUE TITLE
Clean up setup and tests

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#434]
There are some tests that are either inactive or need to be cleaned up/better documented. In particular, the setup code for nonequilibrium switching free energy calculations needs to be refactored:

- [ ] Separate functions for each task, rather than a large class that does everything on instantiation.
- [ ] Tests for each function and the composition of the functions
- [ ] Allow separation of setup pipeline and run code (output thermodynamic and sampler states from the setup, input thermodynamic and sampler states for the run code).

**Comment by hannahbrucemacdonald** [comment]
This has (to some degree been fixed).

Closing this issue, and will look into resurrecting codecov for the package
