### ISSUE TITLE
Using new_relative.py

### ISSUE THREAD

**Issue by alexW432** [choderalab/perses#435]
Hello,

I would like to make a conda installation of perses, particularly I would like to use new_relative.py. To do this do I need an installation of perses-dev? 

Currently I'm trying to install perses-dev following the instructions here http://perses.readthedocs.io/en/latest/installation.html. But receive the error 'Packages missing in current channels'. 

Thank you in advance for any help,
Alex

**Comment by pgrinaway** [comment]
Hi! We're not quite at the point of having the conda release built--this code is still very much a work in progress. I can try to tackle this later after solving some other problems that are currently on my todo list.

**Comment by jchodera** [comment]
For now, [installing via `pip`](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch) or directly from the github repo is the best approach.

**Comment by alexW432** [comment]
Thank you, installing from the repo works. However I needed to change:
`import lxml.etree as etree` 
in new_relative.py to 
`from xml import etree as etree`. 
is there a way to avoid this change as I'm not confident of the effect it may have?

Please may I also ask if perses and new_relative.py require an openeye license for the purpose of relative free energy calculations? 

Thanks,
Alex

**Comment by pgrinaway** [comment]
>is there a way to avoid this change as I'm not confident of the effect it may have?

Do you have `lxml` installed? If not, try installing it. 

>Please may I also ask if perses and new_relative.py require an openeye license for the purpose of relative free energy calculations?

The short answer is yes, at least for the foreseeable future. 

The long answer:

It depends on what exactly you mean by relative free energy calculations. The code that actually runs the calculations (including the one that builds the hybrid topology) does not directly need OpenEye. However, all of the tools that set up the inputs to the hybrid topology factory, etc. do require OpenEye. So you might technically be able to get it to run a calculation without OpenEye, but you'll need to do a lot of extra tooling, etc. We don't currently have the time to address that issue in the near future.

Also, I'd like to stress again that this project is a work in progress; it hasn't been validated yet, so tread with caution.

**Comment by alexW432** [comment]
I have installed lxml with conda, I'm not sure what is happening here but I'll continue to look at it. Thank you for your help, I'll most definitely continue with caution.

Alex

**Comment by jchodera** [comment]
@pgrinaway: Even if we're far from distributing a useful `perses` development version conda build, it probably wouldn't hurt to have a conda recipe that installs all the prerequisites for a `perses` development environment (e.g. `perses-devenv`) so that no additional dependencies are needed to then install from github source.
