### ISSUE TITLE
[WIP] Trajectory of CDK2 perturbation 17~1h1q, trajectory looks fine, energies strange

### ISSUE THREAD

**Issue by brycestx** [choderalab/perses#437]
Attached are scripts and pickled system of this perturbation. Will update after call, WIP

**Comment by jchodera** [comment]
I don't the attachments made it!

**Comment by brycestx** [comment]
[cdk2-17~1h1q-solvated.tar.gz](https://github.com/choderalab/perses/files/1515962/cdk2-17.1h1q-solvated.tar.gz)
Sorry about that, it must have messed up earlier. It includes a python script "issue.py" which recreates the "cdk2-17~1h1q-solvated.h5" trajectory output using the pickled "solvent_nefep_17~1h1q.pkl" perses NonequilibriumSwitchingFEP class object. Also provided is a xml serialized hybrid system. The script repeatedly calls the perses.utils.tests compare_at_lambdas function to print out the energies after 10 steps of AlchemicalNonequilibriumLangevinIntegration. Let me know if you have any further questions.

**Comment by brycestx** [comment]
We are hoping that by fixing the mapping issue we resolved today that this issue will be mediated. I am working on testing the new mapped hybrid system now.

**Comment by jchodera** [comment]
Is the mapping issue the one discussed in https://github.com/choderalab/perses/issues/432 ?

**Comment by jchodera** [comment]
We've now resolved #432, so we can test to see if that's resolved this issue when @pgrinaway finishes the Jupyter notebook for visualizing the work traces and trajectories for individual transformations.

**Comment by brycestx** [comment]
This issue is resolved now due to #459 I am able to get a robust accurate result for this perturbation now
