### ISSUE TITLE
CDK2 test set solvated perturbation nonequilibrium trajectories and work traces

### ISSUE THREAD

**Issue by brycestx** [choderalab/perses#447]
Attached is a file containing only solvated nonequilbrium trajectories and cumulative work values for [cdk2_ligands](https://github.com/choderalab/perses/blob/master/perses/data/schrodinger-jacs-datasets/CDK2_ligands.sdf) indices (14~15). We should use this perturbation as a first test to determine if we can get accurate RBFE results. 
[14~15-CDK2-solvated.zip](https://github.com/choderalab/perses/files/1560419/14.15-CDK2-solvated.zip)
Currently the df0 calculated from the lambda 0 endpoint is: -10504.853731358771 kT
df1 calculated from lambda 1 endpoint: 84.904680228117755 kT
and df from the nonequilibrium simulation: 78.281863111131315 kT 
Therefore the total dG I get for this solvated perturbation is 10668.04027469802 kT. 
Forward and reverse reduced potential differences and cumulative work after each iteration are shown below. Notice that iteration 11 of the forward (0) reducted potential differences is an outlier. After looking at that trajectory `traj.11.neq.lambda0.h5` I see no movement throughout the frames. I am looking into why this may be happening:
```
ne_fep._reduced_potential_differences
Out[16]: 
{0: [-11.346437360396521,
  100.34721449674726,
  283.05096569113084,
  238.52935154491752,
  275.8252905156005,
  285.42990750043282,
  279.76571022356256,
  240.46748791988102,
  115.59348695034532,
  92.76229861201864,
  -10509.407608250373,
  -373.58137207436448,
  -185.37731438631636,
  -326.5608721363933,
  -227.96288707334134,
  -292.37378659452952,
  -153.07394808256686,
  -251.49275520161609,
  -193.57948806558488,
  -70.560868709993883,
  -448.7329061467135,
  -573.24619985672507,
  -921.70574174213471,
  -309.24743294938708,
  139.14997211575974,
  185.48675990177799,
  175.0189724552838,
  295.14339864036447,
  150.79739197114577,
  -1987.8725498917338,
  251.92119363828533,
  -552.26937813295444,
  335.51699696994001,
  304.24358623174157,
  136.45255186729082,
  162.5804412310481,
  321.27220908757772,
  262.42024682178817,
  18.550599196958501,
  338.69792701837105,
  299.79717519889346,
  289.69490296862386,
  326.66279081900211,
  264.51100560107625,
  -491.79337363737795,
  232.66936576400076,
  344.97144634465076,
  292.83547180213827,
  166.48264769177331,
  459.35319588270977,
  262.85140858613886,
  212.11687037486809,
  229.46618065580151,
  145.03683437413201,
  223.12656404038353,
  294.12375114559472,
  232.91156342404793,
  295.47345449067143,
  257.78726721379644,
  120.31643951418664,
  188.09106062418141,
  304.38363623449914,
  234.74591789008809,
  196.7056827285287,
  289.91496813827871,
  301.81551370194211,
  357.3900986556655,
  294.43770358731308,
  330.71713836118761,
  394.93507964105629,
  361.16666148737204,
  312.57429390988364,
  231.56745264888377,
  256.83899514772929,
  356.52051225079049,
  223.75854466108285,
  249.98215979820452,
  312.84532527994452,
  224.55807636445206,
  237.41587399399396,
  313.68056339848226,
  310.16000043653366,
  252.4600640687604,
  259.2692736857025,
  351.28674021458573,
  305.02730992144825,
  375.70922414177767,
  336.30423211554262,
  361.20064639332668,
  291.76729354136842,
  423.57323396580432,
  322.35820633315598,
  466.3523123542127,
  382.17321227366847,
  367.76082897313245],
 1: [470.32555993652204,
  440.87753870549568,
  436.40671434958495,
  401.83789404328854,
  340.36150970895142,
  393.01825630078383,
  273.52011378140014,
  288.66868725200038,
  366.27428098465862,
  308.43423352297941,
  341.23339663170918,
  142.7476516502611,
  145.89422957664465,
  172.79746108168911,
  312.96412889957719,
  311.3377493375574,
  205.62433587554915,
  218.88068430145904,
  368.09116726655338,
  181.21011411660947,
  272.36964341025305,
  217.75257480099572,
  325.37916538746504,
  221.808810061857,
  205.90549866639776,
  274.3828882570815,
  305.86794421632294,
  272.31549279186765,
  347.04673177789118,
  328.36449949499729,
  212.67537269387321,
  283.04772918565141,
  249.8405248751078,
  281.8396174248428,
  280.92961138390456,
  332.97269615079676,
  245.75060637827664,
  239.18775975818789,
  275.2387259283114,
  318.52836793565439,
  182.51284301668602,
  311.27308834913856,
  133.51347263634125,
  397.991802867562,
  334.03102731911349,
  388.12692652426267,
  323.04200874069829,
  256.59930437781441,
  302.22719650323234,
  209.22483238039058,
  97.93981947735665,
  380.72728899929461,
  273.52940068177486,
  282.19332280162598,
  243.56502452860332,
  304.01726924200557,
  328.72976467657463,
  293.99655494913532,
  80.404870582035073,
  231.97964310244788,
  225.97469649193408,
  367.10400501443837,
  356.21232810270521,
  342.69235291409677,
  364.97999946489108,
  344.33380693144318,
  418.71087761512717,
  309.56888823928784,
  122.68125703554142,
  378.98029282344214,
  421.88613022600657,
  290.58467401021153,
  217.04359678863329,
  244.13225902266277,
  238.9015854833342,
  253.90127392083195,
  203.92439527325041,
  217.78329857953031,
  290.8395547009859,
  176.20077681058137,
  295.04689264548506,
  184.94952519050821,
  210.29920043252787,
  308.74501589252577,
  239.88254433017937,
  327.68892567779585,
  459.79997361034293,
  245.36854913157549,
  169.88849996373938,
  294.91416651792861,
  233.65970959747392,
  290.10084028978599,
  187.86844654144079,
  203.0691114590154,
  354.15077113572443]}

ne_fep._total_work
Out[14]: 
{0: [29846.019348667283,
  16265.194320478595,
  12046.850052328125,
  13151.854136888925,
  19478.510780720488,
  27086.323319112777,
  28086.364841544215,
  28024.484161788012,
  31662.367796381888,
  33287.47402993271,
  30365.072247886674,
  30429.242484605056,
  30380.60114449199,
  30260.711046819881,
  29444.689141623658,
  29425.724343530637,
  29188.299479014815,
  34183.398654229022,
  36207.298102840752,
  37258.652637189276,
  36344.915823503201,
  39895.342140648456,
  32734.932836541466,
  26820.99780696481,
  23808.708206508934,
  23468.569619670649,
  25761.659578092902,
  27498.866404302233,
  30226.04195514496,
  23377.237908292867,
  26704.512289891729,
  28877.784188685826,
  30019.308429442266,
  24913.621460492574,
  21241.635642308804,
  20801.069758021367,
  20191.731265105958,
  21003.816134595669,
  21483.598903593709,
  17829.625728487223,
  16990.617423092044,
  16580.692764195857,
  18999.943262203058,
  21985.772975905867,
  15629.731074318943,
  13052.723524230942,
  10684.692075474799,
  9814.6197126912521,
  8090.0320725292822,
  7811.7960900692715,
  8306.5157908766596,
  8241.4779655419679,
  8726.9235512125379,
  9004.8056076305147,
  9347.6785080501722,
  10384.324753076675,
  7573.1371825396336,
  5970.5350075021652,
  4981.3211162858524,
  5754.6213293286819,
  5685.7874122865169,
  6288.9744826660581,
  5386.0934889949158,
  6126.1966921305739,
  5724.7255410879088,
  5435.3236618150795,
  5369.9099858162808,
  4749.1362364454417,
  4961.1974453118382,
  4518.2480413961966,
  4893.1997959973096,
  4643.7852952965022,
  4916.0765730859011,
  4910.3323221028122,
  5211.3354585410498,
  5432.5799519671054,
  5815.0048706061943,
  6019.7432557002567,
  6359.1082165882563,
  6614.4423652487349,
  6893.6774840574944,
  6732.5722289772821,
  6801.2620699315394,
  7884.1379466430926,
  7896.5128297587862,
  7860.3465996051773,
  7350.8403072540814,
  5186.8707123966105,
  4967.3206790478998,
  4579.6902287109415,
  5366.7058589047765,
  5590.3088152480977,
  5079.8754245922064,
  4954.9270033990015,
  4915.8072134432914],
 1: [28518.66514331018,
  31810.139749152939,
  28003.113919444713,
  42513.990812230542,
  45163.067727160887,
  59934.79437710296,
  75465.823934938773,
  68477.272346994301,
  18875.542956561676,
  9052.5010569055794,
  6438.8699916893056,
  6236.4994657791121,
  6232.0832204758653,
  6432.1015476465291,
  5918.7490501660805,
  5866.8190167420871,
  5982.8441167516403,
  6705.5610945835242,
  6515.909981564454,
  6772.94798656888,
  6558.0772939882909,
  6503.3784940053829,
  6065.6502822319489,
  5806.2506822213891,
  6254.4995805009266,
  6418.6179050717219,
  6820.9566447306988,
  7540.7482515602906,
  7634.707785497948,
  7437.1418839105763,
  9179.3725806634611,
  7309.2743558928141,
  7133.0379794934643,
  9592.3698187387126,
  7433.0075266054091,
  9292.3626865603565,
  9207.6522110485766,
  6963.0908375401559,
  6432.9033623966216,
  6969.6556958065421,
  8385.6730728262719,
  7566.6788152947438,
  6793.3504134521063,
  6487.6648041568806,
  6915.761842662595,
  7061.0531810505427,
  7289.9587638466282,
  6933.0071239673298,
  6350.8958795775379,
  6638.8820546822344,
  6618.2071360675318,
  6118.6890751150549,
  5980.5451635228583,
  5853.3322420784134,
  7117.2710441342133,
  6746.7637236361552,
  6595.5402089330664,
  6703.5221047307487,
  6189.0076022804387,
  6360.0885604038003,
  6294.1643539195902,
  6318.9391768619171,
  6294.4775628063453,
  7158.144803855751,
  7188.6325568924913,
  7525.65784739643,
  7115.4700930353711,
  6990.7972956625108,
  6604.0156414086587,
  6564.8801910086113,
  6249.438124890964,
  6820.0859240255204,
  6770.9497138713823,
  6771.635641333376,
  5775.0237562119073,
  5773.6832221765962,
  5288.0465790851049,
  4776.2256730608888,
  4730.2935898182559,
  4934.634199626139,
  4361.684315173934,
  4607.706763631184,
  4819.7397836977725,
  4829.8407702956238,
  4772.0224098006356,
  4492.2892888619363,
  4776.0596723509088,
  4907.3129884344935,
  4781.8540367558771,
  4974.3428222889488,
  4938.9157651080814,
  5016.3629265360105,
  5063.5039960815184,
  5253.5810731865758,
  5685.9753376185699]}
```

**Comment by jchodera** [comment]
Thanks, @brycestx!

Can you give some info about the protocol you used here? Was it just 100 steps?

A quick check of a plot or two suggests this looks like what we expect now:
![image](https://user-images.githubusercontent.com/3656088/34010298-2e9a5128-e0da-11e7-9bff-f045b3cb9f47.png)

The major thing to play with is presumably the trajectory length. I expect we need 20-100 ps NCMC trajectories to get good work curves.

**Comment by brycestx** [comment]
@jchodera yes, 
currently the df0 calculated from the lambda 0 endpoint is: -10504.853731358771 kT
df1 calculated from lambda 1 endpoint: 84.904680228117755 kT
and df from the nonequilibrium simulation: 78.281863111131315 kT
Therefore the total dG I get for this solvated perturbation is 10668.04027469802 kT.
Forward and reverse reduced potential differences and cumulative work after each iteration are shown below. Notice that iteration 11 of the forward (0) reducted potential differences is an outlier. After looking at that trajectory traj.11.neq.lambda0.h5 I no movement throughout the frames. I am looking into why this may be happening

**Comment by brycestx** [comment]
@jchodera for the protocol I equilibrated using 100 iterations of 1000 equilibrium steps at both endpoints. I then did 100 iterations of the full nonequilbrium protocol which was performed using the default values.

**Comment by brycestx** [comment]
After looking at more trajectories it looks like lambda0 trajectories 11-17 all have some issues, with some not moving at all, and others looking like they are resetting. @pgrinaway could this be because they are hitting NaNs?

**Comment by brycestx** [comment]
> From the size of the final work values, this number will currently be totally unreliable. Is the code not currently reporting the uncertainty in all of these free energies? They would be much larger than the actual values.

@jchodera Yes your right I agree. The uncertainty estimates were returned but were NaN for the nonequilibrium BAR estimate. 

> The most useful thing to do right now is to focus on exploring the shape of the per-step work traces as we increase the number of nonequilibrium switching protocols from 10^2 to 10^6 steps. You only need to run a few switching trajectories for each one (<10) to get a feel for how the work curves are behaving.

I have increased the protocol to `ncmc_nsteps=20000` and `nsteps_per_iteration=2000` and am running the longer simulation now. I will update when it finishes.

**Comment by brycestx** [comment]
@jchodera @pgrinaway Attached are the solvated and complex trajectory and work traces with the new Nonequilibrium protocol where I ran `ncmc_nsteps=20000`. The results look much improved:
Solvated dG: -62.708445205518913 +- 1.4829590691230017 kT
Complex dG: 114.35809515307665 +- 1.5529255362118615 kT
However as you can see the ddG is way off. I am now running a new protocol with `ncmc_nsteps=50000` to see if this improves the relative binding free energy estimate.
[14~15-CDK2-solvated-121417.zip](https://github.com/choderalab/perses/files/1564846/14.15-CDK2-solvated-121417.zip)
https://drive.google.com/open?id=1Ks7eodj2MN3O8X6r69zHMcoMd3LX7Iqn

**Comment by jchodera** [comment]
Thanks, @brycestx!

These new `.npy` work trajectories only seem to have one sample in them, but data for 100 trajectories is available. Right now, I think we mostly need data where we store the work for *every* timestep, but only need a few trajectories (<10) for different total NCMC trajectory lengths out to 100,000 steps. 

If we don't yet have a harness to generate this data, I can put something together.

**Comment by jchodera** [comment]
Here's a kdeplot of the work distributions you're seeing (presuming the work is indeed in kT):
![image](https://user-images.githubusercontent.com/3656088/34074285-de2016fa-e279-11e7-8675-bb19bb221ca1.png)
Looks pretty close to working! I think we'll just need longer protocols.

**Comment by brycestx** [comment]
@jchodera attached are solvated and complex results for 10 trajectories of 10k steps where cumulative work is reported every 1k steps. Currently, it looks like saving work for every timestep without saving a frame every timestep isn't possible, but I could modify the function to allow for this capability if necessary.

[14~15-CDK2-solvent-121917.zip](https://github.com/choderalab/perses/files/1602001/14.15-CDK2-solvent-121917.zip)
https://drive.google.com/file/d/1hhInHg_uwZtqz1zDVBtZ9vE6rYPVLWRD/view?usp=sharing

**Comment by brycestx** [comment]
@jchodera @pgrinaway 
![14 15-cdk2-complex-forward-122917](https://user-images.githubusercontent.com/31014151/34545952-a5edae02-f0be-11e7-835a-b8083a8a226f.png)
![14 15-cdk2-complex-reverse-122917](https://user-images.githubusercontent.com/31014151/34545966-b58bf2ce-f0be-11e7-9286-020d7b6ee180.png)
Here are the cumulative work traces for every step for 10k step protocols. The reverse protocol looks like the main source of error.

**Comment by jchodera** [comment]
Thanks! Taking a look now.

For the "cumulative work traces", are you just plotting one trace, or many traces superimposed? I think we want to look at how different the 10 trajectories are. The overall cumulative work isn't important here---just the size of the stddev of the cumulative work traces as a function of step.

**Comment by jchodera** [comment]
Here's a quick analysis of the trajectories in the ZIP file:
![image](https://user-images.githubusercontent.com/3656088/34546878-d751f65a-f0ab-11e7-82fc-ac12b2204508.png)
![image](https://user-images.githubusercontent.com/3656088/34546904-f6f124a4-f0ab-11e7-85f1-76553d551125.png)
It looks like there is still significant width to the work distributions. 100K steps is 100 ps for 1 fs timesteps, so we may have to try out to 1 ns switches.

@pgrinaway : We should also try gently restraining the protein heavy atoms using the same scheme we use in YANK. I believe there is also a utility function in [`openmmtools`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/forcefactories.py#L85-L174) to help with this, though care must still be taken as to how the protein is centered if the barostat is in use.

**Comment by jchodera** [comment]
Overall, the shape of the trances looks really good and free of artifacts, though.

**Comment by pgrinaway** [comment]
Closing this because there doesn't seem to still be an issue here.
