### ISSUE TITLE
Bad hydrogen placement results in ridiculous number of atoms

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#455]
@brycestx found evidence that the protein ends up getting duplicated in the atom map. I'm going to investigate this issue.

**Comment by brycestx** [comment]
It looks like the issue was due to solvation, where over 200k waters were added. This is fixed by uncommenting out 
```
        #modeller.delete(hs)
        #modeller.addHydrogens(forcefield=self._forcefield)
``` 
in [relative_setup.py](https://github.com/choderalab/perses/blob/master/perses/dispersed/relative_setup.py#L216)

**Comment by pgrinaway** [comment]
Ah, the bad hydrogen placement issue again.

**Comment by pgrinaway** [comment]
We should come up with a minimal example to post on OpenMM issue tracker.

**Comment by jchodera** [comment]
Closing due to lack of concrete test case.
