### ISSUE TITLE
Allow electrostics and van der Waals decoupling

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#464]
Right now, we have to change electrostatics and van der Waals simultaneously. We'd like to be able to decouple electrostatics, change van der Waals, and then recouple electrostatics. The change that this would require to the hybrid code would be to add another global parameter, such as `electrostatics_mask`, that would attenuate all custom electrostatics interactions. By default, it could be set at 1 so that current behavior is preserved. cc: @jchodera @brycestx 

To be clear, the desired capability is to have protocols like this:
1. For the first part of the protocol, gradually scale down electrostatics of molecule A
2. For the second part, transform van der Waals from molecule A to molecule B
3. Finally, scale up electrostatics for molecule B

**Comment by jchodera** [comment]
How time-critical is this? Could we do it [after the `HybridTopologyFactory` migration to `openmmtools`](https://github.com/choderalab/openmmtools/pull/339) is completed?

If we want to evaluate these approaches, we can likely ask for help from @mrshirts or @davidlmobley to do a quick benchmark calculation with gromacs to evaluate relative thermodynamic lengths.

**Comment by pgrinaway** [comment]
Doing it after the hybrid topology migration is fine, so I don't think we need to rush. We just wanted to raise the issue, since it would be a good feature to have.

**Comment by pgrinaway** [comment]
This is already implemented now in #486
