### ISSUE TITLE
Deal with reciprocal space PME

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#468]
Right now, we don't capture the reciprocal space in the `CustomNonbondedForce`. We have a couple workarounds:

- `CustomCVForce` interpolating between `NonbondedForce`s for electrostatics of each endpoint, as well as a `NonbondedForce` for environment interactions.
    - Pros: somewhat simple to implement
    - Cons: very large number of exceptions (is this a problem?). Either we have to exclude all the environment-environment atoms in the endpoint `NonbondedForces`, or we have to use exceptions to _include_ all the `environment-core` and `core-core` interactions.

- `CustomCVForce` interpolating between two `NonbondedForce`s for electrostatics, including the environment interactions.
    - Pros: fewer exceptions (I think)
    - Cons: It turns out to require a pretty substantial change to the way the `HybridTopology` is set up.

Thoughts? @jchodera @brycestx

**Comment by jchodera** [comment]
What do you mean by "environment interactions" here? Lennard-Jones interactions, or electrostatics? And do you just mean "all interactions that don't involve the alchemical region"?

If electrostatics, remember that PME must include *all* the electrostatics so that a uniform background charge is not used. I'm not certain that splitting out environment electrostatics (if the environment carries a net charge) would have an effect that *exactly* cancels with the alchemical region interactions with the opposite net charge.

**Comment by pgrinaway** [comment]
Oh, sorry, looks like I didn't post this response:

Sorry, by environment interactions I mean "all interactions that don't involve the alchemical region." That's what I named it in the code + docs. And I was only referring to electrostatics.

>If electrostatics, remember that PME must include all the electrostatics so that a uniform background charge is not used. I'm not certain that splitting out environment electrostatics (if the environment carries a net charge) would have an effect that exactly cancels with the alchemical region interactions with the opposite net charge.

So you're saying I _can't_ have 3 `NonbondedForce` objects, one for alchemical system A, another for alchemical system B, and a third for environment (defined above). 

Instead, the only way to address this is to have two `NonbondedForce` objects with electrostatics only for everything + sterics for the environment (again as defined above), with alchemical sterics handled by a now-lone `CustomNonbondedForce`?

**Comment by jchodera** [comment]
> So you're saying I can't have 3 NonbondedForce objects, one for alchemical system A, another for alchemical system B, and a third for environment (defined above).
> Instead, the only way to address this is to have two NonbondedForce objects with electrostatics only for everything + sterics for the environment (again as defined above), with alchemical sterics handled by a now-lone CustomNonbondedForce?

Yes. You can't split up PME this way because it is not pairwise.

**Comment by pgrinaway** [comment]
Ok, thanks.

**Comment by jchodera** [comment]
> Instead, the only way to address this is to have two NonbondedForce objects with electrostatics only for everything + sterics for the environment (again as defined above)

To be pedantic, the two PME `NonbondedForce` objects representing states A and B would only be fed to a `CustomCVForce`, not added to the `System`.

**Comment by brycestx** [comment]
I have tried running a system from mcl1 with the [exact-pme-relative](https://github.com/choderalab/perses/pull/469) #469 branch and I get nan's in the minimization/equilibration stage. This is using the [latest dev build of openmm 7.3.2](https://anaconda.org/omnia/openmm/7.3.2/download/linux-64/openmm-7.3.2-py36_0.tar.bz2). Attached are the `nan-error-logs` including the serialized integrators, states and systems from both the complex and solvent stages. Lambda was set to 0.0. I am currently debugging and will update with anything I find.

[mcl1_26~44_nan_error_logs.tar.gz](https://github.com/choderalab/perses/files/2109774/mcl1_26.44_nan_error_logs.tar.gz)

**Comment by jchodera** [comment]
I'm not sure this branch has even been tested yet, so I'd hold off until @pgrinaway finishes and tests the implementation.

**Comment by jchodera** [comment]
Please do test the 7.3.2 OpenMM build for benchmarking, though! It's built for CUDA 9.2.

**Comment by pgrinaway** [comment]
This was resolved by #472 #477 and friends.
