### ISSUE TITLE
Nonequilibrium switching driver no longer works

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#475]
The nonequilibrium switching driver relies on the ability to serialize systems, which was lost with the new additions to OpenMM. As @jchodera notes:

>OpenMM neglected to add XML serialization support, so debugging the NaN will be difficult until this is added.

>Also, I wonder if this is the cause of your error, @pgrinaway : If you run the simulation directly after creating it, it runs, but if you create the NetCDF files containing a serialized System and then try to resume, you get an error stating there is no lambda_electrostatics context parameter.

>cc: pandegroup/openmm#2114

**Comment by jchodera** [comment]
Was this addressed by https://github.com/pandegroup/openmm/pull/2115 ?

**Comment by pgrinaway** [comment]
Yes.
