### ISSUE TITLE
Nonequilibrium switching fails with new OpenMM API

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#476]
I think this is actually an update that needs to be made in openmmtools. The `AlchemicalState` object is unaware of how to set the global parameter `lambda_electrostatics` if it's covered by the regular `NonbondedForce`. 

cc: https://github.com/choderalab/openmmtools/issues/359

**Comment by jchodera** [comment]
@pgrinaway This should be resolved using the latest OpenMM 7.3.0 `dev` build now that https://github.com/pandegroup/openmm/pull/2119 and https://github.com/pandegroup/openmm/pull/2115 have been merged.

OK to close?

**Comment by jchodera** [comment]
@brycestx points out we need to revise things so that we explicitly add the global context parameters to `NonbondedForce` now that the API has been extended.

**Comment by pgrinaway** [comment]
Actually, it's pretty unstable now for nonequilibrium switching. Even with 0.5fs I get frequent NaNs. Will investigate further.

**Comment by jchodera** [comment]
Fixed in the [OpenMM 7.3.1 bugfix release](https://github.com/pandegroup/openmm/releases/tag/7.3.1).
