### ISSUE TITLE
Remove oechem dependency

### ISSUE THREAD

**Issue by abradle** [choderalab/perses#478]
Similar to Yank - it would be great if it's possible to run using RDKit and not OEChem - and I think that should be possible - but looks like it would take a fair bit of refactoring to carry out.

I'm wondering where that is on the road map?

**Comment by jchodera** [comment]
This is definitely on our radar. My strategy here is to wait until the next major release of the [openforcefield toolkit](http://github.com/openforcefield/openforcefield) where we are creating a common interface to the OEChem and RDKit functionality we need, which will allow us to plug in and use whichever cheminformatics toolkits we have available.

**Comment by pgrinaway** [comment]
In the medium term, there is another issue open for this (#342) with some information about what would need to be replaced to use RDKit. Contributions are welcome! I'm going to close this issue since it's a duplicate, but as John mentioned, it's definitely on the radar.
