### ISSUE TITLE
Discussion of weight adaptation and sampling schemes

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#48]
Creating a thread to discuss weight adaptation and sampling schemes we should explore and the order in which we should explore them.

**Comment by jchodera** [comment]
As discussed in #31, I still think we want a hierarchy of driver classes, breaking them into those that use MCMC and those that do something different (like use Bayesian Bandits strategies):
```
Sampler (base class)
   + MCMCSampler
      + AdaptiveWeightSampler
      + FixedWeightSampler
   + BayesianBanditsSampler
      + ThompsonSampler
      + (other strategies)
```
We will want to explore a few strategies for the `AdaptiveWeightSampler` based on the [Zhiqiang Tan paper](http://www.stat.rutgers.edu/home/ztan/Publication/SAMS_redo4.pdf) that utilizes stochastic approximation (SA) theory.

If we did instantaneous switching *without* transdimensional RJMC jumps, we could use all three methods Zhiqiang Tan proposed in that paper for adjusting weights:
* Histogram counts [Eq. 9]
* Rao-Blackwellized form [Eq. 12]
* Local update [Eq. 14]

If we use RJMC for instantaneous trandimensional jumps, however, we have a problem in that we can no longer compute the weights in other states in the same way as the paper since these weights do not include the RJMC proposal probability ratios, in principle limiting us to histogram counts [Eq. 9] only.  However, I believe we can straightforwardly modify the theory to include the proposal probability ratios and once again allow us to use all three schemes if we use parallel Monte Carlo to propose multiple different molecules each iteration.

When using NCMC-RJMC switching, however, we are once again limited to histogram counts because we do not know the acceptance probability for moves not yet proposed.  We can once again use parallel Monte Carlo to propose multiple chemical species changes at once (requiring we integrate all of these trajectories).

We don't yet know, however, how much more efficient the Rao-Blackwellized form [Eq. 12] or the local update form [Eq. 14] are over the simple histogram count form.  As a result, we may want to adopt the simplest approach---the histogram counts---that easily works for all of these methods and brainstorm the simplest way to implement parallel Monte Carlo schemes in the future to allow us to handle all of the other forms.

**Comment by jchodera** [comment]
For specific problem classes, we have different optimization needs:

### Optimizing lead compound affinity

To increase affinity, we want to maximize Z_{ligand_k in complex} / Z_{ligand_k in solvent}.

We have several strategies we could adopt:
#### Two-stage: Hydration free energies then optimization of binding affinity

We can compute all the hydration free energies first using one of the `AdaptiveWeightSampler` SAMS schemes, and then feed these hydration free energies into a `FixedWeightSampler` simulation.  While the correlation times are generally short for small molecules in solvent, the efficiency of this approach gets worse as the number of molecules in the design space increases.

#### Simultaneous optimization

@maxentile and I have recently demonstrated that [adding an additional recursion step](https://github.com/choderalab/perses/blob/master/notebooks/Harmonic%20oscillators%20example.ipynb) in which the target log-populations are updated according to the current estimates of log normalizing constants, and running *two* coupled MCMC chains at once, appears to lead to the desired free energy estimates.  Zhiqiang Tan thinks the validity of this approach can be proven in the SA framework.

While it is a bit trickier (since we need to couple together two chains that produce samples at different rates), this method should scale much better with the size of the design space.  Note that the complex and solvent chains are free to sample different ligands, but the coupling occurs through the updated target probabilities \pi_k (which should be represented in log form for numerical stability), were we want

\pi_k \propto Z_{ligand_k in complex} / Z_{ligand_k in solvent}.

I think this is the approach we should prioritize.

## Dual-targeted inhibitors

If we want to design a ligand that binds well to two different proteins, we want to maximize

Z_{ligand_k in complex1} Z_{ligand_k in complex2} / Z_{ligand_k in solvent}

### Two-stage approach

To do this, we could once again precompute all ligand free energies in solvent using SASA and then feed these into a dual-coupled-chain simulation where we simulate complex1 and complex2 and couple together ligand transitions, so that the same ligand is always in both complexes.

### Simultaneous optimization

Once again, we can instead couple together all three chains (complex1, complex2, and solvent) where we let each chain visit a different ligand but couple them at the level of the desired target distribution \pi_k, where we want

\pi_k \propto Z_{ligand_k in complex1} Z_{ligand_k in complex2} / Z_{ligand_k in solvent}

## Target/antitarget approaches

If we want to bind a target (complex1) but avoid a different antitarget (complex2), we want to maximize 

Z_{ligand_k in complex1} / Z_{ligand_k in complex2} 

### Two-stage approach

In order to execute the two-stage approach, we first have to compute the relative Z_{ligand_k in complex2} for *all* ligands, which is computationally very demanding even with SAMS.

### Simultaneous optimization

Here is where the simultaneous optimization will really shine.  We can again couple together two independent chains where update the target probability \pi_k with

\pi_k \propto Z_{ligand_k in complex1} / Z_{ligand_k in complex2} 

## Identification of resistance mutations

In this case, we sample over proteins to maximize the resistance index

R_k = Z_{substrate in complex_k} / Z_{inhibitor in complex_k} 

### Bayesian Bandits approach

We have discussed this at length elsewhere.

### Two-stage approach

The two-stage approach would require we first use SAMS to compute all the relative Z_{inhibitor in complex_k}, then feed these weights into a `FixedWeightSampler`.

### Simultaneous optimization

We again couple together two independent chains (substrate in complex_k; inhibitor in complex_k) and add the recursion step for \pi_k such that

\pi_k \propto R_k = Z_{substrate in complex_k} / Z_{inhibitor in complex_k} 

## HMC:peptide:TCR

For this problem, we are given a very large list of peptide sequences and need to either
* (1) compute all binding affinities
* (2) identify the peptides that bind best
* (3) identify the peptides that bind worst

The relative binding affinity among peptide sequences k can be related to

affinity_k \propto Z_{peptide_k in ternary complex} / Z_{peptide_k in solvent}

In all three cases, I think we want to use the simultaneous optimzation scheme with different target \pi_k:
* (1) \pi_k \propto 1
* (2) \pi_k \propto Z_{peptide_k in ternary complex} / Z_{peptide_k in solvent}
* (3) \pi_k \propto  Z_{peptide_k in solvent} / Z_{peptide_k in ternary complex}

I think there are also more elaborate versions of the problem where we optimize an TCR-mimic that has both a positive design (maximize the binding of some peptides) and negative design (minimize the binding of endogenous peptides) component.  All of these are made easier by the simultaneous optimization strategy.

**Comment by pgrinaway** [comment]
Closing for now. We can revisit the topic later, but trying to avoid issue clutter.
