### ISSUE TITLE
GeometryEngine sometimes produces bad proposals

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#493]
Sometimes, especially for large transformations introducing rings, the `GeometryEngine` produces configurations that are sufficiently unfavorable that the acceptance probability is very poor. There are several way to solve this:

* In the `GeometryEngine`: introduce resampling to eliminate unfavorable configurations. This has the advantage of eliminating the problem where it occurs, but the disadvantage of being rather complicated to implement efficiently (the code that is currently there takes much longer to make a proposal than the old `GeometryEngine`)

* In the `NCMCEngine`: allow new bonds and angles to be softened in order to resolve poor initial configurations with nonequilibrium switching. This has the advantage of being simple to implement as well as able to take advantage of the GPU. On the other hand, we might need to think a bit more about what protocol to use.

These are just initial thoughts--I'm opening this issue to discuss. cc: @jchodera @ivyzhang999

**Comment by hannahbrucemacdonald** [comment]
I think this has been fixed?
