### ISSUE TITLE
Use HMR for vacuum simulations too?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#502]
We should probably set `hydrogenMass` to `4*amu` for vacuum simulations [here](https://github.com/choderalab/perses/blob/master/perses/dispersed/relative_setup.py#L193) since we use it for simulations with a barostat [here](https://github.com/choderalab/perses/blob/master/perses/dispersed/relative_setup.py#L191).

**Comment by hannahbrucemacdonald** [comment]
This is the default now
