### ISSUE TITLE
Analytical GeometryEngine tests

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#506]
In order to dissect the issues in the `GeometryEngine`, we are building simple test systems to examine where the problem (low effective sample size even for simple systems) is coming from:

* 3 -> 4 particle system
* 4 -> 5 particle system with branch
* 3 -> 5 particle system with branch.

**Comment by jchodera** [comment]
This is happening in the analytical-systems branch

**Comment by dominicrufa** [comment]
in the transition from 3-to-4 beads, there are two cases: 
0.  default_dihedral_constant=0 
1.  default_dihedral_constant=1. 

three trials were performed  for each case

in case 1, work:  [2.3700983008784684, 2.370098300878454, 2.3700983008784577]
whereas in case 2: work:  [2.737372156416331, 2.7351245632994834, 2.735033893972514] (larger variance)

**Comment by jchodera** [comment]
@dominicrufa has implemented these in #513.

**Comment by hannahbrucemacdonald** [comment]
@dominicrufa wrote lots of tests for geometry.py and it’s the best covered file in the repo, so going to close
