### ISSUE TITLE
Fix NoTorsionError

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#508]
Sometimes, the current method of selecting a proposal order results in running out of torsions. I have an alternative scheme based on networkx for choosing the proposal order that at least should be easier to analyze.

**Comment by jchodera** [comment]
@pgrinaway : Where is your alternative scheme hiding?

**Comment by jchodera** [comment]
@pgrinaway : Is it in [this branch](https://github.com/choderalab/perses/commits/pf-geometry), added in [this commit](https://github.com/choderalab/perses/commit/388d0a700f0c516cf4efb956ecacf09ac16d35bc)?

**Comment by pgrinaway** [comment]
Yes, it's [here](https://github.com/choderalab/perses/blob/pf-geometry/perses/rjmc/geometry.py#L2248-L2410). Sorry about the delay. You can ignore the rest of that branch (perhaps just copy/paste the code), since it's mostly trying to resurrect the full particle filter. Alternatively you can cherry pick that commit.

**Comment by jchodera** [comment]
Fixed in #517 (by bringing in the NetworkX proposal order code from @pgrinaway).
