### ISSUE TITLE
Fix `HybridSAMSSampler` so that it can be resumed/used transparently with the other `yank` analysis tools

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#510]
Right now, the [`HybridSAMSSampler`](https://github.com/choderalab/perses/blob/99cfe0ffab1de5101f8d1331ec2ef35c0977865a/perses/dispersed/relative_setup.py#L873) simulations can't be resumed, and some analysis tools might not work properly. We should ensure that perses-lite and yank can share the same analysis toolchain.

**Comment by hannahbrucemacdonald** [comment]
This has been done - it’s in the multistate directory
