### ISSUE TITLE
Rework host-guest example

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#512]
The host-guest example in [`examples/host-guest`](https://github.com/choderalab/perses/tree/master/examples/host-guest) starts with a PDB file (which lacks chemical information about bonds) and extracts the host and guest molecules separately, producing Tripos mol2 files absent charges.

Instead, we can use pre-prepared `mol2` files from [SAMPL6](https://www.biorxiv.org/content/biorxiv/early/2018/09/25/371724.full.pdf) from @andrrizzi : 
> The mol2 files for CB8 and OA/TEMOA guests should be charged here:
> - https://github.com/MobleyLab/SAMPL6/tree/master/host_guest/CB8AndGuests
> - https://github.com/MobleyLab/SAMPL6/tree/master/host_guest/OctaAcidsAndGuests (edited) 
> 
> I also used the YANK pipeline to generate OpenEye charges for the hosts. They are currently on the cluster here: `/home/andrrizzi/SAMPL6/setup_scripts/SAMPL/setup/molecules`

For example, the CB8:adamantane derivatives may be a good choice.

**Comment by jchodera** [comment]
This repo may also be useful!

https://github.com/MobleyLab/benchmarksets/blob/master/input_files/cd-set2/mol2/host-bcd.mol2

As would the zip files in the SI of this paper:

https://pubs.acs.org/doi/10.1021/acs.jctc.5b00405

**Comment by jchodera** [comment]
I think @hannahbrucemacdonald has been working on adding this test.

@hannahbrucemacdonald : Can you open a PR for this?

**Comment by hannahbrucemacdonald** [comment]
This is tied up in the `fixing-lambda` PR. Would you like me to separate it out?

**Comment by jchodera** [comment]
No need! We'll just note:

Addressed by #504
