### ISSUE TITLE
Fix issues with nonequilibrium integrator

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#523]
We can likely simplify [`NonequilibriumSwitchingMove`](https://github.com/choderalab/perses/blob/master/perses/dispersed/feptasks.py#L231) once we address the `reset()` issue in https://github.com/choderalab/openmmtools/pull/274

I'm just creating this issue so I don't forget about it.

**Comment by hannahbrucemacdonald** [comment]
I think this has been addressed by @dominicrufa

**Comment by jchodera** [comment]
@dominicrufa : Can you point to your code fix or PR in which this was addressed?

I think we still need to fix the original issue in `openmmtools`, but it may have been worked around here.

**Comment by dominicrufa** [comment]
https://github.com/choderalab/perses/blob/352e5cde82b464f8e8847d2f9e42349e58bc600d/perses/dispersed/feptasks.py#L172

**Comment by hannahbrucemacdonald** [comment]
This is closed, right?

Can one of you two close if you're happy please?

**Comment by dominicrufa** [comment]
yep.
