### ISSUE TITLE
Using non-alchemical endstates with SAMS causes silent errors 

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#542]
Using non-alchemical endstates causes issues with `openmmtools/multistate/sams.py` which results in offline free energies of `[--, --]`. 

non-alchemical endstates results in n+2 states, while sams is expecting n. This throws an error that is caught by https://github.com/choderalab/openmmtools/blob/e97cb814780586e80b9421042f2bd5e0ebaa20c6/openmmtools/multistate/multistatesampler.py#L1433

I have removed the non-alchemical endstates in the perses `refactoring` branch

**Comment by hannahbrucemacdonald** [comment]
These need to be re-implemented such as to capture the respective dispersion correction contribution for the two end states when running `perses-lite`

**Comment by jchodera** [comment]
This was fixed!
