### ISSUE TITLE
Charges not generated in relative simulation when both ligands are planar

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#543]
>>> warning: OEAM1BCCCharges: mol MOL does not appear to be 3D as required.
warning: OEAM1BCCCharges: mol NEW does not appear to be 3D as required.

Above warning is thrown when both ligands are planar and recognised as 2D by OEMols when parameterizing the small molecules at this line here: 

https://github.com/choderalab/perses/blob/61c2fc1900a64cfcb186776b14d571f0de5ae724/perses/app/relative_setup.py#L112

This results in the system being generated where all of the charges are set to zero.

Phenol is not treated as planar, as it has two Carom - Carom - O - H torsions, which aren't present in thiophenol or benzene.

It is also only an issue if _both_ the ligands are viewed as planar, rather than just one.

**Comment by jchodera** [comment]
To clarify---the ligand pair `['thiophenol', 'benzene']` should show this problem, right?

**Comment by hannahbrucemacdonald** [comment]
Yes, when being set up using `relative_setup.py`

**Comment by hannahbrucemacdonald** [comment]
1) update to OEAssignCharges
2) Call omega if the charging fails (and then charge again)
3) make sure we are using ELF1 charges

**Comment by hannahbrucemacdonald** [comment]
And fall back to AM1 if that fails too...

**Comment by hannahbrucemacdonald** [comment]
Addressing this here: https://github.com/choderalab/openmoltools/pull/290

**Comment by jchodera** [comment]
Fixed by calling generateconformers first.
