### ISSUE TITLE
Geometry Engine refactor

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#55]
I thought I would start a discussion here first. I'm not suggesting that all of this needs to be implemented in the next PR (it's a lot), but I wanted to get some ideas.

# Unit Tests
This has been pointed out, but the entire code needs a lot more testing. In particular:

* it would be good to have each method tested separately, in addition to the test of the entire `GeometryEngine`.

* A full suite of tests would also provide a target for test-driven development of new components of the `GeometryEngine` (and actually `perses` in general--especially since we'll need a different components for different sampling strategies).

* Perhaps adding a service such as coveralls or landscape.io can help with making sure that we are writing code that is sufficiently tested.

# Python 3 support

* We want to make sure that all components support Python 3
* Adding type [hints](https://www.python.org/dev/peps/pep-0484/) can be helpful, especially if we use a static type checker to verify that our functions are dealing with the types we expect.

# The Architecture of the Geometry Engine

From our discussions and experience so far, it seems there are three (conceptual). parts of the Geometry Engine:

## The calculation of potentials and making proposals.
This component is responsible for calculating potentials associated with bonds, angles, and torsions, and also proposes them (there might be a clever way of separating potential calculation and proposal to make things cleaner/more modular, but I'm not sure). We definitely want to include impropers, as well as potentially other terms (if we use OpenMM to calculate potentials).

* Is it cleaner to separate proposal and potential calculation? (long term question)
    * They are intimately related, which might make this a bad idea
    * We may want to use different backends for the potential, such as OpenMM or our own code.
* Should we implement the impropers in the Python code, or should we outsource to OpenMM?

## Retrieving parameters and topology information
This component is responsible for:
* Deciding the order of atom proposal
* Deciding which atoms can be used for proposal
* Extracting parameters relevant to the proposal

By not having this part separate and modular, we risk:
* Multiple sites of computation of forcefield parameters (potential for errors)
* Duplication of code (both `logp_reverse` and `propose` need it)
* More difficult-to-read code

## The conversion of coordinates between internal and cartesian
I think this code should be separate (most of it is right now) for several reasons:
* We want to test it separately
* It might be useful to others
* We might consider writing higher-performance versions of it, since it seems to be the bottleneck.

These are some initial thoughts. Eventually, unless there is disagreement, I think we want to implement most if not all of that. However, we should prioritize. To me, it seems:

1. Unit tests
2. Python 3 support
3. Refactor/cleanup (this is large, and some of it can go in the first PR, but I'm not exactly sure how to prioritize it at the moment)

Thoughts? Sorry for the massive issue, but I think discussing the next steps could be helpful. 

Thanks everyone!

**Comment by jchodera** [comment]
The priorities sound good to me!

Some specific thoughts:

### Using OpenMM for proposal energies
I do think we want to move toward an OpenMM-based energy computation scheme for proposals in a future refactoring.  I think we should still propose one atom at a time, using the same sequence of `r`, `theta`, and `phi` proposals, with only the `phi` proposal taking into account the energy around the torsion drive.  We could tinker with which potential terms are harvested for use in the new `System` object used for this purpose, and this could even include some very local Lennard-Jones interactions that will be useful when we are inserting atoms in close proximity to other atoms in a binding site.

### Ring creation
For now, it would be useful if there was a way to include improper torsions in the energy evaluation through simple modifications to existing code.  Simple tests with `benzene >> biphenyl` and `benzene >> napthalene` would tell us about whether we might need a more sophisticated strategy for creating rings that will inform future refactoring.

### ParmEd
The lack of units in ParmEd makes me think we should avoid it altogether and simply use a reference OpenMM `System` object and then make use of units consistently throughout our code to avoid bugs.  Alternatively, @swails may let us create a special `OpenMMStructure` or add an argument where everything is automagically converted to OpenMM-compatible unit-bearing quantities, which would save us the hellish nightmare that was the last two weeks of debugging.

**Comment by pgrinaway** [comment]
Thanks for the comments!

>I do think we want to move toward an OpenMM-based energy computation scheme for proposals in a future refactoring

I agree. It avoids reinventing the energy computation wheel, and will probably be faster. I'll open another issue on that.

>I think we should still propose one atom at a time

Agreed. I think it's going to be pretty difficult to get a joint proposal that is also normalized, and for the moment if we can do well with one-at-a-time proposals (it seems like we can), then let's stick with that.

>For now, it would be useful if there was a way to include improper torsions in the energy evaluation through simple modifications to existing code

I agree it would be good to prioritize this addition. I think this will be in the next PR, along with unit tests.

>The lack of units in ParmEd makes me think we should avoid it altogether and simply use a reference OpenMM System object and then make use of units consistently throughout our code to avoid bugs. 

Yeah, this was a major source of problems. I had thought about subclassing `Structure` as well, to ensure that we always have the right units on things. Either way, we definitely need to ensure we have consistent units everywhere.Finally, I'm not sure what the future support plans for ParmEd are, either. Perhaps we can subclass `System`?

**Comment by swails** [comment]
I would be open to adjusting the classes in `topologyobjects` to bear units instead of using raw numbers, but this is potentially a big job.

The only reason it *wasn't* unit-bearing already is because units were added to ParmEd well after the rest of the infrastructure was in place.  At a minimum, all of the attributes would need to be turned into descriptors so that the appropriate units are handled.  I'm a little worried about the performance effect of using dimensional analysis everywhere, but I can probably circumvent a lot of that by using the `_value` attribute directly (as long as the descriptors always put it in the AKMA unit system).  This should hopefully be the best of both worlds.  What do you think?

**Comment by jchodera** [comment]
Thanks for the explanation, @swails!

This proposal sounds totally sound, but as you noted, possibly a big job.  Would it be better to do this, or simply have derived `OpenMMStructure` and `OpenMMParameterSet` subclasses that (optionally) append units and convert to OpenMM-compatible force constants?

**Comment by swails** [comment]
`Structure` isn't what needs to be unit-bearing.  It's the stuff in `topologyobjects`, like `BondType`, and `AngleType`, ... etc.  And subclassing there isn't really going to help.  If you wanted to do it externally from ParmEd, the only real approach I can think of is to monkey-patch in the changes, and that has the almost assured side-effect of breaking ParmEd completely :).

Best would be to see if ParmEd can be switched to using units internally.  This may be painful API churn, though, as floats and Quantities behave very differently in many respects (and not *everything* will be a `Quantity` -- like torsion periodicity which is just a number).

**Comment by swails** [comment]
Another option is to go all Hungarian notation and add properties `u<paramname>` where the `u` indicates attached units.  So the `BondType` API would go from

```Python
>>> bt = BondType(100.0, 1.0)
>>> bt.k
100.0
>>> bt.req
1.0
>>> bt.uk
Quantity(value=100, unit=angstrom**2*kilocalorie/mole)
>>> bt.ureq
Quantity(value=1.0, unit=angstrom)
```

It adds complexity to the API, but the Hungarian notation should help reduce cognitive load and the extension (rather than replacement) should eliminate API churn.  What do you think of that proposal?

**Comment by swails** [comment]
Note this won't eliminate the factor-of-2 issue in the harmonic energy terms (Amber and CHARMM fold them into the force constant, OpenMM and GROMACS do not, and ParmEd behaves as Amber/CHARMM do).

**Comment by jchodera** [comment]
@pgrinaway: If we are switching to OpenMM for energy calculation during torsion scans, can we build a factory that takes as input:
* System
* list of atoms to include interactions for
* options

The options could specify information about which forces are to be included as well as whether some options (like LJ cutoff) should be overriden.

**Comment by swails** [comment]
@jchodera and @pgrinaway -- what do you think about my latest proposal for making units available on the various attributes of the ParameterType classes?

**Comment by jchodera** [comment]
@swails: OK if we migrate parmed discussion to the parmed issue tracker?

**Comment by swails** [comment]
Please :)

**Comment by pgrinaway** [comment]
Completed in #127 , if there are other issues we can raise them.
