### ISSUE TITLE
System factory for torsion proposals

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#57]
If you need some reference code on how to construct a `System` factory for torsion proposals, you can start with [this old version of `alchemy.py`](https://github.com/choderalab/yank/blob/4ee3a26f920ff67e50a2142c1b7cef0577b1d89f/Yank/alchemy.py#L765-L800
), which would be something like this:
```python
        # Create new deep copy reference system to modify.
        system = openmm.System()

        # Set periodic box vectors.
        [a,b,c] = reference_system.getDefaultPeriodicBoxVectors()
        system.setDefaultPeriodicBoxVectors(a,b,c)

        # Add atoms.
        for atom_index in range(reference_system.getNumParticles()):
            mass = reference_system.getParticleMass(atom_index)
            system.addParticle(mass)

        # Add constraints
        for constraint_index in range(reference_system.getNumConstraints()):
            [iatom, jatom, r0] = reference_system.getConstraintParameters(constraint_index)
            system.addConstraint(iatom, jatom, r0)

        # Copy selected appropriate.
        nforces = reference_system.getNumForces()
        for force_index in range(nforces):
            reference_force = reference_system.getForce(force_index)
            force_name = reference_force.__class__.__name__
            if force_name == 'HarmonicBondForce':
                new_force = openmm.HarmonicBondForce()
                system.addForce(new_force)
                for bond_index in range(reference_force.getNumBonds()):
                    [particle1, particle2, r, K] = reference_force.getBondParameters(bond_index)
                    if set([particle1, particle2]) in atom_set:
                        new_force.addBond(particle1, particle2, r, K)
```

**Comment by jchodera** [comment]
As we discussed yesterday, we could also make this more efficient by recoding all forces as CustomForce classes and allowing atom contributions to be turned on one at a time.  @pgrinaway would need to preenumerate the order in which atoms (or sets of atoms) should be turned on---not sure how hard this is. A Context parameter would then control how atom contributions are turned on.

Even more interesting could be to also make these additional atomic interactions alchemically switched on between integral values of this context parameter. This would be reasonably straightforward.

**Comment by pgrinaway** [comment]
Thanks!

Preenumeration is actually fairly straightforward--`GeometryEngine` v1 (in the attic) does that in an effort to reduce code duplication. 

A major advantage (in addition to speedup) that I could imagine from the CustomForce approach is that it might actually be cleaner than the alternative approach.

>Even more interesting could be to also make these additional atomic interactions alchemically switched on between integral values of this context parameter. 

In this case, can we also get a two for one deal by using the same alchemically-modified system in the geometry proposal as we do in NCMC?

**Comment by jchodera** [comment]
> In this case, can we also get a two for one deal by using the same alchemically-modified system in the geometry proposal as we do in NCMC?

That was my thinking.

I'm happy to code this up if you want to propose what the API should look like to fit in with the rest of `perses`.  I have plenty of code I could borrow from to cobble this together.

**Comment by pgrinaway** [comment]
Hm, I'm not sure what the easiest way to do this would be (as I have a lot less experience with manipulating these custom forces than you do), but would giving each new atom a context parameter `lambda_idx` be a viable option? This would make the interface for `perses` look something like this:

```python
#not sure if we want to use the AlchemicalEliminationEngine idea or something else
alchemical_system = AlchemicalEngine.create_system(unmodified_system, new_atoms, atom_proposal_order)
```

Then inside the `GeometryEngine`:
```python
context = openmm.Context(alchemical_system, integrator, platform)
for atom_idx in atom_proposal_order:
    context.setParameter('lambda_%d' % atom_idx, 1.0)
    #do geometry stuff
```
Is achieving something like this reasonable? Or would this require adding a ridiculous amount of CustomForces?

I'm not sure how we'd combine that with the NCMC parts (maybe that would be too confusing with too many global variables), but at least for the geometry bits it would be easy.

**Comment by pgrinaway** [comment]
Done in #114
