### ISSUE TITLE
Be consistent with minimizers

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#588]

**Comment by hannahbrucemacdonald** [comment]
It's been suggested that simulations that are NaNing on the first step of equilibration might be because the Fire minimizer is used for relative calculations, while the LocalEnergyMinimizer is used for NEQ.

Even if this isn't responsible for the nans, we should be self-consistent anyway

**Comment by jchodera** [comment]
@hannahbrucemacdonald : Did the minimizer change help your NaN issues with Mcl-1, or are you still having NaN issues?

If you're still having issues, can you create a new Perses issue with information on how to reproduce and debug?

**Comment by hannahbrucemacdonald** [comment]
Yep, this fixes the NaN issues
