### ISSUE TITLE
High energy difference between alchemical and non-alchemical energies with furan/thiophene

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#592]
Getting huge energy differences between the alchemical end states when trying to perturb furan into thiophene. Issue doesn't arise when perturbing either of these to pyrolle (which has the extra hydrogen)

> Traceback (most recent call last):
  File "/home/brucemah/software/perses/perses/app/setup_relative_calculation.py", line 454, in <module>
    setup_dict = run_setup(setup_options)
  File "/home/brucemah/software/perses/perses/app/setup_relative_calculation.py", line 395, in run_setup
    zero_state_error, one_state_error = validate_endstate_energies(_top_prop, _htf, _forward_added_valence_energy, _reverse_subtracted_valence_energy, beta = 1.0/(kB*temperature), ENERGY_THRESHOLD = ENERGY_THRESHOLD)
  File "/home/brucemah/miniconda3/envs/omm_source/lib/python3.6/site-packages/perses-0.1-py3.6.egg/perses/tests/utils.py", line 758, in validate_endstate_energies
    assert abs(nonalch_one_rp - alch_one_rp + subtracted_energy) < ENERGY_THRESHOLD, f"The one state alchemical and nonalchemical energy absolute difference {abs(nonalch_one_rp - alch_one_rp + subtracted_energy)} is greater than the threshold of {ENERGY_THRESHOLD}."
AssertionError: The one state alchemical and nonalchemical energy absolute difference 174.23110206093253 is greater than the threshold of 0.0001.

**Comment by hannahbrucemacdonald** [comment]
Error is always at lambda = 1 whether this is furan or thiophene, lamdba = 0 is fine

**Comment by hannahbrucemacdonald** [comment]
It looks like this is happening because the core-core bonds are being treated as `HarmonicBondForce` when they should be `CustomHarmonicBondForce`

**Comment by jchodera** [comment]
Can you also post the map for these transformations?

**Comment by jchodera** [comment]
[`self._hybrid_system_forces['core_bond_force']`](https://github.com/choderalab/perses/blob/master/perses/annihilation/relative.py#L545-L580) is a `CustomBondForce`, so perhaps these bonds are being added to the wrong key?

**Comment by jchodera** [comment]
[This logic](https://github.com/choderalab/perses/blob/master/perses/annihilation/relative.py#L920-L930) appears to assign all bonds where both atoms are core atoms to the `core_bond_force` class, so unless there is a subtle logic bug, I'm not sure that the bug is in the assignment.

Could it just be that the map isn't properly including these atoms as core atoms?

**Comment by hannahbrucemacdonald** [comment]
I'm fixing it now - when there are no unique atoms then it's treating the core as environments, will push a fix this evening

**Comment by jchodera** [comment]
> I'm fixing it now - when there are no unique atoms then it's treating what should be core as environment,

Ah! We had run into that before! Another good test system should be 1-chlorobenzene to 1-fluorobenzene. Maybe you can add a couple of test cases to the unit tests too?

**Comment by jchodera** [comment]
cc: https://github.com/choderalab/perses/issues/362

**Comment by hannahbrucemacdonald** [comment]
The issue only arises when you have multiple legs, but I will add a unit test tomorrow. Dom's `validate_endstate_energies ` catches it which is reassuring, and added a few more assert statements in `relative.py`
