### ISSUE TITLE
Implement support for charge changes

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#596]

**Comment by hannahbrucemacdonald** [comment]
Allow for changes in net charge of the alchemical molecule by pertrubing an distal ion

**Comment by jchodera** [comment]
I believe @zhang-ivy and @mikemhenry are working on this in the [`counterion`](https://github.com/choderalab/perses/tree/counterion) branch. 

Can we open a PR so we can track the PR number addressing this issue?

**Comment by zhang-ivy** [comment]
#770
