### ISSUE TITLE
Add openeye to travis tests

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#6]
Will add openeye installation to travis tests, based on openmoltools.

**Comment by pgrinaway** [comment]
Going to hold off on this for now. I'm looking at [the openmoltools travis](https://github.com/choderalab/openmoltools/blob/master/.travis.yml#L24) but I'm not really sure what happened there (where did those environment variables with the encrypted key come from? they aren't defined in the part below. Why not define them like the binstar token?). I'd play around myself, but I don't want to do anything that breaks the license terms.

**Comment by jchodera** [comment]
I can add those!  Unfortunately they don't work in pull requests from forks, only branches of the main repo.  Do we still want to do that?

**Comment by pgrinaway** [comment]
Ok. Maybe it would be better/easier to skip the tests if they involve openeye. Either way is fine with me.

**Comment by jchodera** [comment]
Are the OpenEye tools required for most of the interesting functionality?  Or just some of it?  We can definitely skip the tests in the same way openmoltools does if we think testing would still be useful.

**Comment by pgrinaway** [comment]
They're required for some of the earlier stuff that we wrote (in particular, multitopology stuff). They aren't required for any of the RJMC stuff, except possibly the proposal mechanism.

**Comment by jchodera** [comment]
I'm working on this now!  Will open a PR.

**Comment by jchodera** [comment]
Update: I haven't added the OpenEye tools yet, but I can do that tomorrow.

**Comment by jchodera** [comment]
This is added now.
