### ISSUE TITLE
Mapping of rings not behaving as expected

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#603]
Currently have issue where rings of different sizes are being mapped onto eachother as it passes the check that 'all bonds in one are in the other'

`oechem.OEExprOpts_RingMember` is insufficient, because we also need to check that molecules aren't mapping onto rings of different sizes i.e.:

![image](https://user-images.githubusercontent.com/43652597/70334042-a2524500-1812-11ea-8f8d-8085ae29e722.png)

**Comment by hannahbrucemacdonald** [comment]
Changing the breaking ring function so that it adds this check. As it is written, it will fail to map the above two molecules, and suggests the user write an atom map manually.

Although I'm not sure it's currently possible for this transformation to work, because it would require a ring system to be fully built in. This is currently an issue with some of the Bace ligands

**Comment by hannahbrucemacdonald** [comment]
![image](https://user-images.githubusercontent.com/43652597/70334309-36bca780-1813-11ea-84f9-0c29e9d3088f.png)


Note atoms 12 13 14

**Comment by hannahbrucemacdonald** [comment]
Attempting to sort it (so that it will fail during set up) in `ring-map` branch, but not sure how this conflicts with ring closure code

**Comment by jchodera** [comment]
Fixed by #627
