### ISSUE TITLE
Allow whether or not endstate corrections are used to be set in YAML

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#611]
Instead of [hard-coding whether the endstate correction is used](https://github.com/choderalab/perses/blob/master/perses/app/setup_relative_calculation.py#L490-L493) as we do now, we should allow the YAML file to override this behavior in case one wants to turn this off for testing.

**Comment by jchodera** [comment]
I suppose this could be simply a choice at analysis time! Instead, we might want to set parameters (like the PME tol) for the endstates.

**Comment by hannahbrucemacdonald** [comment]
I'm happy to do this, but could you clarify what you'd like? At the moment, endstates are included by default in the analysis, but it's still easy to get the non-endstate energies out too.

If we are going to expose different parameters for the end states, I'd want to make sure we are doing it in a clear way (i.e. show that it's only the endstates, and not a 'whole simulation' property) i.e. maybe with a prefix.

> PME-tol : xxx # this would be for sampled states
es-PME-tol : yyy # this would be for unsampled states

**Comment by hannahbrucemacdonald** [comment]
I'm not sure what we want to do with this, as it's possible to ignore them during analysis, but if there's value to this, I can put it in
