### ISSUE TITLE
Use entry-points instead of requiring absolute paths to scripts

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#612]
Instead of `/path/to/perses/app/setup_relative_calculation.py`, we should make use of [entry points](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) to allow `perses-setup-relative <yaml>` or `perses setup relative <yaml>`.

**Comment by hannahbrucemacdonald** [comment]
Done this in `analysis-improvements`.

> perses-relative simulation.yaml
