### ISSUE TITLE
slow protein mutations on some dipeptide transformations

### ISSUE THREAD

**Issue by dominicrufa** [choderalab/perses#629]
[perses_protein_mutations.tar.gz](https://github.com/choderalab/perses/files/4154762/perses_protein_mutations.tar.gz)

For the protein mutation code, some perturbations of residues are running much slower than others. It is likely that this is due to a restraint issue or possibly the tolerances used, and may be related to: https://github.com/openmm/openmm/issues/2380

The code to generate the issue is in `debug_speed_issue.ipynb`

**Comment by hannahbrucemacdonald** [comment]
I’m happy to try help with that this afternoon!

**Comment by dominicrufa** [comment]
[ala_to_ser_and_cys_to_ser.tar.gz](https://github.com/choderalab/perses/files/4208980/ala_to_ser_and_cys_to_ser.tar.gz)
the above .gz file contains hybrid system xmls for ala to ser and cys to ser.

ala to ser:
this seems to be running quickly.  (i.e. 0.14 ms per timestep on average over 1k timesteps)
also, ala to ser seems to be giving consistent forward and reverse free energy estimates in vacuum over 1000 repex cycles with default perses repex sampling parameters (see below):
```
('ALA' -> 'SER'): (34.09403272527055kT, err = 0.0037497935610104724kT),
 ('SER' -> 'ALA'): (-33.841897421933055kT, err = 0.004069442786996544kT)
```
and a second trial gives:
```
('ALA', 'SER'): (33.86980545735876kT, err = 0.003511753588553388kT),
 ('SER', 'ALA'): (-33.775661571202455kT, err = 0.0035493323191000464kT)
```

cys to ser: 
this seems to be running slowly.  (i.e. 1.1 ms per timestep on average over 1k timesteps).
cys to ser seems to be giving the following forward and reverse free energy estimates in vacuum over 1000 repex cycles with default perses repex sampling parameters (see below):
```
('CYS' -> 'SER'): (-9.709770145964946kT, err = 0.01825143693313883kT),
 ('SER' -> 'CYS'): (9.53155300551228, err = 0.024663589020475697kT)
```
and a second trial gives:
```
('CYS' -> 'SER'): (-9.338246025749381kT, err = 0.02285115377094992kT),
 ('SER' -> 'CYS'): (10.299134617462816, err = 0.026017901507416452kT)
```

I can't tell whether the forward/reverse is indeed consistent considering the difference in forward/reverse over 2 trials, though i haven't checked the convergence plots (will post in a later comment)

As far as the discrepancy in the speeds of simulations is concerned, there don't seem to be overdefined constraints causing an instability when i look at the system.xml file for CYS -> SER; the only bit of interest i observed was a constraint between the following atom pairs:
```
hybrid indices: 16, 23
	 ('SER', 'OG') ('SER', 'HG') 0.096 nm
	this is a new topology constraint
```
and 
```
hybrid indices: 15, 16
	 ('CYS', 'HG') ('CYS', 'SG') 0.13360000000000002 nm
	this is an old topology constraint
```

the indices correspond to the following residue name/atom name tuples:

```
hybrid_index: 15
hybrid mass: 4.0 Da
	old atom map: ('CYS', 'HG')
	old atom

hybrid_index: 16
hybrid mass: 29.068 Da
	new atom map: ('SER', 'OG')
	old atom map: ('CYS', 'SG')
	core atom

hybrid_index: 23
hybrid mass: 4.0 Da
	new atom map: ('SER', 'HG')
	new atom
```
(i.e. the `SG` is mapping to the `OG` and since the `HG` constraint distance is changing, we have to create a unique old and unique new `HG` with restraint distances corresponding to the constraint distances reported in the old/new systems, respectively)

when i delete the last constraint in the hybrid system (i.e.
```
hybrid indices: 16, 23
	 ('SER', 'OG') ('SER', 'HG') 0.096 nm
	this is new
```
i am able to recover the following integration speed:
`0.0001483888626098633 s/timestep`

Is there a reason that i should be expecting this speedup when i delete a single constraint?
also, for reference, i am able to validate the enstates when i generate the geometries and hybrid factories of all the aforementioned systems with https://github.com/choderalab/perses/blob/18f86d5d6d85049651d662163b077c76e49bca9b/perses/tests/utils.py#L700, so _all_ energy bookkeeping is exact withing 1e-6 kT

**Comment by jchodera** [comment]
Thanks for the great report! I'll look into this!

I wonder what happens if we don't map the OG to SG and instead only map the
shared backbone atoms and their protons?

**Comment by jchodera** [comment]
Also, just to check---the speed difference is also just as big for solvated systems, right?

**Comment by dominicrufa** [comment]
> Also, just to check---the speed difference is also just as big for solvated systems, right?

Well this is surprising...it looks like that (at least on a CPU) the solvent phase takes about the same amount of time for `ala -> ser` and `cys -> ser`:
```
ala -> ser: 0.004523008346557617 s/timestep
cys -> ser: 0.004359082460403442 s/timestep
```
i'll check GPU speeds tomorrow morning; see the solvent state and system `.xml` files attached.





> I wonder what happens if we don't map the OG to SG and instead only map the shared backbone atoms and their protons?

it looks like that `strong` atom mapping scheme generates this sort of topology map:
![image](https://user-images.githubusercontent.com/46943710/74613275-cbc50200-50da-11ea-881c-1ae3ebd2829f.png)

in this case, it looks like that even in vacuum, the time per timestep is consistent between ala->ser and cys->ser (on a CPU; again, i'll check tomorrow on GPU):
```
ala -> ser: 0.000464937686920166 s/timestep
cys -> ser: 0.0004548287391662598 s/timestep
```
i haven't actually run repex to convergence for forward/reverse solvent phase for the default atom maps, or the vacuum phase for the strong atom maps, but i will tomorrow and report if they seem problematic.  though i don't suspect any inconsistencies in the `strong_map` repex simulations, generally, these will take longer to converge because there are more `unique old/new` atoms.

below are the state and system xmls for `(default_maps, solvent), (default_maps, vacuum), and (strong_maps, vacuum):
[xmls.tar.gz](https://github.com/choderalab/perses/files/4210965/xmls.tar.gz)

**Comment by jchodera** [comment]
Thanks for the great updates!

I think it's worth taking this to the OpenMM issue tracker. I've prepared a simple script for Peter to use to check the timing, and included it here. I've also included variants where I migrate one {O/S}-H or two {O/S}-H bonds to `HarmonicBondForce`---either eliminates the constraint bottleneck.

```
$ python time_system.py 
ALA_SER                        Reference      30.701 ms elapsed :      0.307 ms/step
CYS_SER                        Reference      28.431 ms elapsed :      0.284 ms/step
CYS_SER-1harmonic              Reference      34.069 ms elapsed :      0.341 ms/step
CYS_SER-2harmonic              Reference      55.256 ms elapsed :      0.553 ms/step
***
ALA_SER                        CPU            35.232 ms elapsed :      0.352 ms/step
CYS_SER                        CPU            37.138 ms elapsed :      0.371 ms/step
CYS_SER-1harmonic              CPU            38.331 ms elapsed :      0.383 ms/step
CYS_SER-2harmonic              CPU            36.925 ms elapsed :      0.369 ms/step
***
ALA_SER                        OpenCL          1.781 ms elapsed :      0.018 ms/step
CYS_SER                        OpenCL        191.182 ms elapsed :      1.912 ms/step
CYS_SER-1harmonic              OpenCL          1.300 ms elapsed :      0.013 ms/step
CYS_SER-2harmonic              OpenCL          1.990 ms elapsed :      0.020 ms/step
***
```

[example.zip](https://github.com/choderalab/perses/files/4211443/example.zip)


I think we had this issue before (with @hannahbrucemacdonald) where we noted that OpenCL/CUDA platforms use a _different_ implementation than the CPU/Reference platforms for handling constraint convergence. Once again, this is causing headaches and 100x slowdowns. We should see if we can get those platforms harmonized now.

@dominicrufa : Do you want to submit this issue or should I?

**Comment by dominicrufa** [comment]
> @dominicrufa : Do you want to submit this issue or should I?
@jchodera : please go ahead and submit the issue; i think your explanation of the problem would be more descriptive than mine.  Thanks a lot for looking into this issue.  it has caused me a lot of frustration in getting protein mutations working, and i initially thought that my tampering with `HybridTopologyFactory` to add `environment` to `core` atom valence terms had royally messed up the system hybridization pipeline (which it has not).

**Comment by jchodera** [comment]
> it has caused me a lot of frustration in getting protein mutations working, and i initially thought that my tampering with HybridTopologyFactory to add environment to core atom valence terms had royally messed up the system hybridization pipeline (which it has not).

Any suggestions for how we could implement better tools or tests to reduce the frustration here? It sound like it would be good for us to just make sure our battery of hybrid system tests is pretty complete and quick enough to run entirely via GitHub Actions?

**Comment by jchodera** [comment]
Looks like this is not a bug after all. See the clear explanation here:
https://github.com/openmm/openmm/issues/2380#issuecomment-587559365

The basic idea is this:
1. For this vacuum system, the ALA->SER mutation just uses SHAKE throughout, while CYS->SER must use CCMA for the coupled constraints. CCMA involves more kernel launches, which shows up as a speed difference.
2. Because we did not actually force the kernels to execute with a `context.getState()` call after the `integrate.step()` call, we didn't actually execute the integration for the ALA->SER calculations, and were just timing the queuing rather than execution of GPU kernels.

Let's make sure to test things like this on real solvated systems on a GPU in future just to make sure there really is an issue.
