### ISSUE TITLE
Change dependency to openmoltools

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#63]
This is a reminder to myself to change the dependency from `openmoltools-dev` to `openmoltools` and ensure that Python 3 testing is working on travis. Will do this in the next PR.

**Comment by jchodera** [comment]
I can't even remember what we use `openmoltools` for.

**Comment by jchodera** [comment]
Oh, nevermind!

Fixing this here: https://github.com/choderalab/openmoltools/pull/165

**Comment by jchodera** [comment]
Fixed. Packages will be uploaded shortly: https://anaconda.org/omnia/openmoltools-dev/files

**Comment by pgrinaway** [comment]
Thanks! So should I keep `openmoltools-dev`?

**Comment by jchodera** [comment]
Looks like the packages haven't been pushed. Not sure why.

**Comment by jchodera** [comment]
Think I've fixed it. Let's give it a few min.

**Comment by pgrinaway** [comment]
I think this is resolved
