### ISSUE TITLE
Initialization of a relative calculation is slow

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#644]
The initial stages of setup take ~30 minutes. Let's look into this to figure out why.

**Comment by jchodera** [comment]
Maybe we can add timestamps (or delta timestamps) to the logs so we can easily sort to figure out the slow steps?

**Comment by jaimergp** [comment]
Or `cProfile` it 🗡

The log will be huge and it will take a couple of times longer, but it should be easier to figure out later. Maybe both solutions are useful together.

**Comment by jchodera** [comment]
It's easy to configure the logger to show both the (1) timestamp, and (2) time elapsed since last log message, which will make tracking this down a breeze:
https://stackoverflow.com/questions/31521859/python-logging-module-time-since-last-log

**Comment by hannahbrucemacdonald** [comment]
I'm generating some output to dig through.

`logging.basicConfig(level=logging.INFO)`
Doesn't seem to work for me, instead I need to call
`_logger.setLevel(logging.INFO)`

Not sure if it's a bug or I'm doing something wrong, but making a note of it here to sort it in future

**Comment by jchodera** [comment]
Could this be related to [import ordering](https://stackoverflow.com/questions/20240464/python-logging-file-is-not-working-when-using-logging-basicconfig)?

**Comment by hannahbrucemacdonald** [comment]
Yes it's exactly that

**Comment by jchodera** [comment]
Once we identify candidate steps/functions for targeted optimization, we can tag them with [profiler hooks](https://pypi.org/project/profilehooks/) to report on what the major slow steps within the methods are.

**Comment by hannahbrucemacdonald** [comment]
I might have been being over-dramatic, the Mcl1 systems I've tested this morning take 7 or 8 minutes to run through the setup on a GPU. 

The `validate_endstates_energy` takes 120s, 30s, 3s (complex/solvent/vacuum). Do we need to run this for every phase? Maybe we could just call it for the cheapest phase?

`Handling unique_new/old interaction exceptions...` takes 120 s, < 1 s, < 1s for each phase.

`feptasks.minimize` varies, but takes around 20s for the first state (lambda=0) and ~2s for each other state for the complex phase. I think this is ok because it will scale well with `n_lambdas`.

 

I will check for some other systems though, it might be that other transformations/larger proteins etc are slower.

**Comment by jchodera** [comment]
Could we merge in the log modifications in a PR so the timing info will always be generated in our logs? That will help us continue to make improvements!

**Comment by jchodera** [comment]
> The validate_endstates_energy takes 120s, 30s, 3s (complex/solvent/vacuum). Do we need to run this for every phase? Maybe we could just call it for the cheapest phase?

I think @dominicrufa mentioned that we were using the CPU for this; we should certainly be able to use the GPU instead, shouldn't we?

If we're checking consistency between the hybrid and real endpoints, we would want to validate the this for at least the solvent phase since we otherwise omit testing the intermolecular interactions if we just did vacuum.

**Comment by hannahbrucemacdonald** [comment]
Why are we using the CPU rather than the GPU for the test?

**Comment by dominicrufa** [comment]
if you use CPU for the test, then the error in the endstates usually hovers around 1e-6kT, whereas if you use Reference, the error is roughly 4 orders of magnitude smaller.  i haven't tried gpu

**Comment by hannahbrucemacdonald** [comment]
Is that a precision thing?

**Comment by jchodera** [comment]
> if you use CPU for the test, then the error in the endstates usually hovers around 1e-6kT, whereas if you use Reference, the error is roughly 4 orders of magnitude smaller. i haven't tried gpu

We should just be using `mixed` precision on the GPU, I think!

**Comment by dominicrufa** [comment]
that is the default in the protein mutations PR; once that is merged, then the `_validate_endstate_energies` will run fast

**Comment by hannahbrucemacdonald** [comment]
I think this can be closed now!
