### ISSUE TITLE
GH actions cannot read picked oemols

### ISSUE THREAD

**Issue by dominicrufa** [choderalab/perses#645]
it looks like the last few protein mutations are failing because github actions cannot read pickled oemols (amino acid oemol templates), preventing `Protein Mutations` PR from passing:
```
2020-03-05T16:15:48.4375428Z   File "/home/runner/work/perses/perses/perses/rjmc/topology_proposal.py", line 1681, in _construct_atom_map
2020-03-05T16:15:48.4376305Z     current_oemol = pickle.load(f)
2020-03-05T16:15:48.4377289Z ModuleNotFoundError: No module named 'oechem'
```
not sure why this is a problem
https://pipelines.actions.githubusercontent.com/Kswyxv64lmZdxUXYg0y7ffUub03Qkzsl1NYIuHlgf2MFTXLqWF/_apis/pipelines/1/runs/168/signedlogcontent/5?urlExpires=2020-03-05T16%3A46%3A34.1269869Z&urlSigningMethod=HMACV1&urlSignature=0FxPIlpGJrAmNkXEcPxrsXGNwzyrIr2xNIw%2B9Smwg%2B0%3D

**Comment by jaimergp** [comment]
Is [this SO answer](https://stackoverflow.com/a/2121918) helpful?

> pickle can save and restore class instances transparently, however the class definition must be importable and live in the same module as when the object was stored

Are we loading the pickles in a different module?

**Comment by dominicrufa** [comment]
yes, but the oechem _is_ imported at the time that i am attempting to load the oemol from a pkl...

**Comment by jaimergp** [comment]
Tests pass locally even in a fresh environment? If that's the case, that'd be surprising. Can you confirm?

**Comment by dominicrufa** [comment]
i just reverted to .pdb files as templates.
