### ISSUE TITLE
Oemol rendering things as radicals

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#647]
Need to check that the radicals are only an aesthetic error, rather than the charge being misinterpreted in the whole simulation.

The renderings can be done using: `perses/examples/atom-mapping/*ipynb`, but we are getting something that looks like this:

![image](https://user-images.githubusercontent.com/43652597/76105558-28f9f800-5fa3-11ea-84ac-6ce28f579127.png)

Which is Bace ligand 27 -> 29 (with zero indexing).

I will look into what net charge is associated to the oemol, but I suspect (and very much hope) that this is just a rendering problem, rather than a simulation issue

**Comment by jchodera** [comment]
In that notebook example, it looks like the input molecules are fine but the atom mapping depiction looks problematic, so I'm guessing this is just an issue in `render_atom_mapping`. My guess is that we're missing copying over crucial formal charge information here:
https://github.com/choderalab/perses/blob/master/perses/utils/smallmolecules.py#L169-L180

**Comment by jchodera** [comment]
Turns out that was it. All we needed to do is to copy over formal charges too:
```python
            new_atom.SetFormalCharge(old_atom.GetFormalCharge())
```
I'll open a PR.
