### ISSUE TITLE
Some Bace transformations failing due to validate endstate energies

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#649]
>  File "/home/brucemah/miniconda3/envs/omm_source/lib/python3.6/site-packages/perses-0.5.1-py3.6.egg/perses/tests/utils.py", line 784, in validate_endstate_energies
    assert abs(nonalch_one_rp - alch_one_rp + subtracted_energy) < ENERGY_THRESHOLD, f"The one state alchemical and nonalchemical energy absolute difference {abs(nonalch_one_rp - alch_one_rp + subtracted_energy)} is greater than the threshold of {ENERGY_THRESHOLD}."
AssertionError: The one state alchemical and nonalchemical energy absolute difference 0.00028245274916116614 is greater than the threshold of 0.0001.

I am seeing the endstate energy fail for `gaff-2.1.1`, for a bunch of pairs of ligands for Bace. These edges have run fine with the `openff-1.0.0`

It also seems like it's passing for the complex and solvent phases (which should be the harder test??) and failing for vacuum. For 21 edges, and seems to be between 0.00017 and 0.00028, when the threshold is 0.0001.

Also --- it always seems to be failing at lambda=one state. I can't see any pattern in the ligands that are lambda=1, or any pattern in the edges that fail.

Errors are in `/data/chodera/brucemah/relative_paper/perses050/bace/gaff-2.11`

**Comment by hannahbrucemacdonald** [comment]
Things that are weird: always lambda=1, complex+solvent are fine, edges are random, off is fine. I'm going try with gaff-1.81 and see what happens, otherwise I will print out an off vacuum file and a gaff vacuum file and do spot the difference.


@dominicrufa will you remind me how I figure out what energy term the difference is coming from?

**Comment by hannahbrucemacdonald** [comment]
It looks like the same edges fail with gaff-1.81

**Comment by jchodera** [comment]
Thanks! I suspected this might happen.

Can you dump system and state XML files for the hybrid and endstates systems? It's easiest to debug this from there.

**Comment by hannahbrucemacdonald** [comment]
My bad - it _is_ in the complex phase.

**Comment by hannahbrucemacdonald** [comment]
# Alchemical State
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> CustomBondForce : 211.9647278169761 kJ/mol
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> HarmonicBondForce : 4899.265608807075 kJ/mol
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> CustomAngleForce : 84.6858030525349 kJ/mol
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> HarmonicAngleForce : 12747.275086074495 kJ/mol
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> CustomTorsionForce : 10.884242109900304 kJ/mol
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> PeriodicTorsionForce : 20281.932296018407 kJ/mol
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> NonbondedForce : -383557.848362556 kJ/mol
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> CustomNonbondedForce : 1800.3242463351119 kJ/mol
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> CustomBondForce : 0.0 kJ/mol
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> AndersenThermostat : 0.0 kJ/mol
INFO:root:<openmmtools.states.CompoundThermodynamicState object at 0x7fc1e5da3ef0> MonteCarloBarostat : 0.0 kJ/mol
INFO:root:added forces:-137720.30939281263
INFO:root:reduced potential: -137708.51273668956



## Non-alchemical state
INFO:root:<openmmtools.states.ThermodynamicState object at 0x7fc1e5db0a20> HarmonicBondForce : 5111.230336624052 kJ/mol
INFO:root:<openmmtools.states.ThermodynamicState object at 0x7fc1e5db0a20> HarmonicAngleForce : 12831.878829478324 kJ/mol
INFO:root:<openmmtools.states.ThermodynamicState object at 0x7fc1e5db0a20> PeriodicTorsionForce : 20292.54069334708 kJ/mol
INFO:root:<openmmtools.states.ThermodynamicState object at 0x7fc1e5db0a20> NonbondedForce : -381773.08471288945 kJ/mol
INFO:root:<openmmtools.states.ThermodynamicState object at 0x7fc1e5db0a20> AndersenThermostat : 0.0 kJ/mol
INFO:root:<openmmtools.states.ThermodynamicState object at 0x7fc1e5db0a20> MonteCarloBarostat : 0.0 kJ/mol
INFO:root:added forces:-137726.69123730273
INFO:root:reduced potential: -137714.89458117963


`complex_subtracted_valence_energy=6.382021433648333`

**Comment by hannahbrucemacdonald** [comment]
Why are there two `CustomBondForce` in the Alchemical state? The second one is 0.0 but not sure where it comes from

**Comment by dominicrufa** [comment]
> Why are there two `CustomBondForce` in the Alchemical state? The second one is 0.0 but not sure where it comes from

there is a custom bond force for core-core bonds as well as a custom bond force for nonbonded exceptions that are interpolated.  can you make sure you are validating theses endstates with a `Reference` platform in the `validate_endstate_energies` function?

also, for clarity, it _is_ failing in all three phases?  if so, could you try to parametrize one of the failing ligands in the `Protein Mutations` PR and post the readout from the `validate_endstate_energies` function, as well as the output of the `FFAllAngleGeometry` engine in the forward and reverse directions found here: https://github.com/choderalab/perses/blob/b8c60e45b4798d099cad9624813bc57e02e0aa00/perses/rjmc/geometry.py#L725

**Comment by dominicrufa** [comment]
the idea is that we can look at the valence corrections and the hybrid system forces and validate each force object (or pairs of force objects) separately.

**Comment by jchodera** [comment]
@hannahbrucemacdonald : I don't think we will learn much from comparing the individual Force components for the alchemical and non-alchemical states, since the force terms get recoded in such complicated ways. 

Instead, we first need to know which of the original unmodified Force classes is responsible to help us know where to look. I'd extend the test so that if it fails, it cycles through each force class type of the original system and only includes that force class (bonds, angles, torsions, LJ, LJ+electrostatics) of the original A and B systems to try to identify the source of the discrepancy in the test. This can be easily done with just feeding arguments to SystemGenerator:
https://github.com/openmm/openmmforcefields/blob/master/openmmforcefields/generators/system_generators.py#L140

Note that we would do this for the original A and B systems, and then feed them into the hybrid alchemical factory and test the discrepancy.

That is, we would zero out everything but the bonds for A and B real systems and _then_ feed them into the test. Then we do it with the angles, and so on.

**Comment by hannahbrucemacdonald** [comment]
I noticed that there are many more torsion terms in the OFF system than the GAFF one, but haven't nailed down yet which torsion terms these are.

`system_generator.torsions = False # will zero out all torsion terms`

using this, the endstate energies pass, so it's a torsion thingy.

I'm printing `forces["CustomTorsionForce"].getGlobalParameterDefaultValue(0)` for both hybrid end states at it's correctly set to 0 and 1 respectively.

**Comment by hannahbrucemacdonald** [comment]
>I noticed that there are many more torsion terms in the OFF system than the GAFF one, but haven't nailed down yet which torsion terms these are.

I've attached the 'real' systems for the transformation Bace 10 -> 24 which is failing for GAFF but working for OFF. There are many more torsion parameters defined for the OFF system than the gaff for the same molecule.
[systems.zip](https://github.com/choderalab/perses/files/4338947/systems.zip)

**Comment by dominicrufa** [comment]
> > I noticed that there are many more torsion terms in the OFF system than the GAFF one, but haven't nailed down yet which torsion terms these are.
> 
> I've attached the 'real' systems for the transformation Bace 10 -> 24 which is failing for GAFF but working for OFF. There are many more torsion parameters defined for the OFF system than the gaff for the same molecule.
> [systems.zip](https://github.com/choderalab/perses/files/4338947/systems.zip)

i'll look into this transform at some point today.  thanks

**Comment by hannahbrucemacdonald** [comment]
@jchodera

**Comment by jchodera** [comment]
> I've attached the 'real' systems for the transformation Bace 10 -> 24 which is failing for GAFF but working for OFF. There are many more torsion parameters defined for the OFF system than the gaff for the same molecule.

I'm looking into this now, but I'm not entirely sure which molecule you're looking for. I'd need the SDF files in order to check this.

For now, I'm looking at [`perses/perses/data/bace-example/Bace_ligands_shifted.sdf`](https://github.com/choderalab/perses/blob/master/perses/data/bace-example/Bace_ligands_shifted.sdf), and I'm assuming you're counting from 0 and referring to the old ligand (ligand 10). Let me know if that isn't correct.

From what I can see using the script below, the high number of torsion terms is correct:
```
$ grep "Torsion k" ligand10.gaff-1.81.system.xml  | wc -l
     110
$ grep "Torsion k" ligand10.gaff-2.11.system.xml  | wc -l
     111
$ grep "Torsion k" ligand10.smirnoff99Frosst-1.1.0.system.xml  | wc -l
     161
 $grep "Torsion k" ligand10.openff-1.0.0.system.xml  | wc -l
     196
```
If you turn on `DEBUG` logging, you can see that both `smirnoff99Frosst` and `openff` assign 118 torsions, but some of these torsions have multiple periodicities, so multiple entries are created.

Here's the script I used:
```python
from openmmforcefields.generators import SystemGenerator
from openforcefield.topology import Molecule

import logging 
logging.basicConfig(level=logging.DEBUG)

molecules = Molecule.from_file('Bace_ligands_shifted.sdf')
molecule_index = 10

from simtk import openmm
def write(system, filename):
    with open(filename, 'w') as outfile:
        outfile.write(openmm.XmlSerializer.serialize(system))

for forcefield in ['gaff-1.81', 'gaff-2.11', 'smirnoff99Frosst-1.1.0', 'openff-1.0.0']:
    system_generator = SystemGenerator(small_molecule_forcefield=forcefield, molecules=molecules)
    system = system_generator.create_system(molecules[molecule_index].to_topology().to_openmm())
    filename = 'ligand10.' + forcefield + '.system.xml'
    print(filename)
    write(system, filename)
```

**Comment by jchodera** [comment]
@hannahbrucemacdonald: Can you share the `{system,state}.xml` for the old, new, and hybrid systems?

**Comment by hannahbrucemacdonald** [comment]
>For now, I'm looking at perses/perses/data/bace-example/Bace_ligands_shifted.sdf, and I'm assuming you're counting from 0 and referring to the old ligand (ligand 10). Let me know if that isn't correct.
Yes, sorry this is correct

**Comment by jchodera** [comment]
@hannahbrucemacdonald: Can you share the `{system,state}.xml` for the old, new, and hybrid systems?

**Comment by hannahbrucemacdonald** [comment]
Fixed in `new_ring_closing branch`
