### ISSUE TITLE
Near term goals and planning

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#65]
This is what I am currently thinking--please let me know if you disagree.

`perses` has these parts which need development:

*`TopologyProposalEngine` - this already has an implemented base class and subclasses for small molecules. The small molecule bits need to be refactored for two reasons:
   * The alignment can have multiple results, so the choice of alignment should be random and factored in to the acceptance probability. This is more urgent and I will do it soon.
   * The innards should be refactored to use the OpenMM APIs rather than `tleap`. This is lower priority, since I think the priority is getting something that actually works. This also doesn't change the outward-facing API.

 * `GeometryEngine` - This is implemented, but needs a couple things, some of which are high priority:
   * `GeometryEngine` needs a suite of tests. This is very high priority and was the next thing I wanted to do. 
   * `GeometryEngine` should use OpenMM to calculate potentials. The code for this is already started, but is in the unmerged closed PR. Now that we have a set goal, I can finish this. This is also very high priority.
   * It could use some optimizations. This is low priority.

* `AlchemicalEliminationEngine` and `NCMCEngine` - complete.

* `Sampler` classes (even if only using simple algorithms) need to be written in order to actually do anything with `perses`. This is high priority.

So, my near-term plan of action was, in order:

1. Finish relevant `GeometryEngine` stuff.
2. Fix the `TopologyProposalEngine` to correctly deal with multiple possible alignments.
3. Write a `SAMSSampler` and `ExpandedEnsembleSampler`.
4. Write an adaptive bias `SAMSSampler`.

After (3), we should be able to do relative free energy calculations with SAMS, as well as design with a fixed bias. I think that should be the initial goal here.

Does this sound ok?

**Comment by pgrinaway** [comment]
Ok, after a chat with @jchodera, we'll keep the above list except:

1. Basic API test framework
2. Finish relevant GeometryEngine stuff.
3. Fix the TopologyProposalEngine to correctly deal with multiple possible alignments.
4. Write a SAMSSampler, ExpandedEnsembleSampler, and adaptive bias SAMSSampler
5. Include examples (host/guest, T4 Lysozyme)

**Comment by jchodera** [comment]
Sounds great.  We should include another example that tests @juliebehr's `MutationEngine` too.  There are mutations of T4 lysozyme that modulate the ligand affinities: [L99A binders](http://www.bkslab.org/l99a-binders.php), [L99A nonbinders](http://www.bkslab.org/l99a-non-binders.php), [L99A/M102Q binders](http://www.bkslab.org/l99a-m102q-binders.php), [L99A/M102Q non-binders](http://www.bkslab.org/l99a-m102q-non-binders.php), and a number of additional mutants in [this paper](10.1073/pnas.1500806112).

**Comment by pgrinaway** [comment]
Going to close this, since this is mostly done.
