### ISSUE TITLE
Maps not symmetrical WRT to ligand 0 and 1

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#651]
This is related to issue #649 

Basically the map should be the same whichever direction you go in, but we seem to have an issue for the same two ligands that I used as an example with the previous issue.

for ligand 10 -> 24 we get:
![image](https://user-images.githubusercontent.com/43652597/76321606-a3cf5580-62b8-11ea-9498-efc6133e5fec.png)

which is correct considering the mapping criteria used
atom_expression:
    - IntType

but doing the opposite 24 -> 10 we get:
![image](https://user-images.githubusercontent.com/43652597/76321686-bea1ca00-62b8-11ea-9d3b-8d78b84cfad5.png)

Where it hasn't maximised the number of possible matches found for the given atom_expression. I realise this map is fine to run, but it isn't the one you'd expect from the atom_expression, and it should be symmetrical.

Maybe it's something to do with the openeye MCS function? But we could get around it by doing mappings of i -> j and j -> i and picking the best map from both sets for the simulation

**Comment by hannahbrucemacdonald** [comment]
It's like it hasn't seen the torsion around the 5-6 bond? Also this would cause problems because you've basically got conformationally-locked isomers in the binding site. The Cl will be grown into the wrong side of the active site? (assuming one binding pose)

**Comment by dominicrufa** [comment]
sorry, a torsion about the 5-6 bond is being omitted?!

**Comment by hannahbrucemacdonald** [comment]
Nono it's like the mapping protocol hasn't realised it can rotate around that

This is nothing to do with parameterization, just mapping

**Comment by hannahbrucemacdonald** [comment]
The problem persists if `Exhaustive` is used instead of `Approximate`

**Comment by hannahbrucemacdonald** [comment]
This is an issue when using `map_strength='default` but not when using the bespoke atom and bond expressions that I'm using for the JACS set. Still needs to be fixed

**Comment by jchodera** [comment]
@hannahbrucemacdonald : Good catch!

Is there any chance there are _multiple_ equivalent matches by the MCS critiera, and we're just picking the (arbitrary) first one?

If there is a _unique_ match, we should report this to OpenEye if we can prepare a minimal Python script which simply attempts to generate the MCS from the two molecules in either direction, checking that the atom mapping in either direction is the same.

**Comment by hannahbrucemacdonald** [comment]
They should both be found by MCS, but they shouldn't be equivalent as one has larger number of core atoms than the other, which we select for.  I don't know if it just doesn't consider that 5-6 bond as rotatable?

**Comment by jchodera** [comment]
Sounds like we need a minimum script and input to reproduce this issue and can then debug from there. Could you put one together?

Also, these diagrams still show the same issue we fixed earlier where the molecule being plotted did not have the correct formal charges (fixed in https://github.com/choderalab/perses/pull/648). Could we make sure to use that fix when rendering these? Otherwise, it will cause a lot of confusion.
