### ISSUE TITLE
Remove hard-coding of the `CUDA` platform in `rjmc.geometry.py`

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#663]
At the moment it's hard coded with `CUDA` double, falling back to the slower `Reference` for testing the endstate energy validations.

It would be better to use OpenCL than reference if double is supported, however there is not a clean way to currently test this. I've opened an openmm issue here: https://github.com/openmm/openmm/issues/2635

to see if that may be possible

**Comment by ijpulidos** [comment]
Check if this can be closed with the changes in https://github.com/choderalab/perses/pull/1092

**Comment by ijpulidos** [comment]
Closed via #1092 . `geometry.py` doesn't have the platform hardcoded now.
