### ISSUE TITLE
Parameterizing systems with ForceField

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#67]
I've now put a few methods into `simtk.openmm.app.ForceField` that give us a lot of flexibility for creating new residue definitions, either via `ffxml` files written beforehand (as in `gaff2xml`) or via a plugin that generates templates and parameters on the fly.

For creating parameters on the fly, the problem right now is that `ForceField.createSystem(topology)` only takes in a `topology` object.  If we need to parameterize a new residue (small molecule or biopolymer), it is not clear if we have sufficient information about bond order to generate conformations for parameterizing the missing residue.  

Note that this doesn't affect cases where we already have or can pre-generate parameters, such as standard biopolymers (proteins and nucleic acids) and small molecule libraries (where parameters can be pregenerated).

If we had an input structure, we could in principle perceive bond order from this (e.g. using the OpenEye [`OEPerceiveBondOrders`](https://docs.eyesopen.com/toolkits/python/oechemtk/connectivity.html#bond-order-perception) method), but in Perses, if we are proposing changes to a new molecular species, we need the `System` in order to generate the geometry.  This is a chicken-and-egg problem.

I see three possible solutions:
* A. Find a way to to go from the `Residue` (complete with fully explicit hydrogens) and determine bond orders from connectivity alone and either specification of the charge state or inference as to the likely charge state.
* B. Add optional information about bond order to `Topology` that can be used in creating the system. 
* C. Externally generate plausible structural data for the new residue

It turns out that `antechamber` includes a program [`bondtype`](http://ambermd.org/antechamber/ac.html#bondtype) that [infers bond order automatically](http://modem.ucsd.edu/html/publications/Atom_type.pdf), so provided this works robustly enough, I think we can use this scheme.  I don't know if we will run into trouble with it not being able to guess the appropriate ionization state, and there may be issues with the workflow
```
residueTemplateGenerator -> bondtype -> OEMol -> OEOmega (coordinates) -> antechamber
```
but I think it will work in principle.

**Comment by pgrinaway** [comment]
I suppose this falls under B, but what about an option where we also include a SMILES string. This would fully specify the topology of the molecule, including bond order, and is something that (at least for small molecules) we generate anyway.

For polymers, we could have a SMILES string of the modified monomer?

Perhaps the antechamber option would be easiest, though.

**Comment by jchodera** [comment]
> I suppose this falls under B, but what about an option where we also include a SMILES string. This would fully specify the topology of the molecule, including bond order, and is something that (at least for small molecules) we generate anyway.

That would certainly work!  It would be harder to add this as a `residueTemplateGenerator` plugin, but the easy way to do this would be for us to do something like this in Perses
```python
template = generateResidueTemplateFromSmiles(smiles)
forcefield.registerResidueTemplate(template)
new_system = forcefield.createSystem(new_topology)
```
It may make the most sense to put `generateResidueTemplateFromSmiles` in `openmoltools.forcefield_generators`.  Do you want me to take a stab at that? 

> For polymers, we could have a SMILES string of the modified monomer?

This might be complex because you need to specify a repeating fragment along with terminal blocking groups to parameterize.  Christopher Bayly suggested there was a way to use group specifications in SMIRKS, where we could specify the repeating unit along with the terminal groups that are to be eliminated.  This could then be used to easily parameterize and then modify the residue to be polymeric.

Another possibility for biopolymers is to simply use the PDB Chemical Components Dictionary:
http://deposit.pdb.org/cc_dict_tut.html

I'm not sure if the CIF files have bond order, but they at least have reference geometries.  They may not easily designate the external bonds, however.

**Comment by pgrinaway** [comment]
>It may make the most sense to put generateResidueTemplateFromSmiles in openmoltools.forcefield_generators. Do you want me to take a stab at that?

Sure! I think that option looks pretty nice.

>Christopher Bayly suggested there was a way to use group specifications in SMIRKS

Right, I had forgotten about this! It sounded like this might be a good, consistent way to go. I'm going to have to read up a bit more about SMIRKS though.

**Comment by jchodera** [comment]
How would you want to handle protonation states?  Do you want `generateResidueTemplateFromSmiles` to generate *just* what is specified in the SMILES with the idea that you would pre-enumerate protonation states and choose one?  (Can SMILES even uniquely encode specific protonation states?)  Or would you want an extra argument that choses a particular protonation state?  Or perhaps it should pick a protonations state at random and parameterize that?

I guess the resulting template has to match the modification you made to `Topology`.  Do you go through `OEMol` for that?  If so, can you just pass in an `OEMol` instead?

**Comment by pgrinaway** [comment]
>I guess the resulting template has to match the modification you made to Topology. Do you go through OEMol for that? If so, can you just pass in an OEMol instead?

Maybe this would be easier. I do go through `OEMol` for that.

**Comment by jchodera** [comment]
Great.  Protonation state is unambiguous then, so it should be very easy to do this.

I'll write the following function for `openmoltools.forcefield_generators`:
```
def generateResidueTemplate(molecule):
    """
    Generate simtk.openmm.app.ForceField residue template from OEMol molecule.

    Parameters
    ----------------
    molecule : openeye.oechem.OEMol
         The molecule to parameterize with GAFF/AM1-BCC
         All hydrogens and aromaticity must be explicitly defined.

    Results
    ----------
    template : simtk.openmm.app.forcefield._TemplateData
        Residue template that can be added to ForceField object via registerResidueTemplate()
"""
Does that work?

**Comment by pgrinaway** [comment]
That is fine with me.

**Comment by jchodera** [comment]
OK, nearly got this working:
https://github.com/choderalab/openmoltools/pull/164

It looks like we might be able to go either from an OpenMM Topology `Residue` (using Antechamber's `bondtype` bond perception) or an `OEMol` molecule.

Both the pre-generation of residue templates:
```python
forcefield = ForceField('amber99sb.xml', 'tip3p.xml', 'gaff.xml')
[template, ffxml] = generateResidueTemplate(molecule)
forcefield.registerResidueTemplate(template)
forcefield.loadFile(StringIO(ffxml))
system = forcefield.createSystem(topology)
```
and the residue template generator plugin
```python
# Initialize ForceField
forcefield = ForceField('amber99sb.xml', 'tip3p.xml', 'gaff.xml')
from openmoltools.forcefield_generators import gaffTemplateGenerator
forcefield.registerTemplateGenerator(gaffTemplateGenerator)
# Now, when you need to create a new System...
system = forcefield.createSystem(topology)
```
should work.

I've also added a convenience function to go from a `Residue` to an `OEMol`:
```python
molecule = generateOEMolFromTopologyResidue(residue)
```
though it only works with residues that are separate molecules and not polymeric molecules connected to other residues.

`generateResidueTemplate()` also supports an optional argument `residue_atoms` where you can provide a list of atoms that form the polymeric repeating unit of the residue.  This would allow us to pass an `OEMol` molecule for, say, a modified amino acid with capping groups, along with a list of the atoms that are not capping groups, and it will parameterize the residue and make sure the charges are integral.  This feature hasn't been tested yet, but it should be relatively easy to get working when we need it.

**Comment by jchodera** [comment]
Both schemes now work locally on the latest ommparams branch of parmed. I just have to build you a parmed-dev conda package and then you guys should be good to go!

**Comment by jchodera** [comment]
I've just built the [`parmed-dev` conda package](https://anaconda.org/omnia/parmed-dev) and checked the `ForceField` generators into [`openmoltools`].  The `openmmtools-dev` package should be built soon.

Unfortunately, we've run into a new snag: `ffxml` files written with ParmEd are incompatible with the `ffxml` files currently in the `openmm` and `openmm-dev` packages because the number of significant digits specified for for the 1-4 nonbonded scaling factors are not the same: https://github.com/pandegroup/openmm/issues/1367

This means that small molecules in vacuum or GBSA should work just fine (provided you use the `gaff.xml` in `openmoltools/parameters/gaff.xml`), but we will need to wait for @rafwiewiora to convert some AMBER protein and water parameter/topology files over to the "new format" using ParmEd for them to be compatible with `gaff.xml`.

Note that `openmmtools-dev` is a linux-only package right now, but we can enable `osx` travis tests if we want `osx` package builds too.  Just let me know if we need this.

**Comment by jchodera** [comment]
Examples of using the forcefield generators can be found in the tests:
* [Generate a residue template from an `OEMol`](https://github.com/choderalab/openmoltools/blob/master/openmoltools/tests/test_forcefield_generators.py#L155-L168)
* [Use a `residueTemplateGenerator` plugin to generate templates on the fly](https://github.com/choderalab/openmoltools/blob/master/openmoltools/tests/test_forcefield_generators.py#L201-L211)

**Comment by jchodera** [comment]
`openmoltools-dev` conda package: https://anaconda.org/omnia/openmoltools-dev/files

Note this requires `parmed-dev`, so you may have to `conda remove --yes parmed` first.

**Comment by jchodera** [comment]
There is now a fix for https://github.com/pandegroup/openmm/issues/1367 via PR https://github.com/pandegroup/openmm/pull/1368 but OpenMM currently has a feature freeze, so we're not sure when this will go in.

**Comment by jchodera** [comment]
https://github.com/pandegroup/openmm/pull/1368 has been merged into OpenMM, so you should be good to use `openmoltools-dev` and `openmm-dev` together for this feature.  I just tested to confirm that the current AMBER protein forcefields work fine alongside the small molecule parameters generated using the new template generators.  You'll need `gaff.xml`, which is [here](https://github.com/choderalab/openmoltools/tree/master/openmoltools/parameters).

I'm still adding some more tests to make sure energies are identical to what we get through AMBER, but I think you should be good to go at this point.  Re-open the issue if any fixes are needed.

**Comment by jchodera** [comment]
I just fixed a bug in the forcefield generators where the charges had accidentally been set to zero.  You'll want to update your conda packages (making sure to do a `conda clean -pltis --yes` first).

https://github.com/choderalab/openmoltools/pull/185

**Comment by pgrinaway** [comment]
Ok, I think this is now implemented.
