### ISSUE TITLE
CustomNonbondedForce discrepancies between CPU and OpenCL for OpenMM 7.4.1

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#679]
We noticed that `PROJ13409/RUN2/CLONE0/results0-20200531-002933/science.log` shows a large RMSE force error:
```
  Checking core state against reference...
ERROR:Force RMSE error of 13.7141 with threshold of 5
```
It turns out that this is due to a discrepancy in force index 8 (`CustomNonbondedForce`) in OpenMM 7.4.1:
```
CPU                  8 CustomNonbondedForce                             : potential energy     -112.274 kJ/mol  : force mag     1868.812 kJ/mol/nm
OpenCL               8 CustomNonbondedForce                             : potential energy     -127.883 kJ/mol  : force mag     1220.945 kJ/mol/nm
CUDA                 8 CustomNonbondedForce                             : potential energy     -112.274 kJ/mol  : force mag     1868.819 kJ/mol/nm
```
However, with OpenMM 7.4.2, the discrepancy is eliminated:
```
CPU                  8 CustomNonbondedForce                             : potential energy     -112.274 kJ/mol  : force mag     1868.812 kJ/mol/nm
OpenCL               8 CustomNonbondedForce                             : potential energy     -112.274 kJ/mol  : force mag     1868.822 kJ/mol/nm
CUDA                 8 CustomNonbondedForce                             : potential energy     -112.274 kJ/mol  : force mag     1868.819 kJ/mol/nm
```
From what I can tell, the commits that would have impacted this are https://github.com/openmm/openmm/commit/3205355b27d0c0e82771bc8c14c147126b6c2876 or https://github.com/openmm/openmm/commit/a1460b0b62cee687b593e4db55bb94624a3f2c21, which corresponds to PRs https://github.com/openmm/openmm/pull/2553 or https://github.com/openmm/openmm/pull/2631. 

The latter fix is included in the upcoming core22 0.0.6, but I'll try to make sure the other one is included as well. It may be easier just to upgrade core22 0.0.6 to use OpenMM 7.4.2 to eliminate any potential for inconsistencies.

cc https://github.com/FoldingAtHome/openmm-core/issues/258

**Comment by ijpulidos** [comment]
This should've been solved already. Closing.
