### ISSUE TITLE
Examples are out of date

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#684]

**Comment by WG150** [comment]
The script referenced in the examples/host-guest example `README` is wrong. It should be `prepare_host_guest.py`.

**Comment by WG150** [comment]
Not sure if this an issue with my setup but I seem to get `TypeError` and `ValueError` in the examples/Atom-mapping.ipynb Jupyter Notebook when trying:
```python
from perses.utils.smallmolecules import render_atom_mapping
```

(Using `openeye-toolkits` version `2019.10.2`)

Here is the full error output:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/opt/anaconda3/envs/perses/lib/python3.6/site-packages/openmoltools/amber.py in find_gaff_dat()
    272         try:
--> 273             AMBERHOME = os.path.split(full_path)[0]
    274             AMBERHOME = os.path.join(AMBERHOME, "../")

~/opt/anaconda3/envs/perses/lib/python3.6/posixpath.py in split(p)
    106     everything after the final slash.  Either part may be empty."""
--> 107     p = os.fspath(p)
    108     sep = _get_sep(p)

TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-186b929aa616> in <module>
      1 # from perses.utils.openeye import createOEMolFromSDF
----> 2 from perses.utils.smallmolecules import render_atom_mapping
      3 from perses.utils.openeye import smiles_to_oemol
      4 from perses.rjmc.topology_proposal import AtomMapper
      5 from openeye import oechem

~/opt/anaconda3/envs/perses/lib/python3.6/site-packages/perses-0.6.0.dev0-py3.6.egg/perses/utils/__init__.py in <module>
      1 from perses.utils.data import *
----> 2 from perses.utils.openeye import *

~/opt/anaconda3/envs/perses/lib/python3.6/site-packages/perses-0.6.0.dev0-py3.6.egg/perses/utils/openeye.py in <module>
      9 
     10 from openeye import oechem, oegraphsim
---> 11 from openmoltools.openeye import generate_conformers
     12 from simtk import openmm, unit
     13 from simtk.openmm import app

~/opt/anaconda3/envs/perses/lib/python3.6/site-packages/openmoltools/__init__.py in <module>
     24 """
     25 
---> 26 from openmoltools import amber_parser, system_checker, utils, packmol, openeye, amber, cirpy, gromacs, schrodinger

~/opt/anaconda3/envs/perses/lib/python3.6/site-packages/openmoltools/openeye.py in <module>
      3 import mdtraj as md
      4 from openmoltools.utils import import_, enter_temp_directory, create_ffxml_file
----> 5 from openmoltools.amber import run_antechamber
      6 import logging
      7 

~/opt/anaconda3/envs/perses/lib/python3.6/site-packages/openmoltools/amber.py in <module>
    281     return os.path.join(AMBERHOME, 'dat', 'leap', 'parm', 'gaff.dat')
    282 
--> 283 GAFF_DAT_FILENAME = find_gaff_dat()
    284 
    285 

~/opt/anaconda3/envs/perses/lib/python3.6/site-packages/openmoltools/amber.py in find_gaff_dat()
    274             AMBERHOME = os.path.join(AMBERHOME, "../")
    275         except:
--> 276             raise(ValueError("Cannot find AMBER GAFF"))
    277 
    278     if AMBERHOME is None:

ValueError: Cannot find AMBER GAFF
```

**Comment by schallerdavid** [comment]
In the cdk2 example, repex appears to work! An error is raised when using sams or nonequlibrium. Also,  the cdk2_sams.yaml references to the wrong protein and ligand file.

## Error message
`2020-06-03 12:36:30,558:(2.72s):relative_setup:	preparing to add solvent
Traceback (most recent call last):
  File "/home/david/miniconda2/envs/perses/bin/perses-relative", line 8, in <module>
    sys.exit(run())
  File "/home/david/miniconda2/envs/perses/lib/python3.7/site-packages/perses/app/setup_relative_calculation.py", line 623, in run
    setup_dict = run_setup(setup_options)
  File "/home/david/miniconda2/envs/perses/lib/python3.7/site-packages/perses/app/setup_relative_calculation.py", line 380, in run_setup
    trajectory_directory=trajectory_directory, trajectory_prefix=setup_options['trajectory_prefix'], nonbonded_method=setup_options['nonbonded_method'])
  File "/home/david/miniconda2/envs/perses/lib/python3.7/site-packages/perses/app/relative_setup.py", line 284, in __init__
    self._complex_topology_old, self._complex_positions_old,phase='complex')
  File "/home/david/miniconda2/envs/perses/lib/python3.7/site-packages/perses/app/relative_setup.py", line 666, in _solvate_system
    modeller.addSolvent(self._system_generator.forcefield, model=model, padding=self._padding, ionicStrength=0.15*unit.molar)
  File "/home/david/miniconda2/envs/perses/lib/python3.7/site-packages/simtk/openmm/app/modeller.py", line 485, in addSolvent
    system = forcefield.createSystem(self.topology)
  File "/home/david/miniconda2/envs/perses/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 1164, in createSystem
    if generator(self, res):
  File "/home/david/miniconda2/envs/perses/lib/python3.7/site-packages/openmmforcefields/generators/template_generators.py", line 528, in generator
    forcefield.loadFile(self.gaff_xml_filename)
  File "/home/david/miniconda2/envs/perses/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 256, in loadFile
    self.registerAtomType(type.attrib)
  File "/home/david/miniconda2/envs/perses/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 390, in registerAtomType
    raise ValueError('Found multiple definitions for atom type: '+name)
ValueError: Found multiple definitions for atom type: c`

**Comment by hannahbrucemacdonald** [comment]
@schallerdavid - CDK2 has some weird phospho-residue in it called TPO! It needs the forcefield files like this:

```
forcefield_files:
    - amber/ff14SB.xml # ff14SB protein force field
    - amber/tip3p_standard.xml # TIP3P and recommended monovalent ion parameters
    - amber/tip3p_HFE_multivalent.xml # for divalent ions
    - amber/phosaa10.xml # HANDLES THE TPO
```


Where `phosaa10.xml` is the important bit. I hadn't changed this in sams or nonequilibrium yaml file before, but I have now! And I've fixed the protein/ligand filenames too for sams!

**Comment by hannahbrucemacdonald** [comment]
@WG150 
hmmm can you just try `antechamber` and see that you've got it installed? Also could you do

`conda list openmoltools` please?

**Comment by WG150** [comment]
I think that in `examples/cdk2-example/` the `trajectory_directory` in the `cdk2_repex.yaml` file name needs to be changed to `cdk2_repex_hbonds`.

**Comment by hannahbrucemacdonald** [comment]
@WG150 would you be happy to make that fix in the `fix-examples` branch?

**Comment by WG150** [comment]
In the Jupyter Notebook `Atom-mapping.ipynb` (/examples/atom-mapping) the `.sdf` file that `molecules = Molecule.from_file('Bace_ligands_shifted.sdf')` is loading is not in the working directory.

**Comment by WG150** [comment]
For all python scripts in `examples/dualtopology` I recieve an error when importing the `dualtopology` module:

```python
Traceback (most recent call last):
  File "amino_acid_example.py", line 1, in <module>
    from perses import dualtopology
ImportError: cannot import name 'dualtopology'
```

**Comment by hannahbrucemacdonald** [comment]
Ok I have no idea what dualtopology does so I've gotten rid of it, it was 5 years old and we can't do dual topology in perses...

I've fixed Atom-mapping.ipynb! There is now a wget inside the notebook so it's a bit tidier, its a good script to play with to understand how we do single topology, looking at oechem.oexpropts:

https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEExprOpts.html

Maybe try with a few other molecules too to see what's good

**Comment by WG150** [comment]
The `README` in `examples/freesolv` needs to be more descriptive. There are python scripts in the directory that are not referenced and it is unclear where to start. Also the bash script referenced in the `README` (`prepare_freesolv.sh`) references `mols2pdf.py` and `molgrep.py` scripts that don't exist.

**Comment by WG150** [comment]
`example/host-guest` is missing the `setup_relative_calculation.py` script described in the `README`.

**Comment by WG150** [comment]
In `examples/neq-switching/run_equilibrium_setup.py` there is an import error at: 
```python
from perses.rjmc.topology_proposal import TopologyProposal, SystemGenerator
```
It looks like `SystemGenerator` should be `ProposalEngine` now?

**Comment by hannahbrucemacdonald** [comment]
Ah we now use the SystemGenerator from openmmforcefields 


`from openmmforcefields.generators import SystemGenerator`

**Comment by WG150** [comment]
> Ah we now use the SystemGenerator from openmmforcefields
> 
> `from openmmforcefields.generators import SystemGenerator`

I've now addressed this in #683.

At the end of the script it also seems that `AtomMapper` is being used but not imported anywhere:
```python
atom_mapper = AtomMapper(mol_list)
```

**Comment by WG150** [comment]
`examples/relay-example` needs documentation.

**Comment by WG150** [comment]
I'm getting a weird error in `examples/rjmc/run_example.py` at line 38 in `oemol_to_openmm_system`:

```python
prmtop_file, inpcrd_file = openmoltools.utils.run_tleap(molecule_name, gaff_mol2, frcmod)
    prmtop = app.AmberPrmtopFile(prmtop_file)
```

I get the error: 

```python
Unexpected errors encountered running AMBER tool. Offending output:
Exiting LEaP: Errors = 0; Warnings = 0; Notes = 0.
Traceback (most recent call last):
  File "run_example.py", line 211, in <module>
    run()
  File "run_example.py", line 66, in run
    initial_molecule, "ligand_old"
  File "run_example.py", line 51, in oemol_to_openmm_system
    molecule_name, gaff_mol2, frcmod
  File "/Users/williamglass/opt/anaconda3/envs/perses/lib/python3.6/site-packages/openmoltools/amber.py", line 465, in run_tleap
    check_for_errors( output, other_errors = ['Improper number of arguments'] )
  File "/Users/williamglass/opt/anaconda3/envs/perses/lib/python3.6/site-packages/openmoltools/amber.py", line 257, in check_for_errors
    raise(RuntimeError("Error encountered running AMBER tool. Exiting."))
RuntimeError: Error encountered running AMBER tool. Exiting.
```

After looking up `openmoltools.amber.run_tleap` it seems this usage is ok (i.e. correct number of arguments)... any idea what's causing this error?

**Comment by jaimergp** [comment]
What `ambertools` is installed in the environment? Do you have access to the tleap logs? They should be somewhere in the temporary directory.

**Comment by hannahbrucemacdonald** [comment]
Could you try use this function instead?

https://github.com/choderalab/perses/blob/bf6fa5463521a0376d1afe0e22a6ea1e4ab5ee07/perses/utils/openeye.py#L202

**Comment by hannahbrucemacdonald** [comment]
I think we made good progress on this, so closing for now
