### ISSUE TITLE
Other things for JDC to do?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#69]
I've finished the forcefield generators for small molecules, so I am just trying to figure out what else you guys need me to do.

I only have one item remaining on my list from [the design thread](https://github.com/choderalab/perses/issues/61#issuecomment-168235604):
* A dual-topology `AlchemicalFactory` for [`alchemy`] (https://github.com/choderalab/alchemy/issues/21) to allow us to try different RJMC schemes that may eliminate discontinuous jumps in charges, types, and bond parameters

Anything else I was slated to do?

**Comment by pgrinaway** [comment]
Closing for now.
