### ISSUE TITLE
Where is `mapperkinase3.json`

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#691]
It's used in `testsystems.py:run_kinase_inhibitors`

and it opens/the test works on ghactions, but I can't _find_ the file so can't run the same test locally...

**Comment by jchodera** [comment]
I don't think I added that file. @dominicrufa ? Maybe you just forgot to check this in?

The goal of the `SystemGenerator` JSON file is to just to _use_ the file if it exists, and to create it if it doesn't. We should make sure this behaves this way.

**Comment by hannahbrucemacdonald** [comment]
So @jaimergp did some digging -- the function that _makes_ it has been deleted, the function that _uses_ it isn't in the test suite --- it's from Patrick's days. I'll tidy it up
