### ISSUE TITLE
Running YANK with CUDA

### ISSUE THREAD

**Issue by mmagithub** [choderalab/perses#692]
Hi,
I am wondering if there is a specific recipe to follow to install and run YANK (Anaconda) with CUDA enabled. It seems that the different CUDA / openmm / pymbar versions create several issues and inconsistencies.
I have tried to install the most recent version as outlined on the web page I keep getting this error:
############
return _openmm.Platform_getPlatformByName(name)
Exception: There is no registered Platform called "CUDA"
##############
I tried to load/unload different modules, upgrade or downgrade YANK or openmm, trying different CUDA versions, setting the plugin / nvcc, but no success?
Any recommendations?

Thanks,
Marawan

**Comment by hannahbrucemacdonald** [comment]
Hey - this is the perses issue tracker, I would suggest posting this to the YANK issue tracker. Could you let us know which versions of openmm and CUDA you are trying to use?


Thanks!


Hannah

**Comment by hannahbrucemacdonald** [comment]
Closing issue as doesn't relate to Perses
