### ISSUE TITLE
tests failing due to expired `oe_license`

### ISSUE THREAD

**Issue by dominicrufa** [choderalab/perses#703]
can someone update the oe license so we can get back to passing tests? i think that it has to be encrypted?
The tailed traceback for all tests is:

> LICENSE: No valid license found for oechem
> LICENSE: File(s) used: /home/runner/oe_license.txt
> LICENSE: Closest license failed because:
> LICENSE: expiration date
> ##[error]Process completed with exit code 1.

**Comment by hannahbrucemacdonald** [comment]
@jaimergp --- would you mind encrypting this file again? I think you had it as an organizational secret before? Thanks!

**Comment by jaimergp** [comment]
Not at home right now, but you can change [this line](https://github.com/choderalab/perses/blob/master/.github/workflows/CI.yaml#L56) so it uses `secrets.OE_LICENSE` instead of `secrets.ENC_OE_LICENSE`. That's the `ENC`-less version is the organization-wide one.
