### ISSUE TITLE
Don't use value_with_units/value_with_units.unit

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#73]
Let's not use expressions like
```python
value/value.unit
```
in the code.  There's just too much potential for these being in different units and getting converted to arbitrary units.  Let's just define `kT` somewhere convenient and use that throughout:
```python
value/kT
```

**Comment by jchodera** [comment]
Also, for things like log probabilities and log weights, let's use unitless floats (in units of kT).

**Comment by pgrinaway** [comment]
Completed in #263
