### ISSUE TITLE
Allow both old and new molecule conformations to be specified

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#734]
@dominicrufa : Did you say it was easy to you to add an option to perses to allow us to use the specified external geometries for old and new ligands? If so, we could use that now, and integrate the constrained Omega code later!

**Comment by dominicrufa** [comment]
as long as the geometries of the old/new ligands are specified (and the positions of the mapped atoms are the same), then it shouldn't be too much work to just bypass the geometry engine probabilistic atom placement and make it deterministic. if we'll use this in the immediate future, just commission it and i can probably get it done by the time i go on break at the end of the week.

**Comment by mikemhenry** [comment]
Fixed in PR 770
