### ISSUE TITLE
Refactor to have system creation separated from Topology creation

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#74]
There are a hojillion places where `tleap` and `antechamber` are called in the current code.  It would be great to refactor these to all use a single factory to generate a `System` from a `Topology` using the new `ForceField` with GAFF plugin generator.  If the `ForceField` object is persistent in this factory, the antechamber calls will be cached automatically, though you could also cache `Topology : System` pairs via memoization if you wanted.

**Comment by jchodera** [comment]
We will want to get rid of the [`_build_system()` methods](https://github.com/choderalab/perses/blob/master/perses/rjmc/topology_proposal.py#L912-L967) in `TopologyProposal` so that system building is handled by this separate factory.

This should significantly simplify the class hierarchy since we no longer need classes like [`SmallMoleculeProteinComplex`](https://github.com/choderalab/perses/blob/master/perses/rjmc/topology_proposal.py#L912) `TopologyProposal` subclasses.  The topology proposal classes should all be based on how we are selecting new molecules, as in our [design discussion issue thread](https://github.com/choderalab/perses/issues/61#issuecomment-165308265):
```
* TopologyProposal
   * SmallMoleculeTopologyProposal
      * SmallMoleculeLibrary
      * CombinatorialLibrary
      * ReactionAwareSynthesis
   * PolymerTopologyProposal
      * PointMutation
      * PeptideLibrary
```

**Comment by pgrinaway** [comment]
This refactor was completed in #83 and #86.
