### ISSUE TITLE
hybrid_{complex,solvent}.pdb written by FAH generation code is missing CONECT records for ligands B state

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#752]
The current `hybrid_{complex,solvent}.pdb` written by the FAH generation code appears to be missing `CONECT` records for the ligand B state. It also incorrectly writes the `MOL` residue as `ATOM` instead of `HETATM`.

@dominicrufa : Any idea where I would fix this? It would seem to be an issue with the OpenMM topology we use for writing if we're writing via OpenMM's `PDBFile`.

**Comment by proteneer** [comment]
Lack of CONECT records is usually due to forgetting to call writeFooter()

**Comment by mikemhenry** [comment]
Is there an example or code snippet you could point me to @jchodera that demonstrates this behavior?

**Comment by jchodera** [comment]
@mikemhenry : Sure!

Here's an example output from just the solvent phase of the FAH setup pipeline:
[solvent-phase-fah-example.zip](https://github.com/choderalab/perses/files/6535638/solvent-phase-fah-example.zip)

You can either inspect the `CONECT` records for `hybrid_solvent.pdb` (representing the hybrid ligand in solvent) manually, or load it up into pymol by first running [`set connect_mode, 1` to only use `CONECT` records for bonding](https://pymolwiki.org/index.php/Connect_mode). You'll see there are no `CONECT` records between atoms in the new molecule. There also appear to be distorted connections between other atoms, which may reflect the presence of these `CONECT` records with incorrect offsets:
![image](https://user-images.githubusercontent.com/3656088/119421887-954e3d80-bcb4-11eb-84c3-8a9d67fb2497.png)

I'll post example code to generate this output in the next threaded message.

**Comment by jchodera** [comment]
This example may be much more complicated than the minimal necessary example to reproduce this, so I apologize---I haven't had time to cut it down drastically:
[minimal-neq-sprint.zip](https://github.com/choderalab/perses/files/6535657/minimal-neq-sprint.zip)

Unpacking this will yield an `environment.yml` you can use to create a matching environment on `linux` for testing. (You might need to take a coffee or lunch break in the middle, even if you use `mamba`.) The just environment includes `perses=0.9.0`, `fah-xchem`, and its dependencies.

Once configured, you should be able to set up an example with 
```
python 05-prepare-single-transformation.py 0
```
to generate `13451/RUNS/RUN0/` containing a similar (but not identical) example to the one above.

**Comment by mikemhenry** [comment]
Working on setting up the environment and ran into two issues:

* Arsenic isn't packaged on pypi (there is a package with that name but it is unrelated to what we are doing) or conda-forge, so I just installed the version specified from github with `git+https://github.com/openforcefield/Arsenic.git@0.1.0`

* There is no 0.0.2.2 version for `fragalysis-api` on pypi or conda-forge https://pypi.org/project/fragalysis-api/#history There are no releases or tags on their github page so I'll just install version `0.1.1` and hope for the best

* There is no `pandda-gemmi` package, there is a `pandda-2` and `gemmi` package, I'll install the newest version of `pandda` from source `pip install --no-dependencies git+https://bitbucket.org/pandda/pandda.git` and `gemmi` from pypi and see if that works. 

* https://github.com/choderalab/fah-xchem seems to be needed,
```
json/minimal-neq-sprint-stereofilter-P0033-dimer-neutral-restrained.json
Traceback (most recent call last):
  File "05-prepare-single-transformation.py", line 99, in <module>
    from fah_xchem.schema import CompoundSeries
ModuleNotFoundError: No module named 'fah_xchem'
```
So I installled that from source `pip install git+https://github.com/choderalab/fah-xchem.git`

That got me further, but then crashed on

```
    from openff.toolkit.topology import Molecule
ModuleNotFoundError: No module named 'openff'
```

So then I installed the toolkit with `mamba install openff-toolkit` and got into an issue with the versions of openforcefield installed didn't work with the new toolkit.

So instead I just decided to download things as I needed them:

```
mamba create -n perses-debug-no-connect
conda activate perses-debug-no-connect
mamba install python=3.8
pip install git+https://github.com/choderalab/fah-xchem.git
mamba install -c openeye openeye-toolkits
mamba install pyyaml
mamba install perses
python 05-prepare-single-transformation.py 0

  File "/home/mmh/miniconda3/envs/perses-debug-no-connect/lib/python3.8/site-packages/perses/app/relative_setup.py", line 314, in __init__
    from openforcefield.topology import Molecule
ModuleNotFoundError: No module named 'openforcefield'
```

Which now makes me realize, I broke the `perses` release :( and forgot to update the pins on openff toolkit to make sure we only install the new packages with the correct name space.

**Comment by mikemhenry** [comment]
I let it run for an hour and 15 minutes, this was the last log message: `2021-05-26 12:04:32,259:(0.01s):root:Starting to equilibrate for 2000000.0 fs` and I don't see any pdb files:
```
ll 13450/RUNS/RUN0/   
total 37M
-rw-rw-r-- 1 mmh mmh  35M May 26 12:03 htf.npz
-rw-rw-r-- 1 mmh mmh 1003 May 26 12:03 integrator.xml.bz2
-rw-rw-r-- 1 mmh mmh 2.4M May 26 12:03 system.xml.bz2
```

**Comment by mikemhenry** [comment]
RE perses release, things are actually okay, but the pins do not prevent you from installing conflicting packages, will fix this in the next release

**Comment by jchodera** [comment]
> Arsenic isn't packaged on pypi (there is a package with that name but it is unrelated to what we are doing) or conda-forge, so I just installed the version specified from github with git+https://github.com/openforcefield/Arsenic.git@0.1.0

Good point! Let's try to get `arsenic` onto `conda-forge`. 
I've just connected you and David Dotson with Lorenzo D'Amore (the new OpenFF postdoc heading up protein-ligand benchmarking). Hopefully he can help maintain the science parts, but we can help get it onto `conda-forge`.

**Comment by jchodera** [comment]
> There is no 0.0.2.2 version for fragalysis-api on pypi or conda-forge https://pypi.org/project/fragalysis-api/#history There are no releases or tags on their github page so I'll just install version 0.1.1 and hope for the best
> There is no pandda-gemmi package, there is a pandda-2 and gemmi package, I'll install the newest version of pandda from source pip install --no-dependencies git+https://bitbucket.org/pandda/pandda.git and gemmi from pypi and see if that works.

These packages aren't required by `perses`, but they _are_ required for `fah-xchem`. For now, I've just been putting these `pip+git` entries into an `environment.yml`, but once things stabilize there, it might be useful for @dotsdl to help me work with the Fragalysis devs to get stable releases of these packages onto PyPI and conda-forge.

For now, this functionality is really an optional feature of fah-xchem for pushing structures to fragalysis, and should not be a significant concern right now for perses.

My apologies for neglecting to mention how I initialized part of this environment! I had used this `environment.yml` from `fah-xchem`:
https://github.com/choderalab/fah-xchem/blob/master/environment.yml

**Comment by jchodera** [comment]
> I let it run for an hour and 15 minutes, this was the last log message: 2021-05-26 12:04:32,259:(0.01s):root:Starting to equilibrate for 2000000.0 fs and I don't see any pdb files:

Whoops! You'll want to change the `05-prepare-single-transformation.py` script to reduce the number of steps.
From
```
options['num_equilibration_iterations'] = 2000 # 2 ns
```
to
```
options['num_equilibration_iterations'] = 1 # 1 ps
```

**Comment by mikemhenry** [comment]
I was able to get things to run and reproduce the error. I did a quick look and nothing obvious stood out, we are using mdtraj to save the pdb, I'm guessing we are missing the bonds somewhere in our representation of the topology. Does this error only show up when using the FAH generation code? Just to save future Mike some time, this is the part in the FAH specific code where the pdb file is saved: https://github.com/choderalab/perses/blob/master/perses/app/fah_generator.py#L415-L420 and where we generate the hybrid topology https://github.com/choderalab/perses/blob/master/perses/annihilation/relative.py#L1933

**Comment by mikemhenry** [comment]
Write old pdb and new pdb + mapping indices from hybrid to the old and hybrid from the new
@zhang-ivy has some code snippets for this

**Comment by zhang-ivy** [comment]
@ijpulidos : Here are code snippets that will be useful for adding the features John described. You'll probably want to insert some version of these code snippets near [here](https://github.com/choderalab/perses/blob/master/perses/app/fah_generator.py#L415-L420)

Note that these code snippets assume that we've instantiated a `HybridTopologyFactory`  object (which i've called `htf` here), but given the way the `fah_generator.py` code (linked above) is set up, you can use replace `htf` here with `htfs[phase]`

1) Write PDBs of the old/new topology and positions
```python
    import mdtraj as md
    # 'pos' below is defined here: https://github.com/choderalab/perses/blob/master/perses/app/fah_generator.py#L412-L413
    traj = md.Trajectory(htf.old_positions(pos), md.Topology.from_openmm(htf._topology_proposal.old_topology))
    traj.save('blah.pdb')

```
Note: For saving the new PDB, replace `htf.old_positions(pos)` with `htf.new_positions(pos)` and `htf._topology_proposal.old_topology` with `htf._topology_proposal.new_topology`

2) Save the mappings (not sure which format is best) for hybrid to old indices and hybrid to new indices.
Here's how to access the dictionaries:
```python
htf._hybrid_to_old_map
htf._hybrid_to_new_map
```
Happy to review once you've incorporated these changes!

**Comment by ijpulidos** [comment]
I am not able to reproduce the issue, I think I'm hitting another bug before I get any PDBs. I will be reporting it in another issue. But I just wonder how you managed to get a PDB from it, since after I run `python 05-prepare-single-transformation.py 0` I get this error
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/perses-fah-hybrid-test/bin/perses-fah", line 33, in <module>
    sys.exit(load_entry_point('perses', 'console_scripts', 'perses-fah')())
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/fah_generator.py", line 498, in run
    run_neq_fah_setup(**setup_options)
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/fah_generator.py", line 412, in run_neq_fah_setup
    pos = state.getPositions(asNumpy=True)
UnboundLocalError: local variable 'state' referenced before assignment
```
(Which I think is a real bug, we are catching the exception and `state` can be undefined). And still no PDBs in the created directory, all I have is:
```
13450
└── RUNS
    └── RUN0
        ├── htf.npz
        ├── integrator.xml.bz2
        └── system.xml.bz2
```
I tried checking if this part of the `fah_generator.py` was changed recently, but it doesn't seem to be the case, as far as I can see. Any ideas what I may be missing? Thanks.

Note: Complete log in https://gist.github.com/ijpulidos/fa7561ada5381b1079af89da3af54083

**Comment by jchodera** [comment]
It looks like the OpenMM `Context` is just failing to be created. Check out the end of the log:
```
2021-08-03 13:26:50,123:(0.04s):root:There is no registered Platform called "OpenCL"
Traceback (most recent call last):
  File "/home/mefisto/miniconda3/envs/perses-fah-hybrid-test/bin/perses-fah", line 33, in <module>
    sys.exit(load_entry_point('perses', 'console_scripts', 'perses-fah')())
  File "/home/mefisto/workdir/ChoderaLab/repos/perses/perses/app/fah_generator.py", line 498, in run
    run_neq_fah_setup(**setup_options)
  File "/home/mefisto/workdir/ChoderaLab/repos/perses/perses/app/fah_generator.py", line 412, in run_neq_fah_setup
    pos = state.getPositions(asNumpy=True)
UnboundLocalError: local variable 'state' referenced before assignment
```
The first line suggests that the requested platform---OpenCL---is not available. 

The code simply [skips creating the new `state` variable](https://github.com/choderalab/perses/blob/master/perses/app/fah_generator.py#L397-L410), which can't possibly be the right thing to do here. Presumably, if creating the context fails, it should just setup the calculation without minimizing locally first.

**Comment by ijpulidos** [comment]
So, it took me a while to get things running but I finally made the changes (check PR #839 ). The visualization PDBs generated by the changes are as follow (green is new), for the solvent phase.

![image](https://user-images.githubusercontent.com/2949729/128582374-6772a726-3858-4da2-96c6-aa8dce0cd851.png)

Whereas if you want to check the serialized atom mappings you would have to do something like
```python
npzfile = np.load('/path/to/hybrid_atom_mappings.npz', allow_pickle=True)
npzfile.files
['hybrid_to_old_map', 'hybrid_to_new_map']
npzfile['hybrid_to_new_map'].flat[0]
```
Which I believe is not that friendly but just to stick to numpy object files. Maybe in the future we can think of better formats for serialization (JSON, HDF?).

**Comment by jchodera** [comment]
Sounds great! We can close this with #839 but perhaps should open another issue to discuss serialization formats?

**Comment by ijpulidos** [comment]
@jchodera  Yes, it seems that we already have that in #668
