### ISSUE TITLE
Add python 3.8 / 3.9 support

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/perses#758]
With python3.8:

```
➜ conda install -c omnia perses
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed 

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - perses -> python[version='3.5.*|3.6.*|3.7.*|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
``` 

We should ensure that tests pass with python 3.8 and then create a release on the `omnia` channel that supports python 3.8 

We should also consider using `conda-forge` to automate builds (assuming all the dependices provided by `omnia` have migrated to `conda-forge`

**Comment by jchodera** [comment]
Note that we are migrating away from `omnia` because it has been deprecated and is no longer being maintained now that OpenMM and OpenFF have moved to conda-forge.

This error is probably because some package we currently still depend on has not been built for Python 3.8, but I'm not sure which one it is. It might be one of the deprecated legacy packages like https://github.com/choderalab/openmoltools that we are trying to purge all instances of in perses.

**Comment by jchodera** [comment]
This should be fixed by https://github.com/conda-forge/perses-feedstock/pull/2

**Comment by mikemhenry** [comment]
With our 0.9.0 release on  conda-forge, python 3.9 is supported. Once openeye releases their toolkit with python 3.9 or https://anaconda.org/OpenEye/OpenEye-toolkits/files (currently in the beta channel) then 
`conda install --yes -c conda-forge -c openeye perses openeye-toolkits` will give you a python3.9 environment. For now the solver creates a python 3.7 environment since the openeye toolkit requites python 3.7
`Problem: package openeye-toolkits-2020.2.2-py37_0 requires python >=3.7,<3.8.0a0, but none of the providers can be installed`
