### ISSUE TITLE
Missing a contribution to sampler acceptance probability?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#77]
I think we're missing a critical contribution in the [acceptance criteria for `test_sampler`](https://github.com/choderalab/perses/blob/master/perses/tests/test_sampler.py#L157).  While we include the ratio of proposal probabilities in the geometry proposal, I don't believe we include the difference in potential energies between the old and new conformations.

This results in some pretty weird geometries when the trajectory is visualized.

**Comment by jchodera** [comment]
Notably, this is the difference in potential energies for the alchemically eliminated forms of these molecules, so the majority of the difference in potential arises from the new valence terms (which should cancel to some degree with the ratio of proposal probabilities).

**Comment by juliebehr** [comment]
I believe this was addressed in https://github.com/choderalab/perses/pull/223 here: https://github.com/choderalab/perses/commit/4bf4e7ef52694e560bf6b15f5bb96f276a453f24

**Comment by jchodera** [comment]
I've actually completely lost track of what all the contributions are called in the code and how they map to actual contributions to the mathematically-derived acceptance probability. Perhaps we need to document that?

**Comment by pgrinaway** [comment]
>Perhaps we need to document that?

Yep. I think we need to take a detailed pass through the code, ensuring everything is properly documented, once we clear out some of the smaller issues. This will help identify:

* Test omissions
* API flaws
* Undocumented code
* Bugs in implementations
* Problems with code readability

I'm happy to start doing this as soon as the smaller issues are closed out.

**Comment by jchodera** [comment]
I think @pgrinaway and @juliebehr said this was fixed in our last meeting. Reopen if needed.
