### ISSUE TITLE
Check factorization of partition function

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/perses#792]
We can use the code from `timemachine` as a guide for our implementation.

https://github.com/proteneer/timemachine/blob/c08bfda717d535b0ae9c0ec71f661138819192fe/fe/topology.py#L452-L529

@jchodera if you let me know where we should add this I can take a stab at it.

**Comment by jchodera** [comment]
Fixed by #809.

**Comment by jchodera** [comment]
We determined the checks in https://github.com/proteneer/timemachine/blob/c08bfda717d535b0ae9c0ec71f661138819192fe/fe/topology.py#L452-L529 are too restrictive in that they only permit a _single_ substituent to be alchemically modified at a time, whereas perses permits multiple substituents to be simultaneously changed. Our solution in #809 is therefore more general.
