### ISSUE TITLE
When using geometry-based mapping, de-map problematic transformations

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#805]
Currently, the geometry-based mapping can cause some problematic transformation mappings to be used, e.g.:
![image](https://user-images.githubusercontent.com/3656088/121083657-b4b59200-c7ad-11eb-90cf-9b4d794189fa.png)
We should make sure to de-map these.

Synergizes with #792, which can catch these issues more generally.

**Comment by jchodera** [comment]
Here's another problematic map, which maps only part of the ring between initial and final molecules:
![image](https://user-images.githubusercontent.com/3656088/122515809-d2130900-cfc2-11eb-9ca7-5751b4aa4659.png)
This leads to problematic overlap in solvent:
![image](https://user-images.githubusercontent.com/3656088/122515882-eb1bba00-cfc2-11eb-926c-63b2d75c028d.png)

Here is a ZIP file containing the two molecules involved in the transformation, correctly overlaid:
[RUN344-transformation.zip](https://github.com/choderalab/perses/files/6675178/RUN344-transformation.zip)

Despite the correct overlay, where all atoms (except the H -> F) are on top of each other, an incorrect atom mapping is generated by perses 0.9.0. All atoms except the H -> F should be mapped on top of each other.

@dominicrufa : Any insight into what's going on here?

**Comment by dominicrufa** [comment]
if you open the molecules in pymol and switch between them, you'll see that
the double ring structure not being mapped appropriately is actually
reoriented ever so slightly.  this is a consequence of the relative and
absolute tolerances for the deterministic atom map: here
<https://github.com/choderalab/perses/blob/d215e7a440a6c92ae585c5fea7cb34e654fca512/perses/rjmc/topology_proposal.py#L311>.
one can change the tolerance or modify the sdf-generating scheme so that
atom positions of scaffold atoms are not reoriented.

**Comment by jchodera** [comment]
Thanks! 

@dominicrufa : Since there are no docstrings, could you help me figure out
* What units are `rtol` and `atol` in?
* What do `rtol` and `atol` mean?
* Are these propagated in through any arguments path so they could be set in the YAML file or something?

**Comment by dominicrufa** [comment]
it looks like rtol and atol are the same arguments as in:
https://numpy.org/doc/stable/reference/generated/numpy.allclose.html, and
are in units w.r.t. whatever units
https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemClasses/OEMolBase.html#OEChem::OEMolBase::GetCoords
returns (i don't see units specified in openeye's  docstring). it looks
like they aren't in any arg path, so they are not accessible from a yaml
specification.

**Comment by jchodera** [comment]
Fixed by #809.
