### ISSUE TITLE
Write out YAML after parsing

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/perses#817]
Currently we don't require users to specify all options in the YAML file and instead we provide some defaults in accordance to best practices. Some options are also set dynamically depending on what other options a users sets. After we parse the YAML file and set all the options, we should write out the full YAML file. This will make it easier for users to see exactly which options are being used as well as to improve reproducibility in case our default options change later.

**Comment by mikemhenry** [comment]
I'm going to have to shuffle a few things around so that we can write out the YAML after all modifications have been set. Some keys of the setup options get modified after the `getSetupOptions` function is executed, so I will need to move all the default setting into that function so we can reliably write out the YAML file.

**Comment by jchodera** [comment]
We just need this to be "good enough" since we'll overhaul this whole functionality in [0.11.0](https://github.com/choderalab/perses/milestone/4) with the new API and a YAML structure to match.
