### ISSUE TITLE
Extending PointMutationEngine API to let allowed mutations be specified

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#82]
I think it should be easy to extend the `PointMutationEngine` to let the set of mutatable sites and allowed residues at each site be restricted.  

Right now, the allowed set of amino acids is [hard-coded here](https://github.com/choderalab/perses/blob/master/perses/rjmc/topology_proposal.py#L414):
```python
        aminos = ['ALA','ARG','ASN','ASP','CYS','GLN','GLU','GLY','HIS','ILE','LEU','LYS','MET','PHE','PRO','SER','THR','TRP','TYR','VAL']
```
Instead, we might extend the API from `PointMutationEngine` from
```python
engine = PointMutationEngine(max_point_mutants, proposal_metadata)
```
to add an optional argument:
```python
allowed_mutations = { 
   34 : ['ALA', 'LYS', 'MET'],
  142 : ['VAL', 'MET', 'LEU']
}
engine = PointMutationEngine(max_point_mutants, proposal_metadata, allowed_mutations=allowed_mutations)
```
By default, if this isn't specified, all residues are allowed to be mutated to any residue.  With the optional argument, only the residue indices in `allowed_mutations.keys()` are allowed to mutate to the residues listed in the corresponding value.  We could even get sophisticated and let the keyword `ALL` denote all amino acids:
```python
allowed_mutations = { 
   34 : ['ALA', 'LYS', 'MET'],
  142 : 'ALL'
}
```

**Comment by pgrinaway** [comment]
@juliebehr I think you implemented this, right?

**Comment by juliebehr** [comment]
Ah, yes!  I think my PR was opened before this issue, so there is currently no keyword ```ALL```.

**Comment by pgrinaway** [comment]
Ok, thanks, closing.
