### ISSUE TITLE
Need to refactor perses and dependencies to replace `import simtk.openmm` with `import openmm`

### ISSUE THREAD

**Issue by zhang-ivy** [choderalab/perses#837]
I'm using the nightly dev version of OpenMM (necessary to parametrize glycosylated systems) and getting this error when I try to run `from perses.app.relative_point_mutation_setup import PointMutationExecutor`:

```
~/miniconda3/envs/perses-rbd-ace2-direct/lib/python3.8/site-packages/perses-0.9.1-py3.8.egg/perses/app/relative_point_mutation_setup.py in <module>
      3 from perses.utils.openeye import createOEMolFromSDF, extractPositionsFromOEMol
      4 from perses.annihilation.relative import HybridTopologyFactory, RepartitionedHybridTopologyFactory
----> 5 from perses.rjmc.topology_proposal import PointMutationEngine
      6 from perses.rjmc.geometry import FFAllAngleGeometryEngine
      7 

~/miniconda3/envs/perses-rbd-ace2-direct/lib/python3.8/site-packages/perses-0.9.1-py3.8.egg/perses/rjmc/__init__.py in <module>
----> 1 from perses.rjmc import geometry, coordinate_numba, coordinate_tools, topology_proposal

~/miniconda3/envs/perses-rbd-ace2-direct/lib/python3.8/site-packages/perses-0.9.1-py3.8.egg/perses/rjmc/topology_proposal.py in <module>
     11 import numpy as np
     12 import networkx as nx
---> 13 import openmoltools.forcefield_generators as forcefield_generators
     14 from perses.storage import NetCDFStorageView
     15 from perses.rjmc.geometry import NoTorsionError

~/miniconda3/envs/perses-rbd-ace2-direct/lib/python3.8/site-packages/openmoltools/__init__.py in <module>
     24 """
     25 
---> 26 from openmoltools import amber_parser, system_checker, utils, packmol, openeye, amber, cirpy, gromacs, schrodinger

~/miniconda3/envs/perses-rbd-ace2-direct/lib/python3.8/site-packages/openmoltools/amber_parser.py in <module>
      2 import sys
      3 import math
----> 4 import simtk.openmm.app.element as element
      5 import simtk.unit as unit
      6 import subprocess

ModuleNotFoundError: No module named 'simtk.openmm.app.element'
```

When the next version of OpenMM is released, we'll need to refactor perses and dependencies (like `openmoltools`) to use the new way of importing openmm.

**Comment by mikemhenry** [comment]
We have updated `openmoltools` but have not cut a new release yet, https://github.com/choderalab/openmoltools/pull/304 
You will need to install from source, like `pip install --upgrade git+https://github.com/choderalab/openmoltools.git` and you should be good to go.

**Comment by zhang-ivy** [comment]
This worked, thanks! Should we keep this issue open as a reminder to refactor perses openmm imports?

**Comment by jchodera** [comment]
> This worked, thanks! Should we keep this issue open as a reminder to refactor perses openmm imports?

The only import we need to worry about is
```python
import simtk.openmm.app.element as element
```
which should become
```python
from openmm.app import Element
```
and then `element.Element` should just become `Element` in the code. This works with both new and old OpenMM.

Future refactoring to completely eliminate `simtk.openmm` is low priority.

**Comment by mikemhenry** [comment]
I don't think there is really anything we can do, `perses` imports `openmm` correctly with the new namespace, the error comes from  our dependencies which have been updated but just not released yet. I've got this issue https://github.com/choderalab/perses/issues/798 to keep track of when we can drop those steps in the CI.

Or is there a different issue your seeing with the `openmm imports`?

**Comment by mikemhenry** [comment]
> > This worked, thanks! Should we keep this issue open as a reminder to refactor perses openmm imports?
> 
> The only import we need to worry about is
> 
> ```python
> import simtk.openmm.app.element as element
> ```
> 
> which should become
> 
> ```python
> from openmm.app import Element
> ```

Those imports are not happening in `perses` but in `openmoltools` which has been updated, just no new release cut.

**Comment by zhang-ivy** [comment]
>perses imports openmm correctly with the new namespace

I'm not totally sure this is true. 
When I run:
```
>>> from simtk.openmm import app
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
```
I agree with John that this is a low priority issue, so I'll mark it as such

**Comment by jchodera** [comment]
> I'm not totally sure this is true.
> When I run (with the nightly dev version of OpenMM):

That's a warning we put in that this will eventually change, but we don't have a plan to remove support for `simtk.openmm` yet.

**Comment by mikemhenry** [comment]
At one point removing this style of import would break on the openmm version that we supported. Now that we use openmm >= 7.5 we could change this, but with finite dev effort it will be better to work on this later.

**Comment by zhang-ivy** [comment]
>with finite dev effort it will be better to work on this later.

Yes definitely. Was just raising this issue so that we don't forget, but definitely will not need this anytime soon, especially since John mentioned there are no plans to remove support for `simtk.openmm`!

**Comment by jchodera** [comment]
@zhang-ivy @ijpulidos @mikemhenry : Was this already addressed?

**Comment by mikemhenry** [comment]
Yes, we can close this issue.

**Comment by mikemhenry** [comment]
We are running 7.5, 7.6, and nightly in CI and things are passing
