### ISSUE TITLE
TopologyProposal usage

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/perses#84]
After a mention on #83 , I thought I would start a discussion here on potentially using `TopologyProposal` as a more general sampler-state container.

**Comment by jchodera** [comment]
`TopologyProposal` contains a paired set of old and new sampler states.  What if you instead had a `SamplerState` and `TopologyProposal` contained an old and new sampler state?

**Comment by pgrinaway** [comment]
Going to close this for now to avoid issue clutter. It can be reopened later if necessary.
