### ISSUE TITLE
Benchmarking and evaluation scripts

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#854]
We should pull in [automated scripts for running the free energy benchmark](https://www.choderalab.org/publications/2021/7/5/best-practices-for-constructing-preparing-and-evaluating-protein-ligand-binding-affinity-benchmarks) into perses.

**Comment by mikemhenry** [comment]
We should figure out a way to use something like this to track regressions 
https://asv.readthedocs.io/en/stable/

**Comment by ijpulidos** [comment]
Generate csv file until arsenic object model is refined.
