### ISSUE TITLE
docker container working with GPU

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#864]
It has been reported that the docker container is failing with running actual examples of perses using the GPU. 

This issue is raised to test this is working correctly. Probably by running it in some AWS/GCP instances and checking.

**Comment by mikemhenry** [comment]
Report from a user:

```
 Existing docker image (Perses 0.8.1) on the new A100 GPUs on GCP:

Desired platform not supported. exception raised: Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)

Warning: Returning Reference platform instead of requested platform CUDA

conducting subsequent work with the following platform: Reference

conducting subsequent work with the following platform: CPU



New docker image (Perses 0.9.1) on the V100s on GCP:


Desired platform not supported. exception raised: Error loading CUDA module: CUDA_ERROR_INVALID_PTX (218)

Warning: Returning Reference platform instead of requested platform CUDA

conducting subsequent work with the following platform: Reference

conducting subsequent work with the following platform: CPU



New docker image (Perses 0.9.1) on the A100s on GCP:


Desired platform not supported. exception raised: Error loading CUDA module: CUDA_ERROR_INVALID_PTX (218)

Warning: Returning Reference platform instead of requested platform CUDA

conducting subsequent work with the following platform: Reference

conducting subsequent work with the following platform: CPU


New docker image (Perses 0.9.1) locally (GeForce GTX 1080, Ubuntu 20.04):

Desired platform not supported. exception raised: Error initializing CUDA: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE (804) at /home/conda/feedstock_root/build_artifacts/openmm_1622798693339/work/platforms/cuda/src/CudaContext.cpp:138

Warning: Returning Reference platform instead of requested platform CUDA

conducting subsequent work with the following platform: Reference

conducting subsequent work with the following platform: CPU


nvidia-smi works in the local container.
```
On these nodes
![image](https://user-images.githubusercontent.com/11765982/132422410-99dbeefc-a1ea-4b9f-96d7-d116de5be778.png)
![image](https://user-images.githubusercontent.com/11765982/132422441-a7dd25d8-6b57-49fc-af1f-b1c02ac10860.png)

**Comment by jchodera** [comment]
> Desired platform not supported. exception raised: Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)

Could be a few things regarding CUDA version and driver mismatch, but since this is an A100 (where support was introduce in CUDA 11), it could just be that the `cudatoolkit` version (or driver) is not sufficiently recent.

**Comment by mikemhenry** [comment]
It looks like the issue was the container had `CUDA 11.2.2` but the google cos had `11.0`. I built an image using  `11.0.3` I tested it and will have Molly test it out next!

**Comment by schmolly** [comment]
The perses:0.9.2-cuda-11.0.3 image works on both the A100s and V100s! Thank you so much, Mike! :partying_face:

**Comment by mikemhenry** [comment]
Awesome! That is great to hear! I'll get the changes pushed to our recipe and also do a bit of follow-up research to see if we can do anything to make our builds less sensitive to the CUDA version on the host (or at least see if we can ship support more than one CUDA version)
