### ISSUE TITLE
Should SystemGenerator live in perses.rjmc.topology_proposal?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#88]
Is `perses.rjmc.topology_proposal` the best home for this class?

**Comment by pgrinaway** [comment]
Do you think it would be better somewhere else? I don't really have a preference.

**Comment by jchodera** [comment]
Right now, it would be the same, not necessarily better. So let's punt on changing it until it becomes obvious it would be better elsewhere

**Comment by pgrinaway** [comment]
Ok. Closing this then.
