### ISSUE TITLE
Add OpenEye beta tests to CI

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#883]
We should add OpenEye toolkits beta candidates to our CI.

**Comment by ijpulidos** [comment]
As noted by the `openff-toolkit` folks [here](https://github.com/openforcefield/openff-toolkit/pull/1111), OpenEye releses several beta candidates before the actual rc. I guess we could just test the actual rc once it hits the conda channel after the betas.

**Comment by ijpulidos** [comment]
@mikemhenry What do you think? Should we do this by adding a variable to our current matrix or by specifying a whole different job? Or something else?

**Comment by mikemhenry** [comment]
That's a good question and I've been thinking about it too, maybe we just add it to the nightly openmm tests? Since then they don't need to pass and we are testing bleeding edge
