### ISSUE TITLE
examples on running protein-ligand relative binding calculations

### ISSUE THREAD

**Issue by freeenergylab** [choderalab/perses#888]
Hey @here,

Are there some examples of how to run protein-ligand relative binding calculations using `perses` without neq-switching? Only use the equilibrium alchemical simulations. 
I have two small-molecule `.sdf` files and one protein `.pdb` file. Both molecules have been aligned together based on the common core atom mapping.

Thanks!

Best,
Pengfei

**Comment by ijpulidos** [comment]
Hi @freeenergylab , we do have an example for such a system in the `examples/protein-ligand/cli` which you could run with something like `perses-relative ani.yaml`. You might want to to give that a shot. 

We do have to make the documentation clearer on these examples. We will work on that. Hope this works.

**Comment by freeenergylab** [comment]
<img width="772" alt="image" src="https://user-images.githubusercontent.com/9461715/140462697-a9ec829f-e13f-4bbb-b678-80c676fb8652.png">
The `Perses` heavily depends on the `openeye`. I do not have the license of `openeye`. Could it be replaced by the open-source packages e.g. `rdkit`, `openbabel` et al?

**Comment by pengfeili-tandemai** [comment]
I have one scenario where I have the AMBER `prmtop` and `inpcrd` files including both aligned together ligand topology and positions. Are there quick ways to run protein-ligand binding using perses? Thanks!

**Comment by freeenergylab** [comment]
I have one scenario where I have the AMBER `prmtop` and `inpcrd` files including both aligned together ligand topology and positions. Are there quick ways to run protein-ligand binding using `perses`? Thanks!

**Comment by jchodera** [comment]
> The `Perses` heavily depends on the `openeye`. I do not have the license of `openeye`. Could it be replaced by the open-source packages e.g. `rdkit`, `openbabel` et al?

Replacing OpenEye toolkit dependencies with the [Open Force Field Toolkit](http://openforcefield.org)---which provides an abstraction layer to multiple toolkits, including the open source RDKit---is on our roadmap, but it is not urgent for the folks funding development at the moment.

> I have one scenario where I have the AMBER prmtop and inpcrd files including both aligned together ligand topology and positions. Are there quick ways to run protein-ligand binding using perses? Thanks!

This is not currently on our roadmap, but if you like, you could submit a feature request where you would specify prmtop/inpcrd files for each state and have perses run a free energy calculation. I can't guarantee when we would be able to get to this due to very limited development resources, however.

**Comment by freeenergylab** [comment]
Hey there, 

If I set up one relative binding free energy calculation using `fe_type: repex`, which parameter can be used to control the total simulation time for each `lambda` window?

Thanks!

**Comment by pengfeili-tandemai** [comment]
From the equilibrated structures by Amber, I ran simulations w/o `repex` successfully recently. Close here.

**Comment by freeenergylab** [comment]
From the equilibrated structures by Amber, I ran simulations w/o repex successfully recently. Close here.
