### ISSUE TITLE
TopologyProposal should contain keys of old and new states

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#89]
We should have TopologyProposal contain unique keys for old and new states. These keys will need to be matched up across different samplers to do the free energy adaptation. 

Metadata isn't the best place for this since it is integral to the sampling scheme. I envision metadata as being something that ProposalEngine might need or analysis scripts might find useful.

**Comment by jchodera** [comment]
Should I implement this in my PR?  And if so, how should this work?

**Comment by jchodera** [comment]
Actually, could @pgrinaway and @juliebehr implement this, since it will require you add some mechanism to `PointMutationEngine` and `SmallMoleculeSetProposalEngine` to generate a unique key for each proposed state?  You don't have to call it `key`---something like `state` or `chemical_state_key` or something would work.  It just needs to be a hashable object.

**Comment by pgrinaway** [comment]
+1. I can do that. I think that (canonical isomeric) SMILES allows [tautomer specification] (http://www.daylight.com/meetings/summerschool98/course/dave/smiles-convent.html), and a quick check with openeye seems to demonstrate that the openeye tools are happy with it. Protonation state changes can also be reflected in SMILES, right? So I suggest:

1) canonical isomeric SMILES string for chemical identity
2) sequence for protein identity

Is that ok?

**Comment by jchodera** [comment]
Sounds great.

At some point, we might think of allowing a `set` or `tuple` of `ProposalEngine`s to be specified to propose multiple chemical changes in a Gibbs sampling framework, but we can just use a `set` or `tuple` of those keys at that point.

What do you want to call it?  `key`?  `chemical_state`?  `sampler_discrete_state`?  `bob`?

**Comment by pgrinaway** [comment]
`chemical_state_key`?

**Comment by jchodera** [comment]
Sure. Can always change it later.

**Comment by pgrinaway** [comment]
Added `chemical_state_key` in #97
