### ISSUE TITLE
How big are the chemical state spaces we are supporting?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#90]
This is relevant for how we should represent the log weights for expanded ensemble and SAMS samplers.  

* How big are the chemical state spaces we are supporting?  
* Can we assume we will have some way to enumerate all possible chemical state `key`s at the beginning?  If so, how would we retrieve this list of `key`s from the `ProposalEngine`?
* Should we instead be lazy and only keep track of the `key`s for states we have encountered so far?  If so, can all of the recursion strategies described in [the SAMS paper](http://www.stat.rutgers.edu/home/ztan/Publication/SAMS_redo4.pdf) support this strategy, where only the visited state (and maybe others in its neighborhood) are updated each iteration?

**Comment by pgrinaway** [comment]
> How big are the chemical state spaces we are supporting?

I think it's finite, in the case of a bag of molecules or mutations, and finite of unknown cardinality for reaction-aware proposals.

>Can we assume we will have some way to enumerate all possible chemical state keys at the beginning? If so, how would we retrieve this list of keys from the ProposalEngine?

Not in the reaction-aware case (or perhaps we will find a way, but I don't think we should assume that that's true). In the other cases, we could add a property that allows retrieval of such a thing. It is given in the constructor, anyway.

>Should we instead be lazy and only keep track of the keys for states we have encountered so far? If so, can all of the recursion strategies described in the SAMS paper support this strategy, where only the visited state (and maybe others in its neighborhood) are updated each iteration?

I think that being lazy is more scalable, but for smaller sets maybe we'd just want to pre-enumerate the entire thing?

**Comment by jchodera** [comment]
OK, so we will assume 
* Chemical/mutation space is finite but either of known or unknown cardinality
* We won't have a convenient way to pre-enumerate all states
* We wil assume all proposals are "local", in that one or a small number of proposals are considered at a time
* We will use free energy update rules that assume estimates of free energies for unvisited states will remain at zero, and updates for visited states are computed relative to this.  This requires carefully modifying the update rules as we implement them.
