### ISSUE TITLE
hybrid_complex.pdb no longer being generated by fah-generator

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#906]
It appears that one of our changes removed the generation of `hybrid_complex.pdb` files, required by the COVID Moonshot sprint infrastructure, from being generated by `fah-generator`.

Anybody know when or why this happened, and how I can generate this file from any of these files that _were_ generated?
```
atom_map.png
core.xml
htf.npz
hybrid_atom_mappings.npz
integrator.xml.bz2
new_complex.pdb
old_complex.pdb
perses.yaml
references.npy
state.xml.bz2
system.xml.bz2
```

**Comment by jchodera** [comment]
In the interim, I’m going to see if I can modify the Moonshot sprint code to deal with this.
I think I can use the `hybrid_atom_mappings.npz` and `{old|new}_complex.pdb` instead.

I seem to recall this change was because the `Topology` objects could not correctly handle the hybrid system, so these three files are the preferred alternative solution?

**Comment by mikemhenry** [comment]
@jchodera  I'm away from a computer right now, but if you can grep the code for where we do the file IO, checking the git history on GitHub with the annotate button should help spot which PR made the regression.

**Comment by mikemhenry** [comment]
Maybe this one? https://github.com/choderalab/perses/pull/839

**Comment by jchodera** [comment]
I'm trying to figure out how to extract the required data from the `hybrid_atom_mappings.npz`. Can someone confirm that this is it?
```python
import numpy as np
mappings = np.load(hybrid_atom_mappings_filename, allow_pickle=True)
hybrid_to_old_map = mappings['hybrid_to_old_map']
hybrid_to_new_map = mappings['hybrid_to_new_map']
```

**Comment by jchodera** [comment]
@ijpulidos posted how to access this data here:
https://github.com/choderalab/perses/issues/752#issuecomment-894579125
```python
npzfile = np.load('/path/to/hybrid_atom_mappings.npz', allow_pickle=True)
npzfile.files
['hybrid_to_old_map', 'hybrid_to_new_map']
npzfile['hybrid_to_new_map'].flat[0]
```

**Comment by ijpulidos** [comment]
Yes, I now remember this, was a while ago and I didn't remember. I think we settled on doing it that way (using numpy objects with the topology mappings), instead of the PDB. Do we need a test for covid moonshot? Is it possible to change the covid moonshot script to adapt to the new behavior? I guess we can easily bring the old behavior back, if required, as well.

**Comment by jchodera** [comment]
OK, I think I've figured out a way to reconstruct the old `hybrid_complex.pdb` files, though this approach is very slow:
```python
import numpy as np
import mdtraj as md
import openmm # openmm 7.6
htf = np.load('/home/server/server2/projects/13458/RUNS/RUN43/htf.npz', allow_pickle=True)['arr_0'].tolist()
traj = md.Trajectory(htf.hybrid_topology, htf.hybrid_positions)
traj.remove_solvent(exclude=['CL', 'NA'], inplace=True)
traj.save(f'hybrid_complex.pdb')
```
This requires the same conda environment as was used to create the `npz` file.

There may be a faster way to do this by loading the atom mappings and old/new PDB files and "zipping" them together by directly operating on the MDTraj data model. I'll have to explore this if this becomes a bottleneck.
