### ISSUE TITLE
Why do ProposalEngine and TopologyProposal need `beta`?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#91]
Why do `ProposalEngine` and `TopologyProposal` need `beta`?

If `Force` objects inside of the `System` need their temperatures updated, this can be done automatically by the samplers.  Can we take this out of `ProposalEngine` and `TopologyProposal`?

Maybe we can also make `metadata` arguments in constructors default to `None`?

**Comment by pgrinaway** [comment]
The idea is that perhaps the chemical state proposals may want to take temperature into account. But in that sense, passing in `ThermodynamicState` might be better.

**Comment by jchodera** [comment]
How about we ditch it for now, and if we really need it, have `ProposalEngine` accept `ThermodynamicState`.

**Comment by pgrinaway** [comment]
+1, sounds good. I'll do this now.

**Comment by pgrinaway** [comment]
Resolved in #96
