### ISSUE TITLE
Make all the hydrogens use 4 AMU as mass in System Generator

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#921]
CC #918

**Comment by jchodera** [comment]
For now, the fix in #924 that changes the default `hmass` from 4 to 3 should eliminate most problems, so I'll close this:
https://github.com/choderalab/perses/pull/924/files#diff-e1c4e01dac650f7e0590709ad7a500582fbe004cd1fc2ef5a1d58ec54c0fecabR57

I've opened an issue in `SystemGenerator` to offer this option instead:
https://github.com/openmm/openmmforcefields/issues/185
