### ISSUE TITLE
Rename primary branch to 'main'

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#929]
Let's follow [best practices](https://github.com/github/renaming) and rename the `master` branch to `main`.

**Comment by ijpulidos** [comment]
This was already done. Thanks @mikemhenry !! Github should alert people when they first visit perses after the change to perform the following instructions on their local repositories, I'm just leaving them here just in case:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
