### ISSUE TITLE
Create Docker with new CLI

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/perses#933]
@jchodera I just wanted to make sure that the dummy/testing CLI has the functionality we want:

- [ ] Reads in a yaml file and checks the input
- [ ] Checks to make sure we can use a CUDA context
- [ ] Creates some dummy/mock output files 

I'm working on this right now and should have it done by tomorrow, but I wanted to make sure I wasn't missing anything.

**Comment by jchodera** [comment]
This is correct!
I think we want to make sure we craft the CLI we want to use for this and just not wire it up to the rest of perses quite yet.

**Comment by mikemhenry** [comment]
That's exactly what I'm doing :+1:

**Comment by mikemhenry** [comment]
PR here https://github.com/choderalab/perses/pull/934

**Comment by ijpulidos** [comment]
Add a point in our CLI that does the test from http://docs.openmm.org/latest/userguide/library/02_compiling.html#step-3-install-the-python-api

**Comment by mikemhenry** [comment]
Going to re-open this issue to remind myself to build the docker image once we get 0.9.4 released

**Comment by mikemhenry** [comment]
Assuming that you have `protein-ligand.yaml` in your working directory (`pwd`) then this command should run the CLI, I've created a docker image with the tag `dev` that has perses 0.9.4 

`docker run -it --rm --gpus device=0 --mount type=bind,source=$HOME/.openeye/,target=/openeye/,readonly --mount type=bind,source=$(pwd),target=/mnt/ choderalab/perses:dev perses-cli --yaml /mnt/protein-ligand.yaml`
