### ISSUE TITLE
perses app that uses any MultiStateSampler (including ReplicaExchangeSampler and subclasses) should minimize before simulation

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#936]
Right now, none of the perses apps that use`ReplicaExchangeSampler` and friends call `sampler.minmize()` before they start simulation. We should change this, since it is essential for ensuring stability of the resulting simulations.

Minimization should occur by default, but should be something we can override via the API or YAML.

Note that we should not re-minimize while resuming, however.

**Comment by ijpulidos** [comment]
Should the [default parameters](https://github.com/choderalab/openmmtools/blob/main/openmmtools/multistate/multistatesampler.py#L569-L570) be sane enough for this purpose? Considering that by default there is not limit on the number of iterations.

**Comment by jchodera** [comment]
Yes, the defaults should be fine!

In the future API overhaul, our approach should be to have either the YAML,
CLI, or API delegate kwargs to the appropriate method automatically, like

sampler.minimization = True
sampler.minimization.options.max_iterations = 20

This isn't exactly what we would do, but hopefully communicates how we
would like to automatically delegate options rather than having to
explicitly handle each one. In future, adding a new optional argument or
class field should not require any changes to the API, CLI, of YAML
handling code to be able to accept overrides for these options.
