### ISSUE TITLE
Tests suddenly taking more time

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#945]
Hmm interesting, any ideas why is it taking so much more in tests now? Specially with [perses/tests/test_resume.py::test_resume_protein_mutation_no_checkpoint](https://github.com/choderalab/perses/runs/5326885279?check_suite_focus=true#step:9:329), compared to what it was spending before [here](https://github.com/choderalab/perses/runs/5099918214?check_suite_focus=true#step:9:331).  I know some [testing concurrency changed](https://github.com/choderalab/perses/pull/934/files#diff-b268bb7dc66e8638921e223098a11eabb92b424875ec72a19d6145dc1efbe3f2R14-R17) in this PR, but not sure if that can explain it. I'm having a hard time trying to run tests locally.

_Originally posted by @ijpulidos in https://github.com/choderalab/perses/issues/934#issuecomment-1050419800_

**Comment by mikemhenry** [comment]
https://github.com/choderalab/perses/pull/961
fixes this issue

**Comment by mikemhenry** [comment]
I really don't understand why, but this PR has some background
https://github.com/choderalab/perses/issues/945
