### ISSUE TITLE
Visualizing Trajectories

### ISSUE THREAD

**Issue by casebeerVRTX** [choderalab/perses#946]
@slochower  and I recently ran some ligand transformations using perses and would like to visualize the trajectories (particularly the end states) to make sure everything looks okay. Last summer @dominicrufa pointed us to this script as an example of how to extract the trajectories: https://github.com/hannahbrucemacdonald/endstate_pdbs/blob/master/scripts/input_for_pol_calc.py

We're getting an unexpected error from the pickles. The `openeye` module is installed in our `perses` conda environment which we used to generate the pickles and also here, yet we're seeing a `ModuleNotFoundError`

```

python input_for_pol_calc.py

Warning: importing 'simtk.openmm' is deprecated. Import 'openmm' instead.

Traceback (most recent call last):

File "/cluster/home/casebeer/perses/XXX/lig2to1/input_for_pol_calc.py", line 7, in <module>

htf = htf['arr_0']

File "/cluster/home/casebeer/anaconda3/envs/perses/lib/python3.9/site-packages/numpy/lib/npyio.py", line 254, in __getitem__

return format.read_array(bytes,

File "/cluster/home/casebeer/anaconda3/envs/perses/lib/python3.9/site-packages/numpy/lib/format.py", line 748, in read_array

array = pickle.load(fp, **pickle_kwargs)

ModuleNotFoundError: No module named 'oechem'

```

Is there a recommended debugging step? I know pickles can be finnicky with module paths, but I'm not sure what is happening now since the environment hasn't changed.

I noticed that there is also an in-development visualization module: https://github.com/choderalab/perses/blob/main/perses/analysis/visualization.py Can I use this to look at the trajectories? (I'm not sure we have `old.pdb` and `new.pdb` and I'm not exactly sure how to generate the unique selection strings.)

This is a first step in troubleshooting some transformations that produced unusually terrible results, so we want to check the obvious things like whether the ligand stays in the pocket and the states are mixing acceptably.

**Comment by mikemhenry** [comment]
Yes pickles can be really tricky! Sometimes when modules are missing, you can add the imports to the file before you un-pickle them, so try putting `from openeye import oechem` before you load the pickle and see if that helps!

**Comment by casebeerVRTX** [comment]
Thank you, that seems to have fixed the pickle issue! The script is now able to read in the pickles. What is the best way to visualize the trajectories? We are trying to do some reality checks on our perses runs.
