### ISSUE TITLE
Should PointMutationEngine get ffxmls from SystemGenerator?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#95]
`PointMutationEngine` takes a `SystemGenerator` as an argument. Can it just get the `ffxmls` from this instead of requiring they be passed in as `metadata`?
https://github.com/choderalab/perses/blob/master/perses/rjmc/topology_proposal.py#L337

**Comment by pgrinaway** [comment]
Yeah, this is a good point. Actually, we can probably just get rid of the `metadata` constructor parameter.

**Comment by jchodera** [comment]
My concept originally was that each "sampler state" would have
* current `Topology` --- the system we're simulating
* current `positions` --- the coordinates
* current `metadata` --- any additional information the specific `ProposalEngine` subclass may need, like which mutant is active, what SMILES string is active, etc.  As observed in #94, we could alternatively have a `SamplerState` base class and a variety of subclasses for different `ProposalEngine`s to use, but that is probably (1) not any help, and (2) would make it harder to combine two `ProposalEngine`s unless we instead use mixins, and then things get complicated.

A topology proposal would then need:
* old and new `Topology`
* old and new `positions`
* old and new `metadata`

We also store information about the old and new `System` objects because it was convenient to shove `SystemGenerator` into `ProposalEngine`.  This is fine for now, but I wonder if this should eventually migrate out so `ProposalEngine` can just focus on topologies and positions.

**Comment by jchodera** [comment]
Addressed by #96

**Comment by jchodera** [comment]
Whoops, closed this too soon.  @juliebehr : Can you change `PointMutationEngine` to get the `ffxmls` from `SystemGenerator` using the new `SystemBuilder.ffxmls` property that @pgrinaway added?

**Comment by juliebehr** [comment]
Resolved https://github.com/choderalab/perses/pull/108
