### ISSUE TITLE
Potential misuse of context cache in multistate samplers 

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/perses#963]
@ijpulidos Could you take a look at https://github.com/choderalab/perses/blob/main/perses/samplers/multistate.py#L10 and double check things are not problematic with it? I noticed it while hunting down another issue.

**Comment by jchodera** [comment]
I've opened an issue here: https://github.com/choderalab/openmmtools/issues/558

**Comment by ijpulidos** [comment]
We shouldn't change the global context cache behavior, instead we should use the new "idiomatic" way of dealing with this as in https://github.com/choderalab/perses/blob/393b78faf46cc91d555ad3a7c7780710a93930b0/perses/app/setup_relative_calculation.py#L316

**Comment by ijpulidos** [comment]
We create the context caches here https://github.com/choderalab/perses/blob/393b78faf46cc91d555ad3a7c7780710a93930b0/perses/app/setup_relative_calculation.py#L672-L673

**Comment by jchodera** [comment]
> We have some utils duplicated in perses that are also in openmmtools

@mikemhenry : Let's open another issue to migrate utils to openmmtools and use those when able.

**Comment by ijpulidos** [comment]
I checked the possible misuses of context caches in the code and I believe these were already handled in #977. Closing.
